#define FILE_START_POS	0xBD//189		//mailhead's position 
#define FILE_START_POS	0xBD//189		//mailhead's position 
#define FILE_START_POS	0xBD//189		//mailhead's position 

#define BLOCK_NUMBER	10
#define FIND_SCOPE		50
#define FOURBYTE		4

#define SEARCH_LENGTH   1000
#define TOKEN_ARRAY_LEN 300

#define MSG_DATA_PATH	"/var/xinghao"
#define MSG_MOUNT_PATH	"/var/mount"
#define MSG_MIDDLE_PATH	"/var/middle"
//#define MSG_MOUNT_PATH	"/var/tmp"
//#define MSG_RESULT_PATH	"/var/xinghao"
#define MSG_RESULT_PATH	"/var/xinghao"

#define REMOTE_COMPUTER_IP	"202.196.100.160"

#define EMAIL_TYPE_PASSWD		1
#define EMAIL_TYPE_PURETEXT		2
#define EMAIL_TYPE_GENERAL_W	31
#define EMAIL_TYPE_GENERAL_U	32
#define EMAIL_TYPE_DELETE		-1

#define ITEM_NOT_EXIST			-1
#define ITEM_EXIST				0

#define BACK_LENGTH				50

#define SECTOR_TYPE_CQG		100
#define SECTOR_TYPE_CQB		101
#define SECTOR_TYPE_CBG		110
#define SECTOR_TYPE_CBB		111

#define SECTOR_TYPE_AQ		20
#define SECTOR_TYPE_QB		21
