//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 isCliHelp.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDC_CHECK_effectiveImmediately  101
#define IDC_BUTTON_quit                 108
#define IDC_BUTTON_policy               118
#define IDR_MAINFRAME                   128
#define IDB_qnmIcons                    130
#define IDD_instantAssistant_start      135
#define IDD_instantAssistant_av         136
#define IDD_msgList                     138
#define IDR_QYMCPOPUP                   143
#define IDB_LARGEICONS                  144
#define IDB_SMALLICONS                  145
#define IDR_MC_CFG                      160
#define IDD_shhgPcProperties            178
#define IDD_qnmSearch                   197
#define IDD_qnmEventSearch              199
#define IDR_MC_MGR                      200
#define IDD_qnmClearup                  216
#define IDD_clearupEventCond            217
#define IDD_qnmSendHint                 227
#define IDD_qnmEditPcUsrInfo            230
#define IDD_talk                        312
#define IDD_prop_messenger              319
#define IDD_prop_imTask                 320
#define IDD_prop_imGrp                  322
#define IDD_select_isCli                323
#define IDD_prop_imMsg                  324
#define IDD_policy_isClient             326
#define IDD_imMsgSearch                 330
#define IDR_MENU_null                   333
#define IDD_desktopsMon                 345
#define IDD_cfgVideoConference          347
#define IDD_instantAssistant_0          352
#define IDD_instantAssistant_vw         353
#define IDD_instantAssistant            354
#define IDD_videoCompressors            355
#define IDD_cfgWmv                      356
#define IDD_mediaControl                357
#define IDD_toolbox_sketchPad           362
#define IDB_select                      365
#define IDB_rectangle                   366
#define IDD_messenger_isClient          370
#define IDR_MENU_const                  371
#define IDD_imObjRule                   374
#define IDD_policyAv                    380
#define IDD_selectAvDev                 381
#define IDD_instantAssistant_start_wait 384
#define IDD_qyBar                       388
#define IDD_qyMenu                      389
#define IDD_menu_isCli_walls            390
#define IDD_listView_db                 391
#define IDD_listView                    392
#define IDD_ptzControl                  393
#define IDD_ptzSettings                 394
#define IDD_menu_isCli_walls_ts         395
#define IDD_test_isCli                  419
#define IDD_videoTagCfg                 420
#define IDD_subtitle_select             421
#define IDC_BUTTON_setDev2fpsSettings   451
#define IDC_STATIC_setDev2fpsSettings   452
#define IDC_BUTTON_setDev5fpsSettings   453
#define IDC_STATIC_setDev5fpsSettings   454
#define IDC_BUTTON_setDev5fpsSettings1  455
#define IDC_STATIC_setDev5fpsSettings1  456
#define IDC_BUTTON_setDev5fpsSettings2  457
#define IDC_STATIC_setDev5fpsSettings2  458
#define IDC_BUTTON_contact              1000
#define IDC_STATIC_dlgDesc              1000
#define IDC_BUTTON_group                1001
#define IDC_title                       1004
#define IDC_hint0                       1006
#define IDD_objs                        1007
#define IDD_instantAssistant_1          1008
#define IDC_COMBO_ptzProtoType          1009
#define IDC_BUTTON_PLAY                 1009
#define IDD_status_cli                  1009
#define IDC_EDIT_ptzAddr                1010
#define IDC_BUTTON_STOP                 1010
#define IDC_COMBO_comName               1011
#define IDC_COMBO_comRate               1012
#define IDC_COMBO_comParity             1013
#define IDC_CHECK_MUTE                  1013
#define IDC_COMBO_comData               1014
#define IDC_LIST0                       1014
#define IDC_CHECK_LOOP                  1014
#define IDC_COMBO_comStopBit            1015
#define IDC_EDIT1                       1015
#define IDC_EDIT_uiAudioDataAddedToPlayEveryTime 1016
#define IDC_CHECK_PLAYTHROUGH           1016
#define IDC_BITRATE                     1017
#define IDC_EDIT_uiNotifyIntervalInMs_needMoreAudioData 1017
#define IDC_BUFFERDELAY                 1018
#define IDC_MAXKEYDISTANCE              1021
#define IDC_BUTTON_FRAMESTEP            1022
#define IDC_EDIT8                       1022
#define IDC_EDIT9                       1023
#define IDC_EDIT10                      1024
#define IDC_FRAMERATE                   1025
#define IDC_EDIT11                      1025
#define IDC_QUALITY                     1026
#define IDC_EDIT12                      1026
#define IDC_VBRQUALITY                  1027
#define IDC_hint1                       1027
#define IDC_PROFILES                    1028
#define IDC_PROGRESS_reg                1028
#define IDC_CBR                         1029
#define IDC_EDIT13                      1029
#define IDC_COMPLEXITY                  1030
#define IDC_EDIT14                      1030
#define IDC_QUALITY_VBR                 1031
#define IDC_EDIT15                      1031
#define IDC_EDIT16                      1032
#define IDC_EDIT17                      1033
#define IDC_EDIT18                      1034
#define IDC_EDIT19                      1035
#define IDC_SLIDER                      1036
#define IDC_STATIC_POSITION             1037
#define IDC_STATIC0                     1040
#define IDC_STATIC30                    1041
#define IDC_EDIT0                       1041
#define IDC_STATIC31                    1042
#define IDC_COMBO0                      1042
#define IDC_STATIC32                    1043
#define IDC_IP                          1043
#define IDC_STATIC33                    1044
#define IDC_STATIC34                    1045
#define IDC_STATIC35                    1046
#define IDC_STATIC36                    1047
#define IDC_ip0                         1047
#define IDC_STATIC37                    1048
#define IDC_STARTDATE                   1048
#define IDC_ip1                         1048
#define IDC_STATIC38                    1049
#define IDC_STARTTIME                   1049
#define IDC_STATIC39                    1050
#define IDC_ENDDATE                     1050
#define IDC_ip2                         1050
#define IDC_STATIC40                    1051
#define IDC_ENDTIME                     1051
#define IDC_STATIC41                    1052
#define IDC_COMBO1                      1052
#define IDC_STATIC42                    1053
#define IDC_COMBO2                      1053
#define IDC_STATIC43                    1054
#define IDC_COMBO3                      1054
#define IDC_STATIC44                    1055
#define IDC_COMBO4                      1055
#define IDC_STATIC45                    1056
#define IDC_COMBO5                      1056
#define IDC_COMBO6                      1057
#define IDC_COMBO7                      1058
#define IDC_COMBO8                      1059
#define IDC_DEL                         1059
#define IDC_COMBO9                      1060
#define IDC_STATIC1                     1070
#define IDC_STATIC2                     1071
#define IDC_STATIC3                     1072
#define IDC_STATIC4                     1073
#define IDC_STATIC5                     1074
#define IDC_STATIC6                     1075
#define IDC_STATIC7                     1076
#define IDC_ADD                         1076
#define IDC_STATIC8                     1077
#define IDC_STATIC9                     1079
#define IDC_STATIC10                    1080
#define IDC_STATIC11                    1081
#define IDC_STATIC12                    1082
#define IDC_STATIC13                    1083
#define IDC_STATIC14                    1084
#define IDC_STATIC15                    1085
#define IDC_STATIC16                    1086
#define IDC_STATIC17                    1087
#define IDC_STATIC18                    1088
#define IDC_STATIC19                    1089
#define IDC_STATIC20                    1090
#define IDC_STATIC21                    1091
#define IDC_mac0                        1092
#define IDC_STATIC22                    1092
#define IDC_mac1                        1093
#define IDC_STATIC23                    1093
#define IDC_mac2                        1094
#define IDC_STATIC24                    1094
#define IDC_servicePack                 1095
#define IDC_STATIC25                    1095
#define IDC_osName                      1096
#define IDC_STATIC26                    1096
#define IDC_lastCommTime                1097
#define IDC_STATIC27                    1097
#define IDC_auditTime                   1098
#define IDC_regTime                     1099
#define IDC_curUsrName                  1100
#define IDC_STATIC28                    1100
#define IDC_qwmVer                      1101
#define IDC_proxyServer                 1102
#define IDC_STATIC29                    1102
#define IDC_EDIT2                       1106
#define IDC_EDIT3                       1108
#define IDC_EDIT4                       1110
#define IDC_EDIT5                       1113
#define IDC_EDIT6                       1116
#define IDC_EDIT7                       1119
#define IDC_pcName                      1129
#define IDC_STATIC_ip                   1153
#define IDC_STATIC_mac                  1155
#define IDC_EDIT_mac                    1156
#define IDC_COMBO_queryType             1157
#define IDC_COMBO_eventType             1159
#define IDC_STATIC_ver                  1160
#define IDC_pc0_zongBu                  1162
#define IDC_pc1                         1163
#define IDC_pc2_benBu                   1164
#define IDC_pc3                         1165
#define IDC_pc4_danWei                  1166
#define IDC_pc5                         1167
#define IDC_pc6_qiTaDanWei              1168
#define IDC_pc7                         1169
#define IDC_pc8_buMen                   1170
#define IDC_pc9                         1171
#define IDC_pc10_shiYongRen             1172
#define IDC_pc11                        1173
#define IDC_pc12_jiQiLeiXing            1174
#define IDC_pc13                        1175
#define IDC_pc14_ziChanBianHao          1176
#define IDC_pc15                        1177
#define IDC_pc16_zhuYaoYongTu           1178
#define IDC_pc17                        1179
#define IDC_pc18_lianXiDianHua          1180
#define IDC_pc19                        1181
#define IDC_pc20_shiYongDiDian          1182
#define IDC_pc21                        1183
#define IDC_pc22_shiYongDiDian          1184
#define IDC_pc23                        1185
#define IDC_STATIC_hint                 1186
#define IDC_pc24_ziChanBianHao1         1186
#define IDC_pc25                        1187
#define IDC_STATIC_eventType            1187
#define IDC_pc26_ziChanShuoMing1        1188
#define IDC_pc27                        1189
#define IDC_CHECK_ucbLooping_mediaFile  1190
#define IDC_pc28_ziChanBianHao2         1190
#define IDC_CHECK_distinguishSharedWebcams 1191
#define IDC_pc30_ziChanShuoMing2        1192
#define IDC_pc31                        1193
#define IDC_RADIO_clearupScannedIp      1205
#define IDC_RADIO_clearupEvent          1206
#define IDC_EDIT_hint                   1216
#define IDC_STATIC_type                 1219
#define IDC_STATIC_startTime            1254
#define IDC_STATIC_lastCommTime         1255
#define IDC_STATIC_auditTime            1279
#define IDC_STATIC_mac0                 1308
#define IDC_STATIC_name                 1310
#define IDC_STATIC_endTime              1312
#define IDC_EDIT_name                   1335
#define IDC_STATIC_staticType           1442
#define IDC_STATIC_qycxCopyRight        1463
#define IDC_STATIC_passwd0              1464
#define IDC_STATIC_passwd1              1465
#define IDC_STATIC_condition            1468
#define IDC_STATIC_usrInfoZone          1478
#define IDC_STATIC_pcName               1479
#define IDC_STATIC_osName               1480
#define IDC_STATIC_servicePack          1481
#define IDC_STATIC_ip0                  1482
#define IDC_STATIC_mac1                 1483
#define IDC_STATIC_ip1                  1484
#define IDC_STATIC_mac2                 1485
#define IDC_STATIC_ip2                  1486
#define IDC_STATIC_qwmVer               1487
#define IDC_STATIC_regTime              1488
#define IDC_STATIC_clearHint            1490
#define IDC_STATIC_staticName           1494
#define IDC_STATIC_queryType            1498
#define IDC_BUTTON_browseDir            1570
#define IDC_BUTTON_browseIcDir          1571
#define IDC_RADIO_procModuleKnowlege    1645
#define IDC_CHECK_bottomUp              1756
#define IDC_RADIO_procRegistryKnowlege  1787
#define IDC_BUTTON_avCompressor_req     1822
#define IDC_BUTTON_avCompressor_req_3d  1823
#define IDC_LIST_subtitles              1858
#define IDC_list                        1858
#define IDC_STATIC_sn                   1863
#define IDC_STATIC_recentMsgList        1864
#define IDC_STATIC_input                1865
#define IDC_BUTTON_screenCompressor     1868
#define IDC_request                     1868
#define IDC_LIST_task                   1871
#define IDC_STATIC_peerDesc             1872
#define IDC_STATIC_instantStatus        1874
#define IDC_LIST_members                1875
#define IDC_STATIC_staticSender         1878
#define IDC_STATIC_idInfo_send          1879
#define IDC_STATIC_staticReceiver       1881
#define IDC_STATIC_idInfo_recv          1882
#define IDC_STATIC_receiverDesc         1883
#define IDC_STATIC_staticSendTime       1884
#define IDC_STATIC_sendTime             1885
#define IDC_STATIC_staticRecvTime       1886
#define IDC_STATIC_recvTime             1887
#define IDC_STATIC_staticSubject        1888
#define IDC_STATIC_subject              1889
#define IDC_STATIC_staticContent        1890
#define IDC_STATIC_content              1891
#define IDC_STATIC_senderDesc           1892
#define IDC_STATIC_staticImTaskStatus   1893
#define IDC_STATIC_imTaskStatus         1894
#define IDC_BUTTON_webcamCompressor     1895
#define IDC_STATIC_videoCompressor      1896
#define IDC_COMBO_objList               1897
#define IDC_STATIC_staticMessengerId    1898
#define IDC_STATIC_messengerId          1899
#define IDC_STATIC_staticRuleIfMsgArrive 1900
#define IDC_COMBO_ruleIfMsgArrive       1901
#define IDC_STATIC_audioCompressor      1903
#define IDC_STATIC_staticDirToSaveFile  1904
#define IDC_EDIT_dirToSaveFile          1905
#define IDC_EDIT_dirToSaveICFile        1906
#define IDC_STATIC_staticDirToSaveICFile 1907
#define IDC_STATIC_staticTalker         1917
#define IDC_EDIT_talker                 1918
#define IDC_STATIC_staticId             1919
#define IDC_EDIT_Id                     1920
#define IDC_EDIT_content                1921
#define IDC_pc29                        1923
#define IDC_RADIO_procImMsg             1928
#define IDC_RADIO_procImHisTask         1929
#define IDC_STATIC_status               1968
#define IDC_STATIC_pic0                 1974
#define IDC_STATIC_pic2                 1976
#define IDC_STATIC_pic3                 1977
#define IDC_STATIC_pic4                 1978
#define IDC_STATIC_pic5                 1979
#define IDC_STATIC_pic6                 1980
#define IDC_STATIC_pic7                 1981
#define IDC_STATIC_pic8                 1982
#define IDC_STATIC_pic9                 1983
#define IDC_STATIC_pic10                1984
#define IDC_STATIC_avCompressorVal_req  1985
#define IDC_STATIC_pic11                1985
#define IDC_STATIC_webcamCompressorVal  1986
#define IDC_STATIC_meDesc               1986
#define IDC_STATIC_pic12                1986
#define IDC_STATIC_iWidth               1987
#define IDC_STATIC_pic13                1987
#define IDC_STATIC_avCompressorVal_req2 1987
#define IDC_STATIC_avCompressorVal_req_3d 1987
#define IDC_EDIT_iWidth                 1988
#define IDC_STATIC_pic14                1988
#define IDC_STATIC_iHeight              1989
#define IDC_STATIC_pic15                1989
#define IDC_EDIT_iHeight                1990
#define IDC_STATIC_conference_row       1991
#define IDC_EDIT_conference_row         1992
#define IDC_STATIC_conference_col       1993
#define IDC_EDIT_conference_col         1994
#define IDC_STATIC_ucSeconds_perFrame   1995
#define IDC_EDIT_ucSeconds_perFrame     1997
#define IDC_STATIC_uiBytesRecorded_perBlockAlign 1999
#define IDC_STATIC_usTimeoutInMsToSwitch 2006
#define IDC_EDIT_usTimeoutInMsToSwitch  2007
#define IDC_EDIT_usTimeoutInMsToSwitch_rt 2008
#define IDC_STATIC_usTimeoutInMsToSwitch_rt 2009
#define IDC_EDIT_usMaxFPS_toShareBmp    2013
#define IDC_talkerList                  2013
#define IDC_STATIC_usMaxFPS_toShareBmp  2015
#define IDC_CHECK_ucbManullyPermitToSpeakOnVideoConference 2017
#define IDC_STATIC_usCntLimit_activeMems_from 2018
#define IDC_EDIT_usCntLimit_activeMems_from 2019
#define IDC_STATIC_iTimeoutInMs_channelIdle 2020
#define IDC_EDIT_iTimeoutInMs_channelIdle 2021
#define IDC_COMBO_videoCompressors      2026
#define IDC_COMBO_audioCompressors      2028
#define IDC_STATIC_screenCompressorVal  2029
#define IDC_COMBO_videoOutputType       2030
#define IDC_COMBO_videoCompressor       2031
#define IDC_STATIC_videoOutputType      2032
#define IDC_COMBO_audioCompressor       2033
#define IDC_COMBO_audioOutputType       2034
#define IDC_BUTTON_cfgWmv               2035
#define IDC_STATIC_audioOutputType      2036
#define IDC_STATIC_VBRQUALITY           2037
#define IDC_STATIC_QUALITY              2038
#define IDC_STATIC_COMPLEXITY           2039
#define IDC_STATIC_PROFILES             2040
#define IDC_STATIC_FRAMERATE            2041
#define IDC_STATIC_BITRATE              2042
#define IDC_STATIC_BUFFERDELAY          2043
#define IDC_STATIC_MAXKEYDISTANCE       2044
#define IDC_STATIC_encodingMode         2045
#define IDC_COMBO_mediaFile             2050
#define IDC_STATIC_mediaFileCompressorVal 2052
#define IDC_BUTTON_mediaFileCompressor  2053
#define IDC_STATIC_video                2054
#define IDC_STATIC_audio                2055
#define IDC_STATIC_defaultFmtVal        2057
#define IDC_STATIC_defaultFmt           2058
#define IDC_COMBO_uiBytesRecorded_perBlockAlign 2059
#define IDC_STATIC_uiMaxTimeInMsToPlay  2060
#define IDC_EDIT_uiMaxTimeInMsToPlay    2061
#define IDC_STATIC_uiMaxTimeInMsToBeRemoved 2062
#define IDC_EDIT_uiMaxTimeInMsToBeRemoved 2063
#define IDC_BUTTON_restoreDefaultSettings 2064
#define IDC_STATIC_uiMinTimeInMsOfAudioDataPlaying 2065
#define IDC_EDIT_uiMinTimeInMsOfAudioDataPlaying 2066
#define IDC_STATIC_uiAudioDataAddedToPlayEveryTime 2067
#define IDC_STATIC_uiNotifyIntervalInMs_needMoreAudioData 2068
#define IDC_CHECK_select                2093
#define IDC_CHECK_rectangle             2094
#define IDC_CHECK_point                 2095
#define IDC_CHECK_segment               2096
#define IDC_STATIC_usMinFps_toShareBmp  2097
#define IDC_CHECK_circle                2097
#define IDC_EDIT_usMinFps_toShareBmp    2098
#define IDC_STATIC_hint1                2101
#define IDC_STATIC_messengerName        2102
#define IDC_EDIT_passwd0                2103
#define IDC_EDIT_passwd1                2104
#define IDC_BUTTON_set240pSettings      2105
#define IDC_STATIC_audioPlayCfg         2109
#define IDC_STATIC_pic1                 2110
#define IDC_STATIC_autoAnswer_av        2124
#define IDC_COMBO_autoAnswer_av         2125
#define IDC_STATIC_autoAnswer_screen    2126
#define IDC_COMBO_autoAnswer_screen     2127
#define IDC_STATIC_autoAnswer_mediaFile 2128
#define IDC_COMBO_autoAnswer_mediaFile  2129
#define IDC_COMBO_req                   2130
#define IDC_COMBO_usLayoutType          2132
#define IDC_LIST_deamonStatus           2134
#define IDC_CHECK_showVideoHint         2145
#define IDC_STATIC_240pSettings         2149
#define IDC_STATIC_appName              2157
#define IDC_CHECK_shareWebcamInConference 2158
#define IDC_STATIC_conferenceId_shareWebcam 2159
#define IDC_EDIT_conferenceId_shareWebcam 2160
#define IDC_CHECK_noLocalVideoInThisConference 2161
#define IDC_STATIC_group                2162
#define IDC_BUTTON_shareMediaFile       2162
#define IDC_STATIC_hint_imObjRule       2163
#define IDC_BUTTON_set480pSettings      2164
#define IDC_STATIC_480pSettings         2165
#define IDC_STATIC_aDev                 2170
#define IDC_COMBO_aDev                  2171
#define IDC_STATIC_vDev                 2172
#define IDC_COMBO_vDev                  2173
#define IDC_BUTTON_cfgCaptureFilter_v   2174
#define IDC_BUTTON_cfgCapturePin_v      2175
#define IDC_BUTTON_cfgCrossBar_v        2176
#define IDC_BUTTON_mediaDeviceCompressor 2178
#define IDC_STATIC_mediaDeviceCompressorVal 2179
#define IDC_BUTTON_set1080pSettings     2182
#define IDC_STATIC_1080pSettings        2183
#define IDC_STATIC_uiMinTimeInMsToPlay  2184
#define IDC_EDIT_uiMinTimeInMsToPlay    2185
#define IDC_BUTTON_set720pSettings      2186
#define IDC_STATIC_720pSettings         2187
#define IDC_STATIC_videoEffect          2188
#define IDC_COMBO_videoEffect           2189
#define IDC_BUTTON_more                 2201
#define IDC_BUTTON_set576pSettings      2205
#define IDC_STATIC_576pSettings         2207
#define IDC_STATIC_usMax_nPlayers       2212
#define IDC_STATIC_usMax_nThreads_dec   2213
#define IDC_STATIC_uiMaxQNodes_vwRuleQ  2214
#define IDC_EDIT_usMax_nPlayers         2215
#define IDC_EDIT_usMax_nThreads_dec     2216
#define IDC_EDIT_uiMaxQNodes_vwRuleQ    2217
#define IDC_BUTTON_testLocalAv          2218
#define IDC_CHECK_ucbUseGlobalVWall     2219
#define IDC_BUTTON_nonexclusive         2221
#define IDC_LIST_msg                    2223
#define IDC_BUTTON_export               2224
#define IDC_BUTTON_clear                2225
#define IDC_BUTTON_about                2226
#define IDC_CHECK_showMsgBox            2227
#define IDC_CHECK_showNotification      2228
#define IDC_STATIC_req                  2229
#define IDC_BUTTON_rule                 2231
#define IDC_BUTTON_fullScreen           2232
#define IDC_BUTTON_av                   2233
#define IDC_BUTTON_shareScreen          2234
#define IDC_BUTTON_close                2235
#define IDC_BUTTON_localVideo           2236
#define IDC_BUTTON_av_accept            2237
#define IDC_BUTTON_av_deny              2238
#define IDC_BUTTON_msgBox               2239
#define IDC_BUTTON_menu                 2250
#define IDC_BUTTON_makeBigger           2251
#define IDC_CHECK_ucbScrollForEnlagedImg 2252
#define IDC_BUTTON_showDlgMenu          2253
#define IDC_BUTTON_FOCUS_OUT            2260
#define IDC_BUTTON_closeAndClean        2261
#define IDC_CHECK_ucbPreferCuda         2262
#define IDC_BUTTON_ptzSettings          2265
#define IDC_BUTTON_setDev10fpsSettings  2266
#define IDC_SLIDER_speed                2267
#define IDC_STATIC_speed                2268
#define IDC_BUTTON_IRIS_OUT             2269
#define IDC_BUTTON_FOCUS_IN             2270
#define IDC_BUTTON_IRIS_IN              2271
#define IDC_BUTTON_ZOOM_OUT             2272
#define IDC_BUTTON_ZOOM_IN              2273
#define IDC_BUTTON_RAIN_BRUSH           2274
#define IDC_BUTTON_SEARCH_LIGHT         2275
#define IDC_STATIC_preset               2276
#define IDC_STATIC_focus                2277
#define IDC_STATIC_iris                 2278
#define IDC_STATIC_zoom                 2279
#define IDC_BUTTON_UP                   2280
#define IDC_BUTTON_DOWN                 2281
#define IDC_BUTTON_LEFT                 2282
#define IDC_BUTTON_RIGHT                2283
#define IDC_BUTTON_TOP_LEFT             2284
#define IDC_BUTTON_TOP_RIGHT            2285
#define IDC_BUTTON_BOTTOM_LEFT          2286
#define IDC_BUTTON_BOTTOM_RIGHT         2287
#define IDC_BUTTON_AUTO_SCAN            2288
#define IDC_EDIT_remotePtzUsers         2291
#define IDC_STATIC_remotePtz            2292
#define IDC_STATIC_remoter              2293
#define IDC_STATIC_comPtz               2294
#define IDC_STATIC_comName              2295
#define IDC_STATIC_comBaud              2296
#define IDC_STATIC_comParity            2297
#define IDC_STATIC_comData              2298
#define IDC_STATIC_comStopBit           2299
#define IDC_STATIC_ptzProtocal          2300
#define IDC_STATIC_ptzAddr              2301
#define IDC_EDIT_PRE                    2302
#define IDC_BUTTON_PRE_GO               2303
#define IDC_BUTTON_PRE_SET              2304
#define IDC_BUTTON_PRE_CLEAR            2305
#define IDC_STATIC_memoAppending        2306
#define IDC_EDIT_memoAppending          2308
#define IDC_STATIC_ptz                  2309
#define IDC_BUTTON_ptzPanel             2322
#define IDC_BUTTON_remoteVideo          2323
#define IDC_BUTTON_testAv               2324
#define IDC_STATIC_otherDesc            2326
#define IDC_BUTTON_videoConferenceCfg   2327
#define IDC_STATIC_staticMaskColor      2337
#define IDC_EDIT_maskColor_r            2338
#define IDC_EDIT_maskColor_g            2339
#define IDC_EDIT_maskColor_b            2340
#define IDC_BUTTON_selectFont           2341
#define IDC_STATIC_subtitle0            2342
#define IDC_EDIT_subtitle0              2343
#define IDC_EDIT_subtitle1              2344
#define IDC_STATIC_subtitle1            2345
#define IDC_EDIT_subtitle2              2346
#define IDC_STATIC_subtitle2            2347
#define IDC_STATIC_xyStart              2348
#define IDC_EDIT_subtitle3              2348
#define IDC_EDIT_xStart                 2349
#define IDC_STATIC_subtitle3            2349
#define IDC_EDIT_subtitle4              2350
#define IDC_EDIT_yStart                 2351
#define IDC_STATIC_subtitle4            2351
#define IDC_BUTTON_emptyTxt             2352
#define IDC_BUTTON_useDefault           2353
#define IDC_CHECK_displayTime           2354
#define IDC_EDIT_subtitle5              2354
#define IDC_BUTTON_file                 2355
#define IDC_STATIC_subtitle5            2366
#define IDC_EDIT_subtitle6              2369
#define IDC_STATIC_subtitle6            2370
#define IDC_EDIT_subtitle7              2373
#define IDC_STATIC_subtitle7            2374
#define IDC_EDIT_subtitle8              2377
#define IDC_STATIC_subtitle8            2378
#define IDC_EDIT_subtitle9              2381
#define IDC_STATIC_subtitle9            2382
#define IDC_EDIT_subtitle10             2385
#define IDC_STATIC_subtitle10           2386
#define IDC_EDIT_subtitle11             2389
#define IDC_STATIC_subtitle11           2390
#define IDC_BUTTON_subtitlesSettings    2392
#define IDC_BUTTON_aDev                 2393
#define IDC_BUTTON_fontColor            2394
#define IDC_BUTTON_vDev                 2399
#define IDC_BUTTON_subtitles            2400
#define IDC_STATIC_subtitles            2401
#define IDC_BUTTON_noop                 2402
#define IDC_BUTTON_conferenceQuality    2403
#define IDC_STATIC_testAvHint           2404
#define IDC_CHECK_bUseAec               2409
#define IDD_offlineRes                  2410
#define IDC_BUTTON_layoutType           3000
#define IDD_chromaKeyCfg                3001
#define IDC_BUTTON_layoutType2          3001
#define IDC_BUTTON_selOneBig            3001
#define IDD_menu_d3dWall                3002
#define IDD_msgTool                     3003
#define IDC_LIST_chromaKey              3004
#define IDD_instantAssistant_msg        3004
#define IDC_STATIC_rgb                  3005
#define IDC_EDIT_key_r                  3006
#define IDC_EDIT_key_g                  3007
#define IDD_select_remoteVideo          3007
#define IDC_EDIT_key_b                  3008
#define IDC_STATIC_hsl                  3009
#define IDC_STATIC_key_l                3010
#define IDC_STATIC_key_h                3011
#define IDC_STATIC_key_s                3012
#define IDC_EDIT_key_tola               3013
#define IDC_STATIC_key_tola             3014
#define IDC_EDIT_key_distance           3015
#define IDC_STATIC_key_distance         3016
#define IDC_SPIN_plusInt                3017
#define IDC_STATIC_plusInt              3018
#define IDC_SPIN_plusFloat              3019
#define IDC_STATIC_plusFloat            3020
#define IDC_STATIC_hint_chromaKey       3021
#define IDC_CHECK_useChromaKey          3022
#define IDC_EDIT_edge_distance          3023
#define IDC_CHECK_pick                  3024
#define IDC_BUTTON_save                 3025
#define IDC_STATIC_color                3026
#define IDC_STATIC_minS                 3027
#define IDC_EDIT_minS                   3028
#define IDC_STATIC_minL                 3029
#define IDC_EDIT_minL                   3030
#define IDC_STATIC_maxL                 3031
#define IDC_EDIT_maxL                   3032
#define IDC_CHECK_keyingAFrame          3033
#define IDC_STATIC_desc                 3034
#define IDC_STATIC_color_org            3035
#define IDC_STATIC_color_keyed          3036
#define IDC_BUTTON_setBg                3037
#define IDC_STATIC_edge_distance        3039
#define IDC_STATIC_f_r                  3040
#define IDC_EDIT_f_r                    3041
#define IDC_CHECK_edgeColor             3042
#define IDC_CHECK_smooth                3043
#define IDC_STATIC_minRgb               3044
#define IDC_EDIT_minRgb                 3045
#define IDC_STATIC_xy                   3046
#define IDC_EDIT_x                      3047
#define IDC_EDIT_y                      3048
#define IDC_STATIC_preBlur              3050
#define IDC_SLIDER_preBlur              3051
#define IDC_STATIC_preBlur_val          3052
#define IDC_STATIC_postBlur             3053
#define IDC_SLIDER_postBlur             3054
#define IDC_STATIC_postBlur_val         3055
#define IDC_SLIDER_key_tola             3056
#define IDC_STATIC_key_tola_val         3057
#define IDC_SLIDER_key_tolb             3058
#define IDC_STATIC_key_tolb_val         3059
#define IDC_STATIC_gamma                3060
#define IDC_SLIDER_gamma                3061
#define IDC_STATIC_gamma_val            3062
#define IDD_selectAvCompressor          3068
#define IDC_BUTTON_240p                 3069
#define IDC_BUTTON_480p                 3070
#define IDC_BUTTON_576p                 3071
#define IDC_BUTTON_720p                 3072
#define IDC_BUTTON_1080p                3073
#define IDC_BUTTON_240p_conf            3074
#define IDC_BUTTON_video4k              3074
#define IDC_BUTTON_480p_conf            3075
#define IDC_BUTTON_576p_conf            3076
#define IDC_BUTTON_720p_conf            3077
#define IDC_STATIC_prefer               3078
#define IDC_STATIC_cur                  3079
#define IDC_STATIC_avCompressor         3080
#define IDC_BUTTON_cfg                  3081
#define IDC_CHECK_noPrompt              3082
#define IDC_BUTTON_selAvCompressor      3083
#define IDC_BUTTON_1080p_conf           3083
#define IDC_BUTTON_updateDynBmpList     3084
#define IDC_STATIC_prefer_conf          3084
#define IDC_CHECK_ucbSetDevResolution   3085
#define IDC_STATIC_iDevWidth            3086
#define IDC_EDIT_iDevWidth              3087
#define IDC_STATIC_iDevHeight           3088
#define IDC_EDIT_iDevHeight             3089
#define IDC_CHECK_ucbSaveMsg            3090
#define IDC_STATIC_dirToSaveMsg         3091
#define IDC_EDIT_dirToSaveMsg           3092
#define IDC_BUTTON_browseMsgDir         3093
#define IDC_STATIC_category             3094
#define IDC_COMBO_category              3095
#define IDC_STATIC_audioBitrate         3102
#define IDC_EDIT_audioBitrate           3103
#define IDC_CHECK_ucbOrgAudioFmt        3104
#define IDC_STATIC_channel              3105
#define IDC_EDIT_channel                3106
#define IDC_STATIC_sample               3107
#define IDC_EDIT_sample                 3108
#define IDC_STATIC_bit                  3109
#define IDC_EDIT_bit                    3110
#define IDD_remoteStorageSettings       3111
#define IDC_STATIC_remoteVideo_obj      3112
#define IDC_STATIC_remoteVideo_type     3113
#define IDD_menu_shareDynBmps           3113
#define IDC_COMBO_remoteVideo_type      3114
#define IDD_ptzControl_remote           3114
#define IDC_STATIC_remoteVideo_index    3115
#define IDD_ptzControl_local            3115
#define IDC_EDIT_remoteVideo_index      3116
#define IDD_msgInput                    3116
#define IDD_testSpeed                   3118
#define IDD_menu_generalWall            3119
#define IDC_EDIT_remoteStorageUsers     3120
#define IDC_STATIC_remoteStorageUsers   3121
#define IDC_CHECK_ucbSaveVideo          3122
#define IDD_cfgGrp                      3122
#define IDC_STATIC_dirToSaveVideo       3123
#define IDD_editConsultMem              3123
#define IDC_EDIT_dirToSaveVideo         3124
#define IDD_instantAssistant_start_more 3124
#define IDC_BUTTON_browseVideoDir       3125
#define IDD_instantAssistant_start_grp_more 3125
#define IDD_instantAssistant_av_more    3126
#define IDC_STATIC_timeOfVideoFile      3127
#define IDD_instantAssistant_av_grp_more 3127
#define IDC_EDIT_timeOfVideoFile        3128
#define IDD_cfgBgWall                   3128
#define IDC_STATIC_selectRemoteVideoHint 3129
#define IDD_avRes                       3129
#define IDC_STATIC_remoteStorageSettingsHint 3130
#define IDD_avRes_mgr_hzj               3130
#define IDC_CHECK_xpCantSpeak           3131
#define IDD_avRes_mem_hzj               3131
#define IDC_STATIC_audioSettings        3132
#define IDC_CHECK_bFeatrModeOn          3133
#define IDC_CHECK_bNoiseSup             3134
#define IDC_CHECK_bAGC                  3135
#define IDC_CHECK_bCntrClip             3136
#define IDC_STATIC_bgWall_conf          3137
#define IDC_CHECK_useBgWall             3138
#define IDC_STATIC_rows                 3139
#define IDC_EDIT_rows                   3140
#define IDC_STATIC_cols                 3141
#define IDC_EDIT_cols                   3142
#define IDC_STATIC_pollingInterval      3143
#define IDC_EDIT_pollingInterval        3144
#define IDC_CHECK_ucbRunAsAdvertisingPlayer 3148
#define IDC_STATIC_msgTool              3149
#define IDC_STATIC_no                   3153
#define IDC_STATIC_rtspUrl              3154
#define IDC_EDIT_rtspUrl                3155
#define IDC_COMBO_hardwareAccl          3156
#define IDC_STATIC_hardwareAccl         3157
#define IDC_BUTTON_micOff               3158
#define IDC_CHECK_outlineFont           3159
#define IDC_CHECK_filled                3160
#define IDC_BUTTON_edgeColor            3161
#define IDC_STATIC_edgeWidth            3162
#define IDC_EDIT_edgeWidth              3163
#define IDC_CHECK_horizontalCenter      3164
#define IDC_BUTTON_unresizableCompressor 3166
#define IDC_STATIC_unresizableCompressorVal 3167
#define IDC_BUTTON_menuBar              3168
#define IDC_BUTTON_sendFile             3169
#define IDC_BUTTON_offlineRes           3173
#define IDC_STATIC_offlineRes           3174
#define IDC_LIST_offlineRes             3175
#define IDC_BUTTON_download             3176
#define IDC_BUTTON_upload               3177
#define IDC_BUTTON_refresh              3178
#define IDC_BUTTON_delete               3179
#define IDC_BUTTON_showAllDownloads     3182
#define IDC_BUTTON_nextPage             3183
#define IDC_BUTTON_prevPage             3184
#define IDC_STATIC_pageNum              3185
#define IDC_STATIC_filterKeywords       3186
#define IDC_EDIT_filterKeywords         3187
#define IDC_BUTTON_page1                3188
#define IDC_EDIT_pageNo                 3189
#define IDC_BUTTON_go                   3190
#define IDC_COMBO_dev                   3191
#define IDC_COMBO_ptzType               3192
#define IDC_CHECK_ucbUnresizable        3193
#define IDC_BUTTON_openQvw              3196
#define IDC_BUTTON_closeQvw             3200
#define IDC_BUTTON_playRemoteAudio      3201
#define IDC_EDIT_input                  3202
#define IDC_BUTTON_joinInBgWall         3203
#define IDC_BUTTON_selectAvCompressor   3204
#define IDC_STATIC_avgBitrate           3205
#define IDC_COMBO_avgBitrate            3206
#define IDC_BUTTON_viewOfflineRes       3212
#define IDC_BUTTON_test                 3214
#define IDC_CHECK_ucbManuallyConfCtrl   3216
#define IDC_STATIC_filter               3218
#define IDC_EDIT_filter                 3219
#define IDC_STATIC_confStatus           3221
#define IDC_BUTTON_permitToSpeak        3222
#define IDC_BUTTON_noSpeaking           3223
#define IDC_CHECK1                      3224
#define IDC_CHECK_letConfMgrSetMicOn    3224
#define IDC_CHECK_2Streams              3224
#define IDC_CHECK_ucb2Streams           3224
#define IDC_CHECK_audio                 3224
#define IDC_LIST_usr                    3225
#define IDC_LIST_mem                    3226
#define IDC_EDIT_selUsr                 3227
#define IDC_STATIC_grpName              3228
#define IDC_BUTTON_add                  3229
#define IDC_BUTTON_del                  3230
#define IDC_STATIC_mems                 3231
#define IDC_EDIT_grpName                3232
#define IDC_STATIC_staticCreator        3233
#define IDC_STATIC_creator              3234
#define IDC_LIST_peerInfo               3235
#define IDC_STATIC_peerInfo             3236
#define IDC_BUTTON_controlDesktop       3238
#define IDC_STATIC_confType             3239
#define IDC_STATIC_ksName               3240
#define IDC_EDIT_ksName                 3241
#define IDC_STATIC_memInfo              3242
#define IDC_STATIC_ysName               3243
#define IDC_EDIT_ysName                 3244
#define IDC_BUTTON_memList              3246
#define IDC_BUTTON_stat                 3247
#define IDC_BUTTON_2ndScreen            3248
#define IDC_BUTTON_ipc                  3249
#define IDC_EDIT_bgWallFile             3250
#define IDC_BUTTON_bgWallFile           3252
#define IDC_CHECK_joinInBgWall          3254
#define IDC_CHECK_addBgWallToConf       3256
#define IDC_RADIO_autoLayout            3258
#define IDC_RADIO_useBgWallFile         3259
#define IDC_avResTree                   3260
#define IDC_COMBO_grp                   3261
#define IDC_BUTTON_layout               3262
#define IDC_COMBO_layout                3263
#define IDC_BUTTON_cfgConf              3265
#define IDC_BUTTON_call                 3266
#define IDC_STATIC60                    3267
#define IDC_STATIC61                    3268
#define IDC_STATIC_initiator            3268
#define IDC_STATIC62                    3269
#define IDC_STATIC_videoCodec           3269
#define IDC_STATIC63                    3270
#define IDC_COMBO_videoCodec            3270
#define IDC_STATIC64                    3271
#define IDC_STATIC_usMaxSpeakers        3271
#define IDC_STATIC65                    3272
#define IDC_EDIT_usMaxSpeakers          3272
#define IDC_STATIC66                    3273
#define IDC_CHECK2                      3273
#define IDC_CHECK_video                 3273
#define IDC_CHECK_ucb100k               3273
#define IDC_STATIC67                    3274
#define IDC_CHECK_lLayout               3274
#define IDC_STATIC68                    3275
#define IDC_VIDEORIGHT                  3275
#define IDC_COMBO_fps                   3275
#define IDC_STATIC69                    3276
#define IDC_VIDEOLEFT                   3276
#define IDC_STATIC_fps                  3276
#define IDC_STATIC70                    3277
#define IDC_VIDEOTOP                    3277
#define IDC_STATIC71                    3278
#define IDC_VIDEOBOTTOM                 3278
#define IDC_EDIT_bitrate                3278
#define IDC_STATIC72                    3279
#define IDC_STATIC_bitrate_ul           3279
#define IDC_EDIT_bitrate_ul             3280
#define IDC_COORDINATE                  3281
#define IDC_CHECK3                      3281
#define IDC_CHECK_bLyra                 3281
#define IDC_STATIC73                    3282
#define IDC_                            3282
#define IDC_CANCELAMP                   3282
#define IDC_BUTTON_144p                 3282
#define IDC_STATIC74                    3283
#define IDC_STATIC75                    3284
#define IDC_STATIC76                    3285
#define IDC_STATIC77                    3286
#define IDC_STATIC78                    3287
#define IDC_STATIC79                    3288
#define IDC_STATIC80                    3290
#define IDC_STATIC81                    3291
#define IDC_STATIC82                    3292
#define IDC_STATIC83                    3293
#define IDC_STATIC84                    3294
#define IDC_STATIC85                    3295
#define IDC_STATIC86                    3296
#define IDC_STATIC87                    3297
#define IDC_STATIC88                    3298
#define IDC_STATIC89                    3299
#define IDC_STATIC90                    3300
#define IDC_STATIC91                    3301
#define IDC_STATIC92                    3302
#define IDC_STATIC93                    3303
#define IDC_STATIC94                    3304
#define IDC_STATIC95                    3305
#define IDC_STATIC96                    3306
#define IDC_STATIC97                    3307
#define IDC_STATIC98                    3308
#define IDC_STATIC99                    3309
#define IDC_STATIC100                   3311
#define ID_POPUP32772                   32772
#define ID_SYS_START                    32774
#define ID_SYS_STOP                     32775
#define ID_LOG_DISPLAY                  32776
#define ID_LOG_DISPLAY_OFF              32777
#define ID_qyPcList                     32837
#define ID_qyStat                       32839
#define ID_qyRas                        32840
#define ID_qyIntraConn                  32842
#define ID_qyDevChanged                 32844
#define ID_qyMgrPcGrp                   32845
#define ID_qyDel                        32850
#define ID_qyProperties                 32851
#define ID_qyStopMon                    32852
#define ID_qyStartMon                   32856
#define ID_qyStartIpScan                32878
#define ID_qyStopIpScan                 32879
#define ID_qyStopRegScan                32881
#define ID_qyStartRegScan               32884
#define ID_qyCfgIpScan                  32885
#define ID_qyScannedIpList              32887
#define ID_qyImport                     32889
#define ID_qyExport                     32890
#define ID_qyCfgPcRule                  32893
#define ID_qyCfgUnchk                   32895
#define ID_qySendMsg                    32899
#define ID_qyQwmDel                     32900
#define ID_qyOnInternet                 32901
#define ID_qyDelPcUsr                   32903
#define ID_qyDelPcRule                  32904
#define ID_qyEdit                       32905
#define ID_qyDelProxy                   32908
#define ID_qyCfgProxyRule               32910
#define ID_qyWillAttack                 32914
#define ID_qyStopUnchk                  32916
#define ID_qyStopWillAttack             32917
#define ID_qyRefreshVlanPolicy          32920
#define ID_qyEditPcUsrInTab1            32922
#define ID_qyDelPcUsrInTab1             32923
#define ID_CFGUSR                       32924
#define ID_CFGWARN                      32925
#define ID_qyProxyServer                32927
#define ID_qyStartUpdate                32930
#define ID_qyStopUpdate                 32931
#define ID_qyNetworkView                32932
#define ID_qyConnectionView             32934
#define ID_qyProperties_network         32935
#define ID_qyProperties_switch          32936
#define ID_qyProperties_switchPort      32937
#define ID_qyEdit_switchInfo            32938
#define ID_qyCfgSwitchPolicyGrps        32940
#define ID_qyMgrSwitchPolicyGrps        32941
#define ID_qyDel_switch                 32942
#define ID_qyNetworkSpeedView           32944
#define ID_qyStopIntraMon               32945
#define ID_qyStartIntraMon              32946
#define ID_cfgBhbSysOptions             32949
#define ID_cfgBhbScannedNetSegs         32950
#define ID_qyStopSecChk                 32953
#define ID_qyStartSecChk                32954
#define ID_doSecChk                     32956
#define ID_qyNetDevEventAll             32957
#define ID_cfgAdvancedOptions           32958
#define ID_qyEdit_portUsrInfo           32961
#define ID_qyCancel_portUsrInfo         32962
#define ID_qyStopSnmpScan               32963
#define ID_qyStartSnmpScan              32964
#define ID_qyEdit_switchAndAllConns     32965
#define ID_qyCancel_switchAndAllConns   32967
#define ID_qyCancel_allConns            32968
#define ID_qyDel_connection             32971
#define ID_qySearch_mac                 32976
#define ID_qySearch_netDevEvent         32977
#define ID_qySearch_pcList              32978
#define ID_qySearch_pcEvent             32979
#define ID_qySearch_ip                  32980
#define ID_qyProperties_viewNetDevConn  32981
#define ID_qySearch_unusedConn          32983
#define ID_qyStopMacScan                32984
#define ID_qyStartMacScan               32985
#define ID_qySearchSwitchPort           32987
#define ID_qyStopWatchIp                32990
#define ID_qyStartWatchIp               32991
#define ID_qySearchConnection           32993
#define ID_qyPcSpList                   32994
#define ID_qySearch_pcSpList            32995
#define ID_qyDelPcSp                    32996
#define ID_qyCusPcSp                    32997
#define ID_qySearchPcSp                 32999
#define ID_cfgInterMonIp                33000
#define ID_qyStartPermitNat             33004
#define ID_qyStopPermitNat              33005
#define ID_beStaticAccessModeAndEnablePortSecurity 33006
#define ID_disablePortSecurity          33007
#define ID_setCpsIfMaxSecureMacAddr     33008
#define ID_secureMac                    33009
#define ID_cancelSecureMac              33010
#define ID_qyAssetsView                 33012
#define ID_qyCfgSp                      33013
#define ID_addServicePack               33015
#define ID_qyReportAssetsInfo_byMac     33019
#define ID_qyReportAssetsInfo_byOs      33020
#define ID_qyReportAssetsInfo_en_byMac  33021
#define ID_qyReportAssetsInfo_en_byOs   33022
#define ID_addSp                        33023
#define ID_delServicePack               33025
#define ID_qyCfgBoard                   33026
#define ID_qyCfgCustom                  33027
#define ID_snmpObjRuleList              33028
#define ID_qyCfgSnmpObjRule             33029
#define ID_qyCfgSnmpObjPortRule         33030
#define ID_qyStopDownPortIfMacChanged   33031
#define ID_qyStartDownPortIfMacChanged  33032
#define ID_qyDelSnmpObjRule             33033
#define ID_conflictConnList             33034
#define ID_qyDelConnLock                33037
#define ID_qyCancelConnLock             33038
#define ID_qyDelSwitchConnLock          33039
#define ID_directConnList               33040
#define ID_undoSecChk                   33041
#define ID_pcNetworkPropList            33043
#define ID_pcNetworkRuleList            33044
#define ID_cfgPcNetworkOptions          33045
#define ID_qyProp_pcNetwork             33046
#define ID_qyEdit_pcNetwork             33047
#define ID_qyDel_pcNetwork              33048
#define ID_cfgSystemParams              33050
#define ID_pcProxyCfgPropList           33051
#define ID_pcProxyCfgRuleList           33052
#define ID_queryNetworkProp             33055
#define ID_queryProxyCfg                33056
#define ID_queryComputerInfo            33058
#define ID_pcEventLogList               33059
#define ID_pcOsUsrList                  33061
#define ID_qyPcNetStatList              33062
#define ID_pcPrinterPropList            33063
#define ID_pcProcessPropList            33064
#define ID_qyProhibitAll                33066
#define ID_qyProhibit                   33067
#define ID_pcProcessRuleList            33068
#define ID_addPcProcessPermitRule       33070
#define ID_viewPcProcessRule            33071
#define ID_qyCfgAutoLogon               33072
#define ID_viewRemoteDesktop            33075
#define ID_cancelRemoteDesktop          33076
#define ID_cfgPcMonOptions              33077
#define ID_monDesktop                   33078
#define ID_cancelMonDesktop             33079
#define ID_pcSecChkEventList            33080
#define ID_stopFileMon                  33082
#define ID_startFileMon                 33083
#define ID_pcProcessModulePropList      33084
#define ID_qyCfgModuleInfo              33085
#define ID_addModuleKnowlege            33086
#define ID_editPcModuleKnowlege         33087
#define ID_stopModuleMon                33088
#define ID_startModuleMon               33089
#define ID_editModuleKnowlege           33090
#define ID_delModuleKnowlege            33091
#define ID_qyProp_pcModuleKnowlege      33092
#define ID_importModuleKnowlege         33093
#define ID_exportModuleKnowlege         33094
#define ID_clearupModuleKnowlege        33095
#define ID_pcWindowsUpdatePolicyPropList 33096
#define ID_pcWindowsUpdatePolicyRuleList 33097
#define ID_queryPcWindowsUpdatePolicyProp 33098
#define ID_qyStopDownPortIfWarnSpeed    33099
#define ID_qyStartDownPortIfWarnSpeed   33100
#define ID_qyPcView                     33101
#define ID_pcRegistryList               33102
#define ID_pcRegistryRuleStatusList     33103
#define ID_qyCfgPcRegistryKnowledge     33104
#define ID_stopPcRegistryMon            33105
#define ID_startPcRegistryMon           33106
#define ID_qyMakeClients                33107
#define ID_qyCfgStandardName            33108
#define ID_qyCfgStandardNames           33109
#define ID_pcNetFlowPropList            33110
#define ID_pcNetFlowPropList_ethernet   33111
#define ID_qyMgrSystems                 33113
#define ID_qyCfgSystems                 33114
#define ID_loadProcedObj                33115
#define ID_unloadProcedObj              33116
#define ID_pcNetSharePropList           33117
#define ID_qyTalk                       33127
#define ID_qyMessengerAuthList_needAudited 33134
#define ID_qyMessengerAuthList          33137
#define ID_qyMessengerView              33138
#define ID_qyTalkToTaskPeer             33149
#define ID_qyNewImGrp                   33156
#define ID_qyImGrpAuthList              33159
#define ID_qyAddTo                      33163
#define ID_qyDiscuss                    33165
#define ID_cfgImAuthCond                33168
#define ID_qyModifyMessengerId          33171
#define ID_wwwQmCfgList                 33192
#define ID_wwwQmCfg                     33193
#define ID_ipKnowledgeList              33197
#define ID_qyPhoneGuestList             33206
#define ID_qyAdd                        33207
#define ID_qySendSm                     33209
#define ID_qyGsmModemList               33214
#define ID_qySmContactList              33215
#define ID_qyCfgDefaultSmContact        33217
#define ID_qyCfgSmContact               33218
#define ID_qyImObjAuthList              33223
#define ID_qyAddPhone                   33226
#define ID_qyDelPhone                   33228
#define ID_qyPhoneMessengerList         33229
#define ID_qyCfgDefaultSmServer         33231
#define ID_qyVerifiedPhoneList          33236
#define ID_qyViewSmContacts             33238
#define ID_qyCfgSkippedMacs             33240
#define ID_qyCopy                       33346
#define ID_qyPaste                      33347
#define ID_MENU                         33396
#define ID_viewDynBmp                   33398
#define ID_sharedDynBmpRuleList         33405
#define ID_cfgVisitor                   33407
#define ID_viewToolbox                  33416
#define ID_stopEditing                  33422
#define ID_stopShowingRules             33426
#define ID_startToEdit                  33428
#define ID_startToShowRules             33429
#define ID_qyCusName                    33435
#define ID_qySetBackground              33436
#define ID_save                         33439
#define ID_open                         33441
#define ID_qyResetBackground            33443
#define ID_qyNewMessenger               33465
#define ID_qyImAmList                   33467
#define ID_MENU_isCmd_min               33470
#define ID_MENU_isCmd_max               36470
#define ID_POPUP                        36472
#define ID_cfgCustomerService           36474
#define ID_POPUP_TONGLIAN               36773
#define ID_tonglian                     36774
#define ID_POPUP_CANCELTONGLIAN         36775
#define ID_cancelTonglian               36776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        3134
#define _APS_NEXT_COMMAND_VALUE         36777
#define _APS_NEXT_CONTROL_VALUE         3283
#define _APS_NEXT_SYMED_VALUE           3003
#endif
#endif
