//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by qyMc_winCe_appppc.rc
//
#define IDS_APP_TITLE                   1
#define IDC_QYMC_WINCE_APP              2
#define IDI_QYMC_WINCE_APP              101
#define IDR_MENU                        102
#define IDS_OK                          103
#define IDS_HELP                        104
#define IDD_ABOUTBOX                    105
#define IDD_ABOUTBOX_WIDE               106
#define IDD_QYMC_WINCE_DIALOG           129
#define IDD_qnmCfgOptions_isClient_ce   130
#define IDD_objs                        131
#define IDD_input                       132
#define IDC_STATIC_1                    201
#define IDC_STATIC_2                    202
#define IDC_STATIC_3                    203
#define IDD_qyRegTool                   204
#define IDD_policy_isClient             326
#define IDD_instantAssistant            354
#define IDD_mcClient_logon              368
#define IDD_talk_ce                     372
#define IDC_STATIC_meDesc               1000
#define IDC_BUTTON_contact              1000
#define IDC_BUTTON_group                1001
#define IDC_BUTTON_status               1002
#define IDC_title                       1004
#define IDC_BUTTON_msg                  1005
#define IDC_BUTTON_task                 1006
#define IDC_hint0                       1006
#define IDC_EDIT_input                  1006
#define IDC_BUTTON_av                   1007
#define IDC_BUTTON_op0                  1008
#define IDC_BUTTON_op1                  1011
#define IDC_LIST_msg                    1012
#define IDC_LIST_task                   1013
#define IDC_LIST0                       1014
#define IDC_EDIT1                       1015
#define IDC_PASSWD                      1016
#define IDC_NAME                        1020
#define IDC_EDIT8                       1022
#define IDC_EDIT9                       1023
#define IDC_EDIT10                      1024
#define IDC_EDIT11                      1025
#define IDC_EDIT12                      1026
#define IDC_hint1                       1027
#define IDC_PROGRESS_reg                1028
#define IDC_EDIT13                      1029
#define IDC_EDIT14                      1030
#define IDC_EDIT15                      1031
#define IDC_EDIT16                      1032
#define IDC_EDIT17                      1033
#define IDC_EDIT18                      1034
#define IDC_EDIT19                      1035
#define IDC_STATIC0                     1040
#define IDC_EDIT0                       1041
#define IDC_COMBO0                      1042
#define IDC_COMBO1                      1052
#define IDC_COMBO2                      1053
#define IDC_COMBO3                      1054
#define IDC_COMBO4                      1055
#define IDC_COMBO5                      1056
#define IDC_COMBO6                      1057
#define IDC_COMBO7                      1058
#define IDC_COMBO8                      1059
#define IDC_COMBO9                      1060
#define IDC_STATIC1                     1070
#define IDC_STATIC2                     1071
#define IDC_STATIC3                     1072
#define IDC_STATIC4                     1073
#define IDC_STATIC5                     1074
#define IDC_STATIC6                     1075
#define IDC_STATIC7                     1076
#define IDC_STATIC8                     1077
#define IDC_STATIC9                     1079
#define IDC_STATIC10                    1080
#define IDC_STATIC11                    1081
#define IDC_STATIC12                    1082
#define IDC_STATIC13                    1083
#define IDC_STATIC14                    1084
#define IDC_STATIC15                    1085
#define IDC_STATIC16                    1086
#define IDC_STATIC17                    1087
#define IDC_STATIC18                    1088
#define IDC_STATIC19                    1089
#define IDC_STATIC20                    1090
#define IDC_STATIC21                    1091
#define IDC_STATIC22                    1092
#define IDC_STATIC23                    1093
#define IDC_STATIC24                    1094
#define IDC_STATIC25                    1095
#define IDC_STATIC26                    1096
#define IDC_STATIC27                    1097
#define IDC_STATIC28                    1100
#define IDC_STATIC29                    1102
#define IDC_EDIT2                       1106
#define IDC_EDIT3                       1108
#define IDC_EDIT4                       1110
#define IDC_EDIT5                       1113
#define IDC_EDIT6                       1116
#define IDC_EDIT7                       1119
#define IDC_cntIp                       1134
#define IDC_cntName                     1135
#define IDC_cntPort                     1136
#define IDC_STATIC_hint                 1186
#define IDC_STATIC_usrName              1426
#define IDC_STATIC_passwd               1427
#define IDC_STATIC_centerAddr           1448
#define IDC_STATIC_logonServer          1450
#define IDC_BUTTON_browseDir            1570
#define IDC_STATIC_licenseHint          1650
#define IDC_STATIC_cntAddr1             1754
#define IDC_STATIC_cntAddr2             1755
#define IDC_EDIT_cntAddr1               1757
#define IDC_EDIT_cntAddr2               1758
#define IDC_BUTTON_screenCompressor     1868
#define IDC_request                     1868
#define IDC_STATIC_peerDesc             1872
#define IDC_BUTTON_avCompressor         1880
#define IDC_STATIC_staticRuleIfMsgArrive 1900
#define IDC_COMBO_ruleIfMsgArrive       1901
#define IDC_STATIC_staticDirToSaveFile  1904
#define IDC_EDIT_dirToSaveFile          1905
#define IDC_CHECK_ucbOnlyNetSm          1972
#define IDC_STATIC_cntAddr0             1973
#define IDC_STATIC_cntName              1974
#define IDC_STATIC_cntPort              1975
#define IDC_CHECK_ucbOnlyPhoneMsgr      1981
#define IDC_STATIC_avCompressorVal      1985
#define IDC_STATIC_ucSeconds_perFrame   1995
#define IDC_STATIC_usFrames_perSecond   1996
#define IDC_EDIT_ucSeconds_perFrame     1997
#define IDC_EDIT_usFrames_perSecond     1998
#define IDC_STATIC_usTimeoutInMsToSwitch 2006
#define IDC_EDIT_usTimeoutInMsToSwitch  2007
#define IDC_EDIT_usTimeoutInMsToSwitch_rt 2008
#define IDC_STATIC_usTimeoutInMsToSwitch_rt 2009
#define IDC_EDIT_baud                   2010
#define IDC_STATIC_baud                 2011
#define IDC_CHECK_ucbPermitOtherSm      2012
#define IDC_EDIT_usMaxFPS_toShareBmp    2013
#define IDC_talkerList                  2013
#define IDC_EDIT_usMaxFPS_capScreen     2014
#define IDC_STATIC_usMaxFPS_toShareBmp  2015
#define IDC_STATIC_usMaxFPS_capScreen   2016
#define IDC_CHECK_ucbManullyPermitToSpeakOnVideoConference 2017
#define IDC_STATIC_iTimeoutInMs_channelIdle 2020
#define IDC_EDIT_iTimeoutInMs_channelIdle 2021
#define IDC_STATIC_screenCompressor     2027
#define IDC_STATIC_screenCompressorVal  2029
#define IDC_STATIC_mediaFileCompressor  2051
#define IDC_STATIC_mediaFileCompressorVal 2052
#define IDC_BUTTON_mediaFileCompressor  2053
#define IDC_STATIC_avCompressor         2056
#define IDC_BUTTON_restoreDefaultSettings 2064
#define IDC_BUTTON_setAdvancedSettings  2069
#define IDC_STATIC_usMaxFps_mediaFile   2095
#define IDC_EDIT_usMaxFps_mediaFile     2096
#define IDC_STATIC_usMinFps_mediaFile   2097
#define IDC_EDIT_usMinFps_mediaFile     2098
#define IDC_BUTTON_setSlowSettings      2105
#define IDC_BUTTON_option               2106
#define IDC_COMBO_logonServer           2108
#define IDM_OK                          40000
#define IDM_HELP                        40001
#define IDM_HELP_ABOUT                  40002
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
