//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by qyMc.rc
//
#define IDD_ABOUTBOX                    100
#define IDC_QYWBC                       103
#define IDP_SOCKETS_INIT_FAILED         104
#define ID_HKF1                         106
#define ID_HKF2                         107
#define ID_HKF3                         108
#define IDR_MAINFRAME_old1              109
#define ForMgrBar_IDR_MAINFRAME         109
#define ForMgrBar_IDR_DOCTYPE_QYMC      110
#define ForMgrBar_IDR_MC_CFG            111
#define ID_HKF5                         112
#define ID_HKF6                         113
#define ID_HKF7                         114
#define ID_HKF8                         115
#define IDB_SPLASH                      116
#define IDC_line                        117
#define IDC_LIST_secChk                 118
#define IDC_COMBO_secChk                119
#define ID_INDICATOR_licenseInfo        120
#define IDC_num_hint                    124
#define IDC_mac_hint                    125
#define BAK_IDR_MAINFRAME               126
#define ID_VIEW_ARRANGE                 127
#define IDR_MAINFRAME                   128
#define IDR_QYMCTYPE                    129
#define IDR_DOCTYPE_QYMC                129
#define IDB_qnmIcons                    130
#define IDD_DLG_INFOR                   130
#define IDD_DLG_INFORMATION             131
#define IDD_QY_FORM                     133
#define IDD_DLG_IPSETUP                 133
#define IDI_BTN_LOG                     134
#define IDB_MY_TOOLBAR                  135
#define IDD_MC_BAR                      136
#define IDI_BTN1                        137
#define IDD_msgList                     138
#define IDI_ICON1                       141
#define IDI_ICON2                       142
#define IDD_qnmCfgUnchkedIpGrp          142
#define IDR_QYMCPOPUP                   143
#define IDB_LARGEICONS                  144
#define IDB_SMALLICONS                  145
#define IDR_QY_DEVELOP_BAK              146
#define BAK_IDR_QY_DEVELOP              146
#define IDR_MC_DLGBAR                   149
#define IDD_DIALOG1                     152
#define IDD_MC_LOGON                    152
#define IDD_MC_INITBAR                  153
#define IDD_MC_CFGBARINFO               153
#define IDD_MC_INITPOLICE               154
#define IDD_MC_CFGPOLICEINFO            154
#define BAK_IDR_DOCTYPE_QYMC            157
#define IDD_MC_CFGURLLIST               158
#define IDR_MC_CFG                      160
#define IDD_MC_CFGSJ_FORBAR             162
#define IDD_MC_GUESTREGISTER            163
#define IDD_MC_GUESTUNREGISTER          164
#define IDD_MC_CFGSYSTEM_FORBAR         165
#define IDD_MC_CFGTERMS                 166
#define IDD_MC_CFGTERM                  167
#define IDD_MC_HINT                     168
#define IDD_MC_GETMULTIPCIDS            169
#define IDD_MC_CFGBARS                  170
#define IDD_MC_CFGSYSTEM_FORPOLICE      171
#define IDD_MC_CFGKEYTYPES              172
#define IDD_MC_CFGKEYTYPE               173
#define IDD_qnmPcProperties             175
#define IDD_qnmCfgPcGrps                176
#define IDD_qnmCfgPcGrp                 177
#define IDD_shhgPcProperties            178
#define IDD_qnmCfgQyRegToolDir          181
#define IDD_qnmCfgOptions               182
#define IDD_qnmCfgRasOptions            183
#define IDD_phoneNum                    185
#define IDD_qnmCfgRasRule               186
#define IDB_refresh                     193
#define IDB_find                        194
#define IDB_stat                        196
#define IDD_qnmSearch                   197
#define IDD_qnmPcListSearch             198
#define IDD_qnmEventSearch              199
#define IDR_MC_MGR                      200
#define IDR_jsjgl                       201
#define IDR_yhlx                        202
#define IDD_qyRegTool                   204
#define IDD_qnmCfgIpScan                206
#define IDD_qnmCfgIpGrp                 207
#define IDD_qnmStatGeneral              209
#define IDD_qnmStatOthers               210
#define IDD_testP                       211
#define IDD_qnmStatIpScan               212
#define IDD_qnmStatUsrInfo              213
#define IDD_qnmStatPcInfo               214
#define IDD_qyExport                    215
#define IDD_qnmClearup                  216
#define IDD_clearupEventCond            217
#define IDD_scanningIpStatus            219
#define IDD_qwmCommStatus               220
#define IDD_ip                          221
#define IDD_qnmCfgPcRule                222
#define IDD_qnmCfgUnchk                 224
#define IDD_qnmChkingStatus             226
#define IDD_qnmSendHint                 227
#define IDD_qnmCfgProxy                 228
#define IDD_passwdForStopMon            229
#define IDD_qnmEditPcUsrInfo            230
#define IDD_qnmCfgProxyRule             232
#define BAK_IDR_QYMCPOPUP               233
#define IDD_CFGUSR                      235
#define IDD_CFGUSRS                     236
#define IDD_CFGWARN                     238
#define IDD_editSwitchInfo              242
#define IDD_cfgSwitchPolicyGrps         246
#define IDD_cfgSwitchPolicyGrp          247
#define IDD_mgrSwitchPolicyGrps         249
#define IDD_addSwitchToGrp              250
#define IDR_TOOLBAR_bhb                 251
#define IDD_qnmCfgAdvancedOptions       253
#define IDD_qnmEditMacInfo              254
#define IDD_qnmOthersSearch             255
#define IDD_qnmSnmpObjProperties        256
#define IDD_qnmOtherMacInfo             257
#define IDD_num                         258
#define IDD_mac                         259
#define IDD_qnmPcSpListSearch           260
#define IDD_cusPcSp                     261
#define IDD_cfgInterMonIp               262
#define IDD_qnmSnmpObjPortProperties    266
#define IDD_pcAssetProperties           267
#define IDD_qnmPcAssetListSearch        268
#define IDD_cfgCustom                   273
#define IDD_qnmCfgSnmpObjRule           274
#define IDD_qnmCfgPcNetworkOptions      276
#define IDD_prop_pcNetwork              277
#define IDD_qnmCfgPcNetworkRule         278
#define IDD_cfgSystemParams             279
#define IDD_prop_pcProxyCfg             280
#define IDD_qnmCfgPcProxyCfg            281
#define IDD_cfgSwitchDefaultPolicyGrp   284
#define IDD_cfgPcProcessRule            285
#define IDI_DIR                         286
#define IDD_qnmCfgPcMonOptions          289
#define IDD_cfgFileMonFilter            291
#define IDD_addFileMonRule              292
#define IDD_cfgModuleKnowlege           293
#define IDD_qnmPcProcessModuleListSearch 294
#define IDD_prop_moduleKnowlege         295
#define IDD_moduleKnowlegeOptions       296
#define IDD_qnmCfgWindowsUpdatePolicy   297
#define IDD_prop_windowsUpdatePolicy    298
#define IDD_pcNetworkOptions_sel        299
#define IDD_cfgPcRegistry               300
#define IDD_cfgPcRegistrys              301
#define IDD_cfgPcRegistryKnowledge      302
#define IDD_prop_pcRegistryKnowledge    303
#define IDD_cfgStandardName             304
#define IDD_cfgStandardNames            305
#define IDD_qyCfgSystems                307
#define IDD_qyCfgSystem                 308
#define IDD_selectDsn                   310
#define IDR_TRAY_offline                314
#define IDR_TRAY_online                 315
#define IDR_TRAY_msg                    316
#define IDR_TRAY_notice                 318
#define IDD_prop_messenger              319
#define IDD_prop_imTask                 320
#define IDD_newImObjGrp                 321
#define IDD_prop_imGrp                  322
#define IDD_select                      323
#define IDD_prop_imMsg                  324
#define IDD_imGrp                       325
#define IDD_policy_isMgr                327
#define IDD_policy_imAuthCond           328
#define IDD_cfgSystemParams_is          329
#define IDD_imMsgSearch                 330
#define IDD_statMessengerInfo           331
#define IDR_MENU_null                   333
#define IDD_wwwQmCfg                    335
#define IDD_cfgIpKnowledge              338
#define IDD_prop_ipKnowledge            339
#define IDD_cfgPhoneMessenger           340
#define IDD_cfgGsmModem                 341
#define IDD_pcMon                       344
#define IDD_desktopsMon                 345
#define IDD_cfgSkippedMacs              346
#define IDD_DIALOG2                     355
#define IDR_TOOLBAR1                    363
#define IDB_select                      365
#define IDB_rectangle                   366
#define IDD_messenger                   369
#define IDR_MENU_const                  371
#define IDD_imObjRule                   374
#define IDD_status_daemon               377
#define IDD_exportClients               378
#define IDD_cfgCustomerService          379
#define IDD_qyBar                       388
#define IDD_confList                    391
#define IDC_LIST_IPINFO                 1000
#define IDC_IPADDRESS_INTRA_START       1000
#define IDC_IPADDRESS_INTRA_END         1001
#define IDC_BUTTON_status               1002
#define IDC_BUTTON_ADD                  1002
#define IDC_EDIT_DEPART                 1002
#define IDC_EDIT_COMINFO                1003
#define IDC_EXIT                        1003
#define IDC_title                       1004
#define IDC_BUTTON_ADD_IP               1004
#define IDC_BUTTON_EDIT                 1005
#define IDC_hint0                       1006
#define IDC_BUTTON_DEL                  1006
#define IDD_DLG_QUERY                   1006
#define IDC_STATIC_gm                   1007
#define IDC_IPADDRESS_INTER             1007
#define IDD_objs                        1007
#define IDC_BTN1                        1008
#define IDC_IPADDRESS_INTER0            1008
#define IDD_messenger1                  1008
#define IDD_messenger_testCreateUsr     1008
#define IDC_BTN2                        1009
#define IDC_STATIC_ks                   1009
#define IDC_IPADDRESS_INTER1            1009
#define IDC_BTN3                        1010
#define IDC_IPADDRESS_INTER2            1010
#define IDC_BTN4                        1011
#define IDC_IPADDRESS_INTER3            1011
#define IDC_BTN5                        1012
#define IDC_SCANINTERVAL                1012
#define IDC_BTN6                        1013
#define IDC_STATIC_lxdh                 1013
#define IDC_scanIntervalPerCNetSeg      1013
#define IDC_QY_WBC                      1014
#define IDC_BTN7                        1014
#define IDC_LIST0                       1014
#define IDC_EDIT1                       1015
#define IDC_BTN8                        1015
#define IDC_STATIC_sbxh                 1015
#define IDC_PASSWD                      1016
#define IDC_BTN9                        1016
#define IDC_BTN0                        1017
#define IDC_STATIC_sbxlh                1017
#define IDC_COMBO_TYPE                  1017
#define IDC_STATIC_gcbh                 1019
#define IDC_NAME                        1020
#define IDC_STATIC_sydd                 1021
#define IDC_EDIT8                       1022
#define IDC_STATIC_jqlx                 1023
#define IDC_EDIT9                       1023
#define IDC_EDIT10                      1024
#define IDC_WARNON                      1024
#define IDC_HINT2                       1024
#define IDC_DATETIMEPICKER2             1024
#define IDC_STATIC_qt                   1025
#define IDC_EDIT11                      1025
#define IDC_HINT3                       1025
#define IDC_DATETIMEPICKER3             1025
#define IDC_EDIT12                      1026
#define IDC_WARNUNTILUSRSTOPIT          1026
#define IDC_HINT4                       1026
#define IDC_DATETIMEPICKER4             1026
#define IDC_hint1                       1027
#define IDC_IPLOG                       1027
#define IDC_PROGRESS_reg                1028
#define IDC_CHK_BROOT                   1029
#define IDC_EDIT13                      1029
#define IDC_MAXWARNELAPSE               1029
#define IDC_BARID                       1030
#define IDC_EDIT14                      1030
#define IDC_FRDB                        1031
#define IDC_EDIT15                      1031
#define IDC_FZR                         1032
#define IDC_EDIT16                      1032
#define IDC_AQY                         1033
#define IDC_EDIT17                      1033
#define IDC_ADDR                        1034
#define IDC_EDIT18                      1034
#define IDC_SHOWLOG                     1034
#define IDC_EDIT19                      1035
#define IDC_AQYTEL                      1036
#define IDC_NTERMS                      1039
#define IDC_CERTTYPE                    1039
#define IDC_CERTID                      1040
#define IDC_STATIC0                     1040
#define IDC_GUESTTYPE                   1041
#define IDC_EDIT0                       1041
#define IDC_STATIC30                    1041
#define IDC_PCID                        1042
#define IDC_COMBO0                      1042
#define IDC_STATIC31                    1042
#define IDC_IP                          1043
#define IDC_STATIC32                    1043
#define IDC_GROUPNAME                   1044
#define IDC_STATIC33                    1044
#define IDC_OFFICE                      1045
#define IDC_GROUPNAME2                  1045
#define IDC_STATIC34                    1045
#define IDC_COUNTRY                     1046
#define IDC_STATIC35                    1046
#define IDC_DETAIL                      1047
#define IDC_ip0                         1047
#define IDC_STATIC36                    1047
#define IDC_STARTDATE                   1048
#define IDC_ip1                         1048
#define IDC_STATIC37                    1048
#define IDC_STARTTIME                   1049
#define IDC_STATIC38                    1049
#define IDC_ENDDATE                     1050
#define IDC_ip2                         1050
#define IDC_STATIC39                    1050
#define IDC_ENDTIME                     1051
#define IDC_STATIC40                    1051
#define IDC_COMBO1                      1052
#define IDC_STATIC41                    1052
#define IDC_COMBO2                      1053
#define IDC_STATIC42                    1053
#define IDC_HINT                        1054
#define IDC_COMBO3                      1054
#define IDC_STATIC43                    1054
#define IDC_CHK_GUESTUSEBEFOREREG       1055
#define IDC_COMBO4                      1055
#define IDC_STATIC44                    1055
#define IDC_COMBO5                      1056
#define IDC_STATIC45                    1056
#define IDC_COMBO6                      1057
#define IDC_MODIFY                      1058
#define IDC_COMBO7                      1058
#define IDC_DEL                         1059
#define IDC_MAC                         1059
#define IDC_COMBO8                      1059
#define IDC_LEFTAFTERDISCOUNT           1060
#define IDC_COMBO9                      1060
#define IDC_modifyDefSnmpPolicy         1060
#define IDC_FEE                         1061
#define IDC_OK                          1064
#define IDC_GETMULTIPCIDS               1066
#define IDC_PCIDLIST                    1067
#define IDC_OFFICELABEL                 1070
#define IDC_STATIC1                     1070
#define IDC_COUNTRYLABEL                1071
#define IDC_STATIC2                     1071
#define IDC_DETAILLABEL                 1072
#define IDC_STATIC3                     1072
#define IDC_PCIDLABEL                   1073
#define IDC_STATIC4                     1073
#define IDC_GRP                         1074
#define IDC_STATIC5                     1074
#define IDC_BARSLIST                    1075
#define IDC_STATIC6                     1075
#define IDC_ADD                         1076
#define IDC_STATIC7                     1076
#define IDC_CHK_MANUREGBAR              1077
#define IDC_STATIC8                     1077
#define IDC_SERVICETYPE                 1078
#define IDC_STATIC9                     1079
#define IDC_STATIC10                    1080
#define IDC_CFGKEYTYPE                  1081
#define IDC_STATIC11                    1081
#define IDC_KEYTYPELIST                 1082
#define IDC_STATIC12                    1082
#define IDC_STATIC13                    1083
#define IDC_KEYTYPENAME                 1084
#define IDC_STATIC14                    1084
#define IDC_KEYTYPECODE                 1085
#define IDC_STATIC15                    1085
#define IDC_IMPOLICY                    1086
#define IDC_STATIC16                    1086
#define IDC_BMPOLICY                    1087
#define IDC_STATIC17                    1087
#define IDC_officeName                  1088
#define IDC_STATIC18                    1088
#define IDC_subOfficeName               1089
#define IDC_STATIC19                    1089
#define IDC_ownerName                   1090
#define IDC_STATIC20                    1090
#define IDC_STATIC21                    1091
#define IDC_mac0                        1092
#define IDC_STATIC22                    1092
#define IDC_mac1                        1093
#define IDC_STATIC23                    1093
#define IDC_mac2                        1094
#define IDC_STATIC24                    1094
#define IDC_gm                          1095
#define IDC_STATIC25                    1095
#define IDC_servicePack                 1095
#define IDC_osName                      1096
#define IDC_STATIC26                    1096
#define IDC_lastCommTime                1097
#define IDC_STATIC27                    1097
#define IDC_auditTime                   1098
#define IDC_regTime                     1099
#define IDC_STATIC28                    1100
#define IDC_curUsrName                  1100
#define IDC_qwmVer                      1101
#define IDC_STATIC29                    1102
#define IDC_proxyServer                 1102
#define IDC_pcGrpList                   1103
#define IDC_lxdh                        1104
#define IDC_sbxlh                       1105
#define IDC_EDIT2                       1106
#define IDC_EDIT3                       1108
#define IDC_EDIT4                       1110
#define IDC_startIp                     1111
#define IDC_sbxh                        1112
#define IDC_EDIT5                       1113
#define IDC_endIp                       1114
#define IDC_gcbh                        1115
#define IDC_EDIT6                       1116
#define IDC_glCntIp                     1117
#define IDC_ks                          1118
#define IDC_EDIT7                       1119
#define IDC_jqlx                        1127
#define IDC_pcName                      1129
#define IDC_domainSvrIp                 1133
#define IDC_cntIp                       1134
#define IDC_qyRegToolDir                1135
#define IDC_CHECK_bNotAllAllowed        1136
#define IDC_monIp                       1136
#define IDC_cntPort                     1136
#define IDC_COMBO_rasCmd                1137
#define IDC_LIST_permittedPhoneNums     1138
#define IDC_COMBO_rasCmd2               1138
#define IDC_COMBO_stopMon               1139
#define IDC_EDIT_phoneNum               1140
#define IDC_COMBO_safeModeCmd           1141
#define IDC_COMBO_floppyCmd             1142
#define IDC_COMBO_cdromCmd              1143
#define IDC_RADIO_rasCmd_permitted      1144
#define IDC_COMBO_usbCmd                1144
#define IDC_RADIO_rasCmd_prohibited     1145
#define IDC_RADIO_rasCmd_default        1146
#define IDC_COMBO_sndEventLogCmd        1146
#define IDC_STATIC_col0                 1147
#define IDC_COMBO_col0                  1148
#define IDC_STATIC_col1                 1149
#define IDC_EDIT_col1                   1150
#define IDC_STATIC_col2                 1151
#define IDC_EDIT_col2                   1152
#define IDC_STATIC_ip                   1153
#define IDC_STATIC_mac                  1155
#define IDC_EDIT_mac                    1156
#define IDC_COMBO_queryType             1157
#define IDC_EDIT_nDays                  1158
#define IDC_COMBO_eventType             1159
#define IDC_STATIC_ver                  1160
#define IDC_CHECK_qyStopScripts         1161
#define IDC_pc0                         1162
#define IDC_pc0_zongBu                  1162
#define IDC_pc1                         1163
#define IDC_pc2                         1164
#define IDC_pc2_benBu                   1164
#define IDC_pc3                         1165
#define IDC_pc4                         1166
#define IDC_pc4_danWei                  1166
#define IDC_pc5                         1167
#define IDC_pc6                         1168
#define IDC_pc6_qiTaDanWei              1168
#define IDC_pc7                         1169
#define IDC_pc8                         1170
#define IDC_pc8_buMen                   1170
#define IDC_pc9                         1171
#define IDC_pc10                        1172
#define IDC_pc10_shiYongRen             1172
#define IDC_pc11                        1173
#define IDC_pc12                        1174
#define IDC_pc12_jiQiLeiXing            1174
#define IDC_pc13                        1175
#define IDC_pc14                        1176
#define IDC_pc14_ziChanBianHao          1176
#define IDC_pc15                        1177
#define IDC_pc16                        1178
#define IDC_pc16_zhuYaoYongTu           1178
#define IDC_pc17                        1179
#define IDC_pc18                        1180
#define IDC_pc18_lianXiDianHua          1180
#define IDC_pc19                        1181
#define IDC_pc20                        1182
#define IDC_pc20_shiYongDiDian          1182
#define IDC_pc21                        1183
#define IDC_pc22                        1184
#define IDC_pc22_shiYongDiDian          1184
#define IDC_pc23                        1185
#define IDC_STATIC_hint                 1186
#define IDC_pc24                        1186
#define IDC_pc24_ziChanBianHao1         1186
#define IDC_STATIC_eventType            1187
#define IDC_pc25                        1187
#define IDC_STATIC_hint2                1187
#define IDC_ipGrpList                   1188
#define IDC_pc26                        1188
#define IDC_pc26_ziChanShuoMing1        1188
#define IDC_CHECK_yhzc                  1189
#define IDC_pc27                        1189
#define IDC_CHECK1                      1190
#define IDC_pc28                        1190
#define IDC_pc28_ziChanBianHao2         1190
#define IDC_CHECK2                      1191
#define IDC_CHECK_distinguishSharedWebcams 1191
#define IDC_CHECK_bhxw                  1192
#define IDC_pc30                        1192
#define IDC_pc30_ziChanShuoMing2        1192
#define IDC_CHECK_jsjbd                 1193
#define IDC_pc31                        1193
#define IDC_DATETIMEPICKER1             1194
#define IDC_CHECK_zysj                  1194
#define IDC_CHECK_mac                   1195
#define IDC_CHECK_ip                    1196
#define IDC_CHECK_pc                    1197
#define IDC_CHECK_os                    1198
#define IDC_CHECK_usr                   1199
#define IDC_CHECK0                      1200
#define IDC_CHECK_mszjjr                1201
#define IDC_RADIO_exportCurQuery        1202
#define IDC_RADIO_exportBakData         1203
#define IDC_RADIO_exportCfg             1204
#define IDC_RADIO_clearupScannedIp      1205
#define IDC_RADIO_exportBhbCfg          1205
#define IDC_RADIO_clearupEvent          1206
#define IDC_STATIC_scanningIp           1207
#define IDC_STATIC_prePortIfIndex       1207
#define IDC_RADIO_exportRegInfo         1207
#define IDC_STATIC_scanningNetworkSegment 1208
#define IDC_STATIC_ipScan               1210
#define IDC_STATIC_selectedIp           1211
#define IDC_STATIC_nm                   1213
#define IDC_LIST_comm                   1214
#define IDC_LIST_qwmComm                1214
#define IDC_CHECK_autoClearup           1215
#define IDC_EDIT_hint                   1216
#define IDC_EDIT_qrtTitle               1217
#define IDC_STATIC_type                 1219
#define IDC_COMBO_des                   1220
#define IDC_LIST_unchkedIp              1222
#define IDC_LIST_tmpUnchkedIp           1223
#define IDC_EDIT_officeName             1223
#define IDC_EDIT_subOfficeName          1224
#define IDC_EDIT_lanName                1225
#define IDC_COMBO_lanName               1226
#define IDC_EDIT_passwdForStopMon       1228
#define IDC_COMBO_startProxy            1230
#define IDC_CHECK_unchk                 1232
#define IDC_PASSWD0                     1233
#define IDC_PASSWD1                     1234
#define IDC_USRLIST                     1238
#define IDC_GRPLIST                     1242
#define IDC_ANIMATE1                    1243
#define IDC_SCROLLBAR1                  1244
#define IDC_EDIT_getCommunity           1245
#define IDC_EDIT_setCommunity           1246
#define IDC_EDIT_v3_getCommunity        1247
#define IDC_EDIT_v3_setCommunity        1248
#define IDC_EDIT_usm                    1249
#define IDC_EDIT_grpName                1250
#define IDC_COMBO_securityLevel         1251
#define IDC_SPIN1                       1252
#define IDC_STATIC_nDays                1253
#define IDC_STATIC_startTime            1254
#define IDC_STATIC_lastCommTime         1255
#define IDC_EDIT_cusName                1256
#define IDC_LIST_switchPolicyGrp        1259
#define IDC_COMBO_snmpVer               1261
#define IDC_EDIT_usmName                1262
#define IDC_EDIT__getCommunity          1263
#define IDC_COMBO_snmpPolicyGrp         1265
#define IDC_LIST_ip                     1267
#define IDC_EDIT_place                  1268
#define IDC_COMBO_dbTypeName            1269
#define IDC_EDIT_uid                    1270
#define IDC_EDIT_pwd                    1271
#define IDC_CHECK_default               1273
#define IDC_EDIT_devType                1275
#define IDC_STATIC_switch               1276
#define IDC_CHECK_ucbDirectConn         1277
#define IDC_STATIC_switchPort           1278
#define IDC_STATIC_auditTime            1279
#define IDC_STATIC_productName          1281
#define IDC_STATIC_cusName              1282
#define IDC_STATIC_numPorts             1283
#define IDC_STATIC_sysDescr             1284
#define IDC_STATIC_netDevType           1285
#define IDC_STATIC_portIfDescr          1285
#define IDC_STATIC_place                1286
#define IDC_STATIC_prePortIfDescr       1287
#define IDC_EDIT_num                    1288
#define IDC_STATIC_portIfIndex          1289
#define IDC_COMBO_scanedObj             1289
#define IDC_STATIC_scanedObj            1290
#define IDC_COMBO_osName                1291
#define IDC_COMBO_spName                1293
#define IDC_EDIT_cusPcSp                1294
#define IDC_STATIC_spName               1295
#define IDC_COMBO_cusName               1296
#define IDC_scanIntervalPerPc           1298
#define IDC_EDIT_dbServIp               1299
#define IDC_STATIC_iCpsGlobalMaxSecureAddress 1300
#define IDC_STATIC_iCpsGlobalTotalSecureAddress 1301
#define IDC_STATIC_vlanId               1302
#define IDC_STATIC_iCpsIfMaxSecureMacAddr 1303
#define IDC_STATIC_iCpsIfCurrentSecureMacAddrCount 1304
#define IDC_STATIC_iCpsIfPortSecurityStatus 1305
#define IDC_STATIC_iCpsIfViolationAction 1306
#define IDC_EDIT_dbName                 1307
#define IDC_STATIC_mac0                 1308
#define IDC_STATIC_assetType            1309
#define IDC_STATIC_name                 1310
#define IDC_STATIC_des0                 1311
#define IDC_STATIC_endTime              1312
#define IDC_STATIC_des1                 1312
#define IDC_STATIC_col3                 1313
#define IDC_STATIC_des2                 1313
#define IDC_STATIC_col4                 1314
#define IDC_STATIC_env                  1315
#define IDC_EDIT_col3                   1316
#define IDC_EDIT_col4                   1317
#define IDC_EDIT_pcName                 1318
#define IDC_COMBO_assetType             1319
#define IDC_EDIT_assetName              1320
#define IDC_CHECK_onlyLast              1321
#define IDC_EDIT_assetDes0              1322
#define IDC_EDIT_monPort                1323
#define IDC_STATIC_rasCmd               1324
#define IDC_STATIC_monIp                1325
#define IDC_STATIC_floppyCmd            1326
#define IDC_STATIC_monPort              1327
#define IDC_STATIC_cdromCmd             1328
#define IDC_CHECK_bNotChkOnInternet     1329
#define IDC_STATIC_usbCmd               1330
#define IDC_EDIT_des0                   1332
#define IDC_STATIC_rasCmd2              1333
#define IDC_STATIC_safeModeCmd          1334
#define IDC_EDIT_name                   1335
#define IDC_STATIC_eventLogCmd          1337
#define IDC_EDIT_company                1337
#define IDC_EDIT_product                1338
#define IDC_STATIC_printerCmd           1339
#define IDC_STATIC_netStatCmd           1341
#define IDC_STATIC_sndUsrInfoCmd        1343
#define IDC_EDIT_nDwLevels              1364
#define IDC_EDIT_nZcbhs                 1366
#define IDC_STATIC_nDwLevels            1368
#define IDC_STATIC_nZcbhs               1370
#define IDC_STATIC_dw                   1371
#define IDC_STATIC_bm                   1372
#define IDC_RADIO_ucbDhcpEnabled        1373
#define IDC_RADIO_staticIp              1374
#define IDC_STATIC_ipMask               1375
#define IDC_STATIC_gateway              1376
#define IDC_RADIO_autoDns               1377
#define IDC_RADIO_staticDns             1378
#define IDC_STATIC_firstDns             1379
#define IDC_STATIC_syr                  1382
#define IDC_STATIC_pcNetworkPropType    1383
#define IDC_STATIC_des                  1384
#define IDC_STATIC_devDesc              1385
#define IDC_STATIC_devIp                1386
#define IDC_IPADDRESS_devIp             1388
#define IDC_IPADDRESS_ipMask            1389
#define IDC_IPADDRESS_gateway           1390
#define IDC_IPADDRESS_firstDns          1391
#define IDC_IPADDRESS_secondaryDns      1392
#define IDC_COMBO_pcNetworkPropType     1393
#define IDC_STATIC_secondaryDns         1394
#define IDC_EDIT_getCfgInterval         1395
#define IDC_EDIT_showPcNetworkPropInterval 1396
#define IDC_RADIO_ucbEnableAutodial     1397
#define IDC_EDIT_sndEventLogInterval    1397
#define IDC_RADIO_ucbNoNetAutodial      1398
#define IDC_EDIT_sndUsrInfoInterval     1398
#define IDC_RADIO_defaultDial           1399
#define IDC_EDIT_sndNetStatInterval     1399
#define IDC_CHECK_autoDetect            1400
#define IDC_EDIT_showProcessInterval    1400
#define IDC_CHECK_proxyOverride         1401
#define IDC_EDIT_getOpCmdInterval       1401
#define IDC_EDIT_showModulesInterval    1402
#define IDC_EDIT_port                   1403
#define IDC_EDIT_proxyServer            1404
#define IDC_STATIC_proxyServer          1405
#define IDC_STATIC_port                 1406
#define IDC_STATIC_grp0                 1407
#define IDC_STATIC_grp1                 1408
#define IDC_STATIC_snmpVer              1414
#define IDC_STATIC_snmpPolicyHint       1415
#define IDC_RADIO_procDj                1416
#define IDC_EDIT_auditDir               1417
#define IDC_STATIC_auditDir             1418
#define IDC_COMBO_sndPrinterCmd         1419
#define IDC_COMBO_sndNetStatCmd         1420
#define IDC_COMBO_sndUsrInfoCmd         1421
#define IDC_STATIC_sndEventLogCmd       1422
#define IDC_STATIC_sndPrinterCmd        1423
#define IDC_STATIC_sndNetStatCmd        1424
#define IDC_EDIT_maxLogs                1425
#define IDC_STATIC_usrName              1426
#define IDC_STATIC_passwd               1427
#define IDC_STATIC_getCfgInterval       1428
#define IDC_STATIC_getOpCmdInterval     1429
#define IDC_STATIC_qrtTitle             1430
#define IDC_STATIC_showPcNetworkPropInterval 1431
#define IDC_STATIC_sndEventLogInterval  1432
#define IDC_STATIC_sndUsrInfoInterval   1433
#define IDC_STATIC_sndNetStatInterval   1434
#define IDC_STATIC_showProcessInterval  1435
#define IDC_STATIC_maxLogs              1436
#define IDC_STATIC_passwdForStopMon     1437
#define IDC_STATIC_showModulesInterval  1437
#define IDC_STATIC_phoneNum             1438
#define IDC_STATIC_staticDw             1439
#define IDC_STATIC_staticSyr            1440
#define IDC_STATIC_staticIp             1441
#define IDC_STATIC_staticType           1442
#define IDC_STATIC_staticBm             1443
#define IDC_STATIC_staticIpAddress      1444
#define IDC_STATIC_staticPort           1445
#define IDC_STATIC_lanSetting           1446
#define IDC_STATIC_dialSetting          1447
#define IDC_STATIC_centerIp             1448
#define IDC_STATIC_centerAddr           1448
#define IDC_STATIC_qyRegToolDir         1449
#define IDC_STATIC_stopMon              1451
#define IDC_STATIC_ruleType             1453
#define IDC_STATIC_portIfDescrHint      1454
#define IDC_STATIC_ucbDownPortIfMacNewStatus 1455
#define IDC_COMBO_ibDownPortIfMacNew    1456
#define IDC_CHECK_ibDirectConn          1457
#define IDC_BUTTON_bindPcNetworkOptions 1458
#define IDC_BUTTON_cancelPcNetworkOptionsBindings 1459
#define IDC_STATIC_specialPhoneNum      1460
#define IDC_STATIC_bindPcNetworkOptions 1461
#define IDC_STATIC_cancelPcNetworkOptionsBindings 1462
#define IDC_STATIC_qycxCopyRight        1463
#define IDC_STATIC_passwd0              1464
#define IDC_STATIC_passwd1              1465
#define IDC_STATIC_cfgWarn              1466
#define IDC_STATIC_maxWarnElapse        1467
#define IDC_STATIC_condition            1468
#define IDC_STATIC_buDing               1469
#define IDC_STATIC_bieMing              1470
#define IDC_STATIC_qiShiIP              1474
#define IDC_STATIC_jieShuIP             1475
#define IDC_STATIC_danWei               1476
#define IDC_STATIC_buMen                1477
#define IDC_STATIC_usrInfoZone          1478
#define IDC_STATIC_pcName               1479
#define IDC_STATIC_osName               1480
#define IDC_STATIC_servicePack          1481
#define IDC_STATIC_ip0                  1482
#define IDC_STATIC_mac1                 1483
#define IDC_STATIC_ip1                  1484
#define IDC_STATIC_mac2                 1485
#define IDC_STATIC_ip2                  1486
#define IDC_STATIC_mac3                 1486
#define IDC_STATIC_qwmVer               1487
#define IDC_STATIC_mac4                 1487
#define IDC_STATIC_regTime              1488
#define IDC_STATIC_clearHint            1490
#define IDC_STATIC1_standard            1491
#define IDC_STATIC_staticMac0           1492
#define IDC_STATIC_staticAssetType      1493
#define IDC_STATIC_staticName           1494
#define IDC_STATIC_staticDes0           1495
#define IDC_STATIC_staticStartTime      1496
#define IDC_STATIC_staticEndTime        1497
#define IDC_STATIC_queryType            1498
#define IDC_STATIC_deviceType           1499
#define IDC_STATIC_keySearch            1500
#define IDC_STATIC_dbTypeName           1501
#define IDC_STATIC_dbServIp             1502
#define IDC_STATIC_dbName               1503
#define IDC_STATIC_uid                  1504
#define IDC_STATIC_pwd                  1505
#define IDC_STATIC_staticFirstDns       1506
#define IDC_STATIC_staticGateway        1507
#define IDC_STATIC_staticIpMask         1508
#define IDC_STATIC_staticDevIp          1509
#define IDC_STATIC_staticSecondaryDns   1510
#define IDC_STATIC_staticGateway2       1511
#define IDC_STATIC_staticFirstDns2      1512
#define IDC_STATIC_staticSecondaryDns2  1513
#define IDC_STATIC_unchkedIp            1514
#define IDC_STATIC_tmpUnchkedIp         1515
#define IDC_STATIC_unchkedHint          1516
#define IDC_STATIC_processName          1517
#define IDC_STATIC_cfgSwitchPolicyGrpWarning 1518
#define IDC_STATIC_grpName              1519
#define IDC_STATIC_getCommunity         1520
#define IDC_STATIC_setCommunity         1521
#define IDC_STATIC_securityLevel        1522
#define IDC_STATIC_addSwitchToGrpHint   1524
#define IDC_STATIC_ipAddress1           1525
#define IDC_STATIC_devDes0              1526
#define IDC_qnmEditMacInfo_switch       1527
#define IDC_qnmEditMacInfo_mac          1528
#define IDC_qnmEditMacInfo_switchPort   1529
#define IDC_qnmEditMacInfo_auditTime    1530
#define IDC_qnmSnmpObjProperties_productName 1531
#define IDC_qnmSnmpObjProperties_cusName 1532
#define IDC_qnmSnmpObjProperties_IP     1533
#define IDC_qnmSnmpObjProperties_place  1534
#define IDC_qnmSnmpObjProperties_numPorts 1535
#define IDC_qnmSnmpObjProperties_sysDescr 1536
#define IDC_STATIC_preICpsGlobalMaxSecureAddress 1537
#define IDC_STATIC_preICpsGlobalTotalSecureAddress 1538
#define IDC_STATIC_preVlanId            1541
#define IDC_STATIC_preICpsIfMaxSecureMacAddr 1542
#define IDC_STATIC_preICpsIfSecureMacAddrCount 1543
#define IDC_STATIC_preICpsIfViolationAction 1544
#define IDC_STATIC_preICpsIfPortSecurityStatus 1545
#define IDC_default_snmpVer             1546
#define IDC_default_getCommunity        1547
#define IDC_default_setCommunity        1548
#define IDC_cfgSwitchDefaultPolicyGrp_hint 1549
#define IDC_default_cfgSwitchPolicyGrpWarning 1550
#define IDC_STATIC_staticAuditTime      1551
#define IDC_STATIC_staticProductName    1552
#define IDC_STATIC_staticRuleType       1553
#define IDC_STATIC_ibDownPortIfMacChanged 1554
#define IDC_STATIC_ibDownPortIfMacNew   1554
#define IDC_STATIC_capScreenCmd         1563
#define IDC_COMBO_capScreenCmd          1564
#define IDC_STATIC_staticCapScreenDir   1565
#define IDC_STATIC_capScreenInterval    1566
#define IDC_EDIT_capScreenInterval      1568
#define IDC_BUTTON_browseDir            1570
#define IDC_BUTTON_cfgFileMonFilter     1571
#define IDC_CHECK_filterSysDir          1573
#define IDC_CHECK_filterUsrTmpDir       1574
#define IDC_CHECK_filterWinDir          1575
#define IDC_LIST_rules                  1576
#define IDC_STATIC_filterRules          1580
#define IDC_reset                       1583
#define IDC_COMBO_bMonAll               1584
#define IDC_CHECK_filterRename          1585
#define IDC_CHECK_filterModify          1586
#define IDC_COMBO_fileMonRuleType       1587
#define IDC_CHECK_bMonAllDisks          1588
#define IDC_STATIC_staticFileName       1589
#define IDC_EDIT_fileName               1590
#define IDC_STATIC_company              1591
#define IDC_STATIC_product              1592
#define IDC_STATIC_commonErr            1597
#define IDC_STATIC_memInfo              1598
#define IDC_CHECK_ucbDaemon             1602
#define IDC_CHECK_ucbSys                1603
#define IDC_CHECK_ucbUseNet             1604
#define IDC_CHECK_ucbHardware           1605
#define IDC_EDIT_commonErr              1606
#define IDC_EDIT_memInfo                1607
#define IDC_EDIT_securityLevel          1608
#define IDC_CHECK_ucbSpy                1609
#define IDC_CHECK_ucbAdvertisement      1610
#define IDC_CHECK_ucbVirus              1611
#define IDC_CHECK_ucbBackDoor           1612
#define IDC_STATIC_providerName         1613
#define IDC_EDIT_providerName           1614
#define IDC_STATIC_providerAddr         1615
#define IDC_EDIT_providerAddr           1616
#define IDC_STATIC_providerTime         1617
#define IDC_STATIC_cfgModuleKnowlegeHint 1618
#define IDC_STATIC_fileName             1619
#define IDC_EDIT_providerTime           1620
#define IDC_EDIT_moduleName             1621
#define IDC_STATIC_qnmPcProcessModuleListSearch 1622
#define IDC_EDIT_fileName_prop          1623
#define IDC_EDIT_name_prop              1624
#define IDC_EDIT_des0_prop              1625
#define IDC_EDIT_company_prop           1626
#define IDC_EDIT_product_prop           1627
#define IDC_EDIT_commonErr_prop         1628
#define IDC_EDIT_memInfo_prop           1629
#define IDC_EDIT_securityLevel_prop     1630
#define IDC_EDIT_providerName_prop      1631
#define IDC_EDIT_providerAddr_prop      1632
#define IDC_EDIT_providerTime_prop      1633
#define IDC_EDIT_capScreenDir           1634
#define IDC_STATIC_ibDownPortIfMacChangePort 1635
#define IDC_COMBO_ibDownPortIfMacChangePort 1636
#define IDC_STATIC_ucbDownPortIfMacChangePortStatus 1637
#define IDC_STATIC_ibNotLogIfMacChanged 1639
#define IDC_COMBO_ibNotLogIfMacChanged  1640
#define IDC_STATIC_ibNotLogIfMacChangedStatus 1641
#define IDC_RADIO_unAudited             1642
#define IDC_RADIO_audited               1643
#define IDC_RADIO_procModuleKnowlege    1645
#define IDC_STATIC_sndModuleInfoCmd     1647
#define IDC_COMBO_sndModuleInfoCmd      1648
#define IDC_RADIO_procDj98              1649
#define IDC_STATIC_licenseHint          1650
#define IDC_BUTTON_cfgWindowsUpdatePolicy 1651
#define IDC_STATIC_cfgWindowsUpdatePolicy 1652
#define IDC_STATIC_autoUpdate           1653
#define IDC_STATIC_staticAUOptions      1654
#define IDC_STATIC_AUOptions            1655
#define IDC_STATIC_staticScheduledInstallDay 1656
#define IDC_STATIC_ScheduledInstallDay  1657
#define IDC_STATIC_staticScheduledInstallTime 1658
#define IDC_STATIC_ScheduledInstallTime 1659
#define IDC_RADIO_ucbWSusPolicyExists   1660
#define IDC_STATIC_group_autoUpdate     1661
#define IDC_STATIC_staticNoAutoUpdate   1662
#define IDC_STATIC_NoAutoUpdate         1663
#define IDC_STATIC_staticAUOptions_autoUpdate 1664
#define IDC_STATIC_AUOptions_autoUpdate 1665
#define IDC_STATIC_staticScheduledInstallDay_autoUpdate 1666
#define IDC_STATIC_ScheduledInstallDay_autoUpdate 1667
#define IDC_STATIC_staticScheduledInstallTime_autoUpdate 1668
#define IDC_STATIC_ScheduledInstallTime_autoUpdate 1669
#define IDC_STATIC_staticUseWUServer    1670
#define IDC_STATIC_UseWUServer          1671
#define IDC_STATIC_staticWUServer       1672
#define IDC_STATIC_WUServer             1673
#define IDC_STATIC_staticWUStatusServer 1674
#define IDC_STATIC_WUStatusServer       1675
#define IDC_STATIC_staticRescheduleWaitTime 1676
#define IDC_STATIC_RescheduleWaitTime   1677
#define IDC_STATIC_staticRescheduleWaitTimeEnabled 1678
#define IDC_STATIC_RescheduleWaitTimeEnabled 1679
#define IDC_STATIC_staticNoAutoRebootWithLoggedOnUsers 1680
#define IDC_STATIC_NoAutoRebootWithLoggedOnUsers 1681
#define IDC_STATIC_staticElevateNonAdmins 1682
#define IDC_STATIC_ElevateNonAdmins     1683
#define IDC_STATIC_staticTargetGroupEnabled 1684
#define IDC_STATIC_TargetGroupEnabled   1685
#define IDC_STATIC_staticTargetGroup    1686
#define IDC_STATIC_TargetGroup          1687
#define IDC_STATIC_wsus                 1688
#define IDC_CHECK_pcAdapter             1689
#define IDC_CHECK_computer              1690
#define IDC_CHECK_windowsUpdatePolicy   1691
#define IDC_CHECK_staticNoAutoUpdate    1694
#define IDC_CHECK_staticAUOptions       1695
#define IDC_CHECK_staticUseWUServer     1696
#define IDC_CHECK_staticRescheduleWaitTime 1697
#define IDC_CHECK_staticRescheduleWaitTimeEnabled 1698
#define IDC_CHECK_staticNoAutoRebootWithLoggedOnUsers 1699
#define IDC_CHECK_staticScheduledInstallDay 1700
#define IDC_CHECK_staticScheduledInstallTime 1701
#define IDC_CHECK_staticElevateNonAdmins 1702
#define IDC_CHECK_staticTargetGroupEnabled 1703
#define IDC_CHECK_proxy                 1704
#define IDC_EDIT_WUServer               1710
#define IDC_EDIT_WUStatusServer         1711
#define IDC_EDIT_RescheduleWaitTime     1712
#define IDC_EDIT_TargetGroup            1719
#define IDC_BUTTON_import               1721
#define IDC_STATIC_showWindowsUpdatePolicyInterval 1722
#define IDC_EDIT_showWindowsUpdatePolicyInterval 1723
#define IDC_COMBO_AUOptions_autoUpdate  1724
#define IDC_COMBO_ScheduledInstallDay_autoUpdate 1725
#define IDC_COMBO_ScheduledInstallTime_autoUpdate 1726
#define IDC_COMBO_NoAutoUpdate          1727
#define IDC_COMBO_AUOptions             1728
#define IDC_COMBO_UseWUServer           1729
#define IDC_COMBO_RescheduleWaitTimeEnabled 1730
#define IDC_COMBO_NoAutoRebootWithLoggedOnUsers 1731
#define IDC_COMBO_ScheduledInstallDay   1732
#define IDC_COMBO_ScheduledInstallTime  1733
#define IDC_COMBO_ElevateNonAdmins      1734
#define IDC_COMBO_TargetGroupEnabled    1735
#define IDC_CHECK_staticDetectionFrequencyEnabled 1736
#define IDC_COMBO_DetectionFrequencyEnabled 1737
#define IDC_COMBO_DetectionFrequency    1738
#define IDC_STATIC_staticDetectionFrequencyEnabled 1739
#define IDC_STATIC_DetectionFrequencyEnabled 1740
#define IDC_STATIC_staticDetectionFrequency 1741
#define IDC_STATIC_DetectionFrequency   1742
#define IDC_STATIC_warnPercentOfBand    1743
#define IDC_EDIT_warnPercentOfBand      1744
#define IDC_STATIC_ibDownPortIfWarnSpeed 1745
#define IDC_COMBO_ibDownPortIfWarnSpeed 1746
#define IDC_STATIC_ibDownPortIfWarnSpeedStatus 1747
#define IDC_STATIC_warnPercentOfBandUnit 1748
#define IDC_STATIC_warnPercentOfBandStatus 1749
#define IDC_CHECK_popupToWarn           1750
#define IDC_STATIC_popupToWarnStartTime 1751
#define IDC_STATIC_popupToWarnStartTimeVal 1752
#define IDC_CHECK_cntIp                 1753
#define IDC_STATIC_cntAddr1             1754
#define IDC_STATIC_cntAddr2             1755
#define IDC_EDIT_cntAddr1               1757
#define IDC_EDIT_cntAddr2               1758
#define IDC_BUTTON_cfgPcRegistry        1760
#define IDC_STATIC_GROUP_capScreen      1761
#define IDC_LIST_pcRegistry             1762
#define IDC_COMBO_iRootKey              1763
#define IDC_EDIT_subKey                 1764
#define IDC_STATIC_iRootKey             1765
#define IDC_STATIC_subKey               1766
#define IDC_STATIC_nIntervals           1767
#define IDC_EDIT_nIntervals             1768
#define IDC_STATIC_cfgPcRegistryHint    1769
#define IDC_CHECK_unsupport98           1770
#define IDC_CHECK_unsupportMe           1771
#define IDC_CHECK_unsupport2000         1772
#define IDC_CHECK_unsupportXp           1773
#define IDC_CHECK_unsupport2003         1774
#define IDC_CHECK_ucbNotLogAdd          1775
#define IDC_CHECK_ucbNotLogDel          1776
#define IDC_CHECK_ucbNotLogModify       1777
#define IDC_STATIC_cfgName              1778
#define IDC_EDIT_cfgName                1779
#define IDC_STATIC_suggestedVal         1780
#define IDC_EDIT_suggestedVal           1781
#define IDC_STATIC_cfgPcRegistryKnowlegeHint 1782
#define IDC_STATIC_iRootKeyVal          1783
#define IDC_STATIC_subKeyVal            1784
#define IDC_STATIC_cfgNameVal           1785
#define IDC_STATIC_suggestedValVal      1786
#define IDC_RADIO_procRegistryKnowlege  1787
#define IDC_COMBO_sndPcRegistryValCmd   1788
#define IDC_STATIC_sndPcRegistryValCmd  1789
#define IDC_STATIC_queryCfgsInterval    1790
#define IDC_EDIT_queryCfgsInterval      1791
#define IDC_STATIC_nMaxConns            1792
#define IDC_EDIT_nMaxConns              1793
#define IDC_EDIT_zb                     1795
#define IDC_STATIC_preStandardName      1796
#define IDC_EDIT_zb_standard            1797
#define IDC_STATIC_standardName         1798
#define IDC_EDIT_bb                     1800
#define IDC_EDIT_bb_standard            1801
#define IDC_CHECK_zb                    1802
#define IDC_EDIT_dw                     1803
#define IDC_EDIT_dw_standard            1804
#define IDC_CHECK_bb                    1805
#define IDC_EDIT_bm                     1806
#define IDC_EDIT_bm_standard            1807
#define IDC_CHECK_syr                   1808
#define IDC_EDIT_syr                    1809
#define IDC_EDIT_syr_standard           1810
#define IDC_CHECK_bm                    1811
#define IDC_CHECK_dw                    1812
#define IDC_STATIC_hint_cfgStandardName 1813
#define IDC_LIST_cfgStandardName        1814
#define IDC_BUTTON_cfgStandardNames     1815
#define IDC_STATIC_staticCmdLine        1816
#define IDC_EDIT_cmdLine                1817
#define IDC_STATIC_cmdLine              1818
#define IDC_CHECK_bCmdLineGiven         1819
#define IDC_EDIT_cmdLine_prop           1820
#define IDC_STATIC_netFlow              1821
#define IDC_STATIC_uiWarnPercent        1823
#define IDC_EDIT_uiWarnPercent          1824
#define IDC_STATIC_ucDetectTimesBeforeWarn 1825
#define IDC_EDIT_ucDetectTimesBeforeWarn 1826
#define IDC_CHECK_ucbPopupToWarn        1827
#define IDC_STATIC_stopNetworkCardTime  1828
#define IDC_EDIT_stopNetworkCardTime    1829
#define IDC_STATIC_percentSym           1830
#define IDC_STATIC_ucWarnedNetworkCardCmd 1831
#define IDC_COMBO_ucWarnedNetworkCardCmd 1832
#define IDC_STATIC_showNetFlowInterval  1833
#define IDC_EDIT_showNetFlowInterval    1834
#define IDC_CHECK_autoConfigUrl         1835
#define IDC_STATIC_autoConfigUrlVal     1836
#define IDC_STATIC_autoConfigUrl        1837
#define IDC_EDIT_autoConfigUrl          1838
#define IDC_STATIC_sndPrintersInterval  1839
#define IDC_EDIT_sndPrintersInterval    1840
#define IDC_STATIC_nProcessQmObjQInterval 1841
#define IDC_EDIT_nProcessQmObjQInterval 1842
#define IDC_STATIC_nRefreshQmObjQLastCommTime 1843
#define IDC_EDIT_nRefreshQmObjQLastCommTime 1844
#define IDC_EDIT_showPcNetShareInterval 1845
#define IDC_STATIC_showPcNetShareInterval 1846
#define IDC_EDIT_showPcArpInterval      1847
#define IDC_STATIC_showPcArpInterval    1848
#define IDC_COMBO_dsn                   1849
#define IDC_COMBO_systemId              1850
#define IDC_STATIC_systemId             1851
#define IDC_STATIC_autorunCmd           1852
#define IDC_COMBO_autorunCmd            1853
#define IDC_STATIC_netShareCmd          1854
#define IDC_COMBO_netShareCmd           1855
#define IDC_STATIC_adminCmd             1856
#define IDC_COMBO_adminCmd              1857
#define IDC_LIST1                       1858
#define IDC_STATIC_systemName           1859
#define IDC_EDIT_systemName             1860
#define IDC_STATIC_ucHideQwmCmd         1861
#define IDC_COMBO_ucHideQwmCmd          1862
#define IDC_STATIC_sn                   1863
#define IDC_send                        1868
#define IDC_STATIC_ucbDsnless           1869
#define IDC_COMBO_ucbDsnless            1870
#define IDC_STATIC_staticSender         1878
#define IDC_STATIC_idInfo_send          1879
#define IDC_BUTTON_videoCompressor      1880
#define IDC_STATIC_staticReceiver       1881
#define IDC_STATIC_idInfo_recv          1882
#define IDC_STATIC_receiverDesc         1883
#define IDC_STATIC_staticSendTime       1884
#define IDC_STATIC_sendTime             1885
#define IDC_STATIC_staticRecvTime       1886
#define IDC_STATIC_recvTime             1887
#define IDC_STATIC_staticSubject        1888
#define IDC_STATIC_subject              1889
#define IDC_STATIC_staticContent        1890
#define IDC_STATIC_content              1891
#define IDC_STATIC_senderDesc           1892
#define IDC_STATIC_staticImTaskStatus   1893
#define IDC_STATIC_imTaskStatus         1894
#define IDC_COMBO_objList               1897
#define IDC_STATIC_staticMessengerId    1898
#define IDC_STATIC_messengerId          1899
#define IDC_CHECK_ucbLogImMsg           1902
#define IDC_CHECK_ucbUseMac             1906
#define IDC_CHECK_ucbUseDomainName      1907
#define IDC_CHECK_ucbUseOsUsrName       1908
#define IDC_CHECK_ucbUseMessengerName   1909
#define IDC_CHECK_ucbUsePcName          1910
#define IDC_CHECK_ucbAutoVerification   1911
#define IDC_STATIC_usIntervalInS_refreshRecentFriends 1912
#define IDC_CHECK6                      1913
#define IDC_EDIT_usIntervalInS_refreshRecentFriends 1914
#define IDC_STATIC_usIntervalInS_refreshContactList 1915
#define IDC_EDIT_usIntervalInS_refreshContactList 1916
#define IDC_STATIC_staticTalker         1917
#define IDC_EDIT_talker                 1918
#define IDC_STATIC_staticId             1919
#define IDC_EDIT_Id                     1920
#define IDC_EDIT_content                1921
#define IDC_pc29                        1923
#define IDC_CHECK_enableProxy           1924
#define IDC_CHECK_filterWinTmpDir       1925
#define IDC_CHECK_staticDetectionFrequency 1926
#define IDC_CHECK_messenger             1927
#define IDC_RADIO_procImMsg             1928
#define IDC_RADIO_procImHisTask         1929
#define IDC_STATIC_grpDisplayName       1930
#define IDC_EDIT_grpDisplayName         1931
#define IDC_STATIC_displayName          1932
#define IDC_EDIT_displayName            1933
#define IDC_CHECK_ucbImSwitchable       1934
#define IDC_CHECK_ucbPublic             1935
#define IDC_STATIC_startTmpMessengerId  1936
#define IDC_EDIT_startTmpMessengerId    1937
#define IDC_STATIC_endTmpMessengerId    1938
#define IDC_EDIT_endTmpMessengerId      1939
#define IDC_STATIC_hintForTmpMessengerId 1940
#define IDC_STATIC_startIp              1941
#define IDC_EDIT_startIp                1942
#define IDC_STATIC_endIp                1943
#define IDC_EDIT_endIp                  1944
#define IDC_STATIC_wLocation            1945
#define IDC_EDIT_wLocation              1946
#define IDC_STATIC_iWeight              1947
#define IDC_EDIT_iWeight                1948
#define IDC_STATIC_startIpVal           1949
#define IDC_STATIC_endIpVal             1950
#define IDC_STATIC_wLocationVal         1951
#define IDC_STATIC_iWeightVal           1952
#define IDC_RADIO_procIpKnowledge       1953
#define IDC_STATIC_countryCode          1954
#define IDC_EDIT_countryCode            1955
#define IDC_STATIC_phoneNo              1956
#define IDC_EDIT_phoneNo                1957
#define IDC_RADIO_procPhoneGuest        1958
#define IDC_STATIC_wDevIdStr            1959
#define IDC_STATIC_wDevIdStrVal         1960
#define IDC_STATIC_nameVal              1961
#define IDC_STATIC_idStr_vDev           1962
#define IDC_STATIC_idStr_vDevVal        1963
#define IDC_EDIT_idStr_contact          1964
#define IDC_CHECK_ucbDefault            1965
#define IDC_CHECK_ucbDefaultSmServer    1966
#define IDC_RADIO_default               1970
#define IDC_STATIC_pic0                 1974
#define IDC_CHECK_ucbSaveAsGif          1975
#define IDC_STATIC_pic2                 1976
#define IDC_STATIC_monPics_row          1976
#define IDC_STATIC_pic3                 1977
#define IDC_EDIT_monPics_row            1977
#define IDC_STATIC_pic4                 1978
#define IDC_STATIC_monPics_col          1978
#define IDC_STATIC_pic5                 1979
#define IDC_EDIT_monPics_col            1979
#define IDC_STATIC_pic6                 1980
#define IDC_EDIT_mac0                   1980
#define IDC_STATIC_pic7                 1981
#define IDC_EDIT_mac1                   1981
#define IDC_STATIC_pic8                 1982
#define IDC_EDIT_mac2                   1982
#define IDC_STATIC_wAdvertisement       1982
#define IDC_STATIC_pic9                 1983
#define IDC_EDIT_mac3                   1983
#define IDC_EDIT_wAdvertisement         1983
#define IDC_STATIC_pic10                1984
#define IDC_EDIT_mac4                   1984
#define IDC_STATIC_pic11                1985
#define IDC_STATIC_pic12                1986
#define IDC_STATIC_pic13                1987
#define IDC_STATIC_pic14                1988
#define IDC_STATIC_pic15                1989
#define IDC_EDIT_iWidth_webcam          1991
#define IDC_EDIT_iHeight_webcam         1992
#define IDC_STATIC_iWidth_webcam        1993
#define IDC_STATIC_iHeight_webcam       1994
#define IDC_STATIC_scope                2001
#define IDC_STATIC_zb                   2002
#define IDC_STATIC_bb                   2003
#define IDC_STATIC_usTimeoutInMsToSwitch 2006
#define IDC_EDIT_usTimeoutInMsToSwitch  2007
#define IDC_STATIC_minPasswdLen         2022
#define IDC_EDIT_minPasswdLen           2023
#define IDC_STATIC_maxInvalidLogonAttempts 2024
#define IDC_EDIT_maxInvalidLogonAttempts 2025
#define IDC_STATIC_screenCompressor     2027
#define IDC_COMBO_screenCompressors     2028
#define IDC_COMBO_outputType            2030
#define IDC_STATIC_outputType           2032
#define IDC_STATIC_usMaxMsgs_allowedToSwitchToTalkChannel_media 2046
#define IDC_EDIT_usMaxMsgs_allowedToSwitchToTalkChannel_media 2047
#define IDC_STATIC_usMaxMsgs_allowedToSwitchToTalkChannel_robot 2048
#define IDC_EDIT_usMaxMsgs_allowedToSwitchToTalkChannel_robot 2049
#define IDC_STATIC_mediaFileCompressor  2051
#define IDC_STATIC_avCompressor_req     2056
#define IDC_STATIC_webcamCompressor     2057
#define IDC_CHECK_ucbUseDynBmpRule      2092
#define IDC_STATIC_hint1                2101
#define IDC_STATIC_messengerName        2102
#define IDC_EDIT_passwd0                2103
#define IDC_EDIT_passwd1                2104
#define IDC_STATIC_pic1                 2110
#define IDC_STATIC_cntPort              2111
#define IDC_STATIC_wLanAdapterCmd       2112
#define IDC_COMBO_wLanAdapterCmd        2113
#define IDC_STATIC_ucBlueToothCmd       2116
#define IDC_COMBO_ucBlueToothCmd        2117
#define IDC_STATIC_ucInfraredCmd        2118
#define IDC_COMBO_ucInfraredCmd         2119
#define IDC_STATIC_uc1394Cmd            2120
#define IDC_COMBO_uc1394Cmd             2121
#define IDC_COMBO_ucSdHostAdapterCmd    2122
#define IDC_STATIC_ucSdHostAdapterCmd   2123
#define IDC_STATIC_autoAnswer_av        2124
#define IDC_COMBO_autoAnswer_av         2125
#define IDC_STATIC_autoAnswer_screen    2126
#define IDC_COMBO_autoAnswer_screen     2127
#define IDC_STATIC_autoAnswer_mediaFile 2128
#define IDC_COMBO_autoAnswer_mediaFile  2129
#define IDC_STATIC_netStats             2133
#define IDC_LIST_deamonStatus           2134
#define IDC_STATIC_filter               2135
#define IDC_EDIT_filter                 2136
#define IDC_CHECK_ucbNeedValidIpForDevice 2138
#define IDC_RADIO_ts_logon              2139
#define IDC_RADIO_ts_dev                2140
#define IDC_STATIC_lang                 2141
#define IDC_COMBO_lang                  2142
#define IDC_STATIC_category             2143
#define IDC_EDIT_category               2144
#define IDC_STATIC_avResolution         2150
#define IDC_STATIC_webcamResolution     2151
#define IDC_STATIC_ucWpdCmd             2155
#define IDC_COMBO_ucWpdCmd              2156
#define IDC_COMBO_ucMobileDeviceCmd     2157
#define IDC_STATIC_appName              2157
#define IDC_STATIC_ucMobileDeviceCmd    2158
#define IDC_CHECK_shareWebcamInConference 2158
#define IDC_STATIC_ucUsbNetworkCardCmd  2159
#define IDC_STATIC_conferenceId_shareWebcam 2159
#define IDC_COMBO_ucUsbNetworkCardCmd   2160
#define IDC_EDIT_conferenceId_shareWebcam 2160
#define IDC_CHECK_noLocalVideoInThisConference 2161
#define IDC_STATIC_group                2162
#define IDC_STATIC_hint_imObjRule       2163
#define IDC_STATIC_mediaDeviceCompressor 2177
#define IDC_STATIC_avCompressor_reply   2190
#define IDC_LIST_msg                    2223
#define IDC_BUTTON_export               2224
#define IDC_BUTTON_clear                2225
#define IDC_BUTTON_menu                 2250
#define IDC_STATIC_subtype              2265
#define IDC_COMBO_subtype               2266
#define IDC_STATIC_dbServName           2267
#define IDC_EDIT_dbServName             2268
#define IDC_RADIO_useWinAuth            2270
#define IDC_RADIO_useSqlAuth            2271
#define IDC_STATIC_makeClientHint       2272
#define IDC_CHECK_notUseP2pCall         2273
#define IDC_STATIC_offlineResServDir    2274
#define IDC_EDIT_offlineResServDir      2275
#define IDC_STATIC_mgrThreads_cs        2276
#define IDC_EDIT_mgrThreads_cs          2277
#define IDC_STATIC_cliThreads           2278
#define IDC_EDIT_cliThreads             2279
#define IDC_STATIC_mgrThreads_route     2280
#define IDC_EDIT_mgrThreads_route       2281
#define IDC_STATIC_mgrThreads_sw        2282
#define IDC_EDIT1_mgrThreads_sw         2283
#define IDC_EDIT_mgrThreads_sw          2283
#define IDC_STATIC_clientWelcomeMsg     2284
#define IDC_EDIT_clientWelcomMsg        2285
#define IDC_EDIT_clientWelcomeMsg       2285
#define IDC_STATIC_driver               2286
#define IDC_EDIT_driver                 2287
#define IDC_LIST_conf                   2288
#define IDC_STATIC_hintForMcu           2289
#define IDC_STATIC_startMcuId           2290
#define IDC_EDIT_startMcuId             2291
#define IDC_STATIC_cntofMcus            2292
#define IDC_EDIT_cntofMcus              2293
#define IDC_STATIC_mcuUsrName           2294
#define IDC_EDIT_mcuUsrName             2295
#define IDC_STATIC_hintForMcuUsr        2296
#define IDC_STATIC_mcuDomainName        2297
#define IDC_EDIT_mcuDomainName          2298
#define IDC_STATIC_mcuPasswd            2299
#define IDC_EDIT_mcuPasswd              2300
#define IDC_BUTTON_browserDir           2301
#define IDC_CHECK_bUseManuallySetResServId 2302
#define IDC_EDIT_resServId              2303
#define ID_TEST                         32771
#define ID_VIEW_MC_BAR                  32772
#define ID_FILE_SETUP                   32772
#define ID_MENU1                        32774
#define ID_SYS_START                    32774
#define ID_SYS_STOP                     32775
#define ID_LOG_DISPLAY                  32776
#define ID_LOG_DISPLAY_OFF              32777
#define ID_QY_CFG                       32779
#define ID_CFG_LOGTRANSFER              32781
#define ID_CFG_KEYLIST                  32783
#define ID_STAT_BARS                    32787
#define ID_STAT_PCS                     32788
#define ID_STAT_URLS                    32789
#define ID_STAT_KEYS                    32790
#define ID_DRAW_URLHISTORY              32791
#define ID_DRAW_KEYHISTORY              32792
#define ID_DRAW_BARHISTORY              32793
#define ID_DRAW_PCHISTORY               32794
#define ID_HELP_QYMC                    32795
#define ID_CFG_OPTIONS                  32796
#define ID_QYMCTEST                     32801
#define ID_EDIT_LIST                    32807
#define ID_CFG_BARMONLIST               32808
#define ID_CFG_MONPCLIST                32809
#define ID_CFG_MONBARLIST               32810
#define ID_CFG_MONSITELIST              32811
#define ID_CFG_MONKEYLIST               32812
#define ID_NEWBARMON                    32814
#define ID_NEWBARLISTMON                32815
#define ID_NEWPCLISTMON                 32816
#define ID_NEWSITELISTMON               32817
#define ID_NEWKEYLISTMON                32818
#define ID_NEWSITEMON                   32819
#define ID_NEWKEYMON                    32820
#define ID_STAT                         32821
#define ID_NEWPCMON                     32822
#define ID_NEWURLBROWSER                32823
#define ID_NEWIE                        32824
#define ID_CFG_BARSINFO                 32825
#define ID_CFG_TOBEROOT                 32826
#define ID_CFG_SJ                       32829
#define ID_CFG_BARINFO                  32830
#define ID_CFG_TERMS                    32832
#define ID_testModifyVar                32834
#define ID_PCLIST                       32835
#define ID_qyViewEvent                  32836
#define ID_qyPcList                     32837
#define ID_qyQuery                      32838
#define ID_qyStat                       32839
#define ID_qyRas                        32840
#define ID_pcInterConn                  32841
#define ID_qyIntraConn                  32842
#define ID_qyIpChanged                  32843
#define ID_qyDevChanged                 32844
#define ID_qyMgrPcGrp                   32845
#define ID_qyRegChanged                 32846
#define ID_qyQwm                        32847
#define ID_qyDel                        32850
#define ID_qyProperties                 32851
#define ID_qyStopMon                    32852
#define ID_qyStopScript                 32853
#define ID_qyStopScripts                32854
#define ID_qyStartScripts               32855
#define ID_qyStartMon                   32856
#define ID_cfgDomainIp                  32857
#define ID_cfgCnt                       32858
#define ID_MENUITEM32860                32860
#define ID_getRegTool                   32862
#define ID_cfgRegToolDir                32863
#define ID_rasRule                      32866
#define ID_qyCfgRasRule                 32868
#define ID_qyFind                       32871
#define ID_qyStopAutoReg                32874
#define ID_qyStartAutoReg               32875
#define ID_bdwyh                        32876
#define ID_wdwlsyh                      32877
#define ID_qyStartIpScan                32878
#define ID_qyStopIpScan                 32879
#define ID_qyRegScan                    32880
#define ID_qyStopRegScan                32881
#define ID_qyStartRespForUnreg          32882
#define ID_qyStopRespForUnreg           32883
#define ID_qyStartRegScan               32884
#define ID_qyCfgIpScan                  32885
#define ID_qyIpList                     32886
#define ID_qyScannedIpList              32887
#define ID_qyStopPcMon                  32888
#define ID_qyImport                     32889
#define ID_qyExport                     32890
#define ID_qyCfgPcRule                  32893
#define ID_pcRule                       32894
#define ID_qyCfgUnchk                   32895
#define ID_qyUsrList                    32896
#define ID_qySendMsg                    32899
#define ID_qyQwmDel                     32900
#define ID_qyOnInternet                 32901
#define ID_qyDelUsr                     32902
#define ID_qyDelPcUsr                   32903
#define ID_qyDelPcRule                  32904
#define ID_qyEdit                       32905
#define ID_qyVlanMgrList                32907
#define ID_qyDelProxy                   32908
#define ID_qnmStartProxy                32909
#define ID_qyCfgProxyRule               32910
#define ID_qyUnchkPc                    32913
#define ID_qyWillAttack                 32914
#define ID_qyUnchk                      32915
#define ID_qyStopUnchk                  32916
#define ID_qyStopWillAttack             32917
#define ID_qyAuditAll                   32918
#define ID_qyRefreshVlanPolicy          32920
#define ID_qyEditPcUsrInTab1            32922
#define ID_qyDelPcUsrInTab1             32923
#define ID_CFGUSR                       32924
#define ID_CFGWARN                      32925
#define ID_qyProxyServer                32927
#define ID_qyStopRereg                  32928
#define ID_qyStartRereg                 32929
#define ID_qyStartUpdate                32930
#define ID_qyStopUpdate                 32931
#define ID_qyNetworkView                32932
#define ID_qyMgrSwitchPolicy            32933
#define ID_qyConnectionView             32934
#define ID_qyProperties_network         32935
#define ID_qyProperties_switch          32936
#define ID_qyProperties_switchPort      32937
#define ID_qyEdit_switchInfo            32938
#define ID_qyMgrSwitchPolicyGrp         32939
#define ID_qyCfgSwitchPolicyGrps        32940
#define ID_qyMgrSwitchPolicyGrps        32941
#define ID_qyDel_switch                 32942
#define ID_qySpeedView                  32943
#define ID_qyNetworkSpeedView           32944
#define ID_qyStopIntraMon               32945
#define ID_qyStartIntraMon              32946
#define ID_cfgBhb                       32947
#define ID_cfgBhbSetup                  32948
#define ID_cfgBhbSysOptions             32949
#define ID_cfgBhbScannedNetSegs         32950
#define ID_qyStopBhb                    32951
#define ID_qyStartBhb                   32952
#define ID_qyStopSecChk                 32953
#define ID_qyStartSecChk                32954
#define ID_doSecChk                     32956
#define ID_qyNetDevEventAll             32957
#define ID_cfgAdvancedOptions           32958
#define ID_qyStopConnectionMon          32959
#define ID_qyStartConnectionMon         32960
#define ID_qyEdit_portUsrInfo           32961
#define ID_qyCancel_portUsrInfo         32962
#define ID_qyStopSnmpScan               32963
#define ID_qyStartSnmpScan              32964
#define ID_qyEdit_switchAndAllConns     32965
#define ID_qyCancel_switchAndAllConns   32967
#define ID_qyCancel_allConns            32968
#define ID_qyDel_connection             32971
#define ID_qySearch_mac                 32976
#define ID_qySearch_netDevEvent         32977
#define ID_qySearch_pcList              32978
#define ID_qySearch_pcEvent             32979
#define ID_qySearch_ip                  32980
#define ID_qyProperties_viewNetDevConn  32981
#define ID_qySearch_invalidNetDevConn   32982
#define ID_qySearch_unusedConn          32983
#define ID_qyStopMacScan                32984
#define ID_qyStartMacScan               32985
#define ID_qySearchSwitchPort           32987
#define ID_qySearchRootListMac          32988
#define ID_qyStopWatchIp                32990
#define ID_qyStartWatchIp               32991
#define ID_qySearchConnection           32993
#define ID_qyPcSpList                   32994
#define ID_qySearch_pcSpList            32995
#define ID_qyDelPcSp                    32996
#define ID_qyCusPcSp                    32997
#define ID_qySearchPcSp                 32999
#define ID_cfgInterMonIp                33000
#define ID_qyPermitNat                  33003
#define ID_qyStartPermitNat             33004
#define ID_qyStopPermitNat              33005
#define ID_beStaticAccessModeAndEnablePortSecurity 33006
#define ID_disablePortSecurity          33007
#define ID_setCpsIfMaxSecureMacAddr     33008
#define ID_secureMac                    33009
#define ID_cancelSecureMac              33010
#define ID_qyMonIf                      33011
#define ID_qyAssetsView                 33012
#define ID_qyCfgSp                      33013
#define ID_add                          33014
#define ID_addServicePack               33015
#define ID_qyReport                     33016
#define ID_qyReportAssetsInfo           33017
#define ID_qyReportAssetsInfo_en        33018
#define ID_qyReportAssetsInfo_byMac     33019
#define ID_qyReportAssetsInfo_byOs      33020
#define ID_qyReportAssetsInfo_en_byMac  33021
#define ID_qyReportAssetsInfo_en_byOs   33022
#define ID_addSp                        33023
#define ID_delSp                        33024
#define ID_delServicePack               33025
#define ID_qyCfgBoard                   33026
#define ID_qyCfgCustom                  33027
#define ID_snmpObjRuleList              33028
#define ID_qyCfgSnmpObjRule             33029
#define ID_qyCfgSnmpObjPortRule         33030
#define ID_qyStopDownPortIfMacChanged   33031
#define ID_qyStartDownPortIfMacChanged  33032
#define ID_qyDelSnmpObjRule             33033
#define ID_conflictConnList             33034
#define ID_qyCancelLock                 33035
#define ID_qyDelConflictConn            33036
#define ID_qyDelConnLock                33037
#define ID_qyCancelConnLock             33038
#define ID_qyDelSwitchConnLock          33039
#define ID_directConnList               33040
#define ID_undoSecChk                   33041
#define ID_pcNetworkPropList            33043
#define ID_pcNetworkRuleList            33044
#define ID_cfgPcNetworkOptions          33045
#define ID_qyProp_pcNetwork             33046
#define ID_qyEdit_pcNetwork             33047
#define ID_qyDel_pcNetwork              33048
#define ID_cfgSystemOptions             33049
#define ID_cfgSystemParams              33050
#define ID_pcProxyCfgPropList           33051
#define ID_pcProxyCfgRuleList           33052
#define ID_pcComputerPropList           33053
#define ID_pcComputerRuleList           33054
#define ID_queryNetworkProp             33055
#define ID_queryProxyCfg                33056
#define ID_queryComputerName            33057
#define ID_queryComputerInfo            33058
#define ID_pcEventLogList               33059
#define ID_pcOsUsrList                  33061
#define ID_qyPcNetStatList              33062
#define ID_pcPrinterPropList            33063
#define ID_pcProcessPropList            33064
#define ID_qyProhibitAll                33066
#define ID_qyProhibit                   33067
#define ID_pcProcessRuleList            33068
#define ID_qyPermit                     33069
#define ID_addPcProcessPermitRule       33070
#define ID_viewPcProcessRule            33071
#define ID_qyCfgAutoLogon               33072
#define ID_autoLogonList                33073
#define ID_viewRd                       33074
#define ID_viewRemoteDesktop            33075
#define ID_cancelRemoteDesktop          33076
#define ID_cfgPcMonOptions              33077
#define ID_monDesktop                   33078
#define ID_cancelMonDesktop             33079
#define ID_pcSecChkEventList            33080
#define IDC_stopFileMon                 33081
#define ID_stopFileMon                  33082
#define ID_startFileMon                 33083
#define ID_pcProcessModulePropList      33084
#define ID_qyCfgModuleInfo              33085
#define ID_addModuleKnowlege            33086
#define ID_editPcModuleKnowlege         33087
#define ID_stopModuleMon                33088
#define ID_startModuleMon               33089
#define ID_editModuleKnowlege           33090
#define ID_delModuleKnowlege            33091
#define ID_qyProp_pcModuleKnowlege      33092
#define ID_importModuleKnowlege         33093
#define ID_exportModuleKnowlege         33094
#define ID_clearupModuleKnowlege        33095
#define ID_pcWindowsUpdatePolicyPropList 33096
#define ID_pcWindowsUpdatePolicyRuleList 33097
#define ID_queryPcWindowsUpdatePolicyProp 33098
#define ID_qyStopDownPortIfWarnSpeed    33099
#define ID_qyStartDownPortIfWarnSpeed   33100
#define ID_qyPcView                     33101
#define ID_pcRegistryList               33102
#define ID_pcRegistryRuleStatusList     33103
#define ID_qyCfgPcRegistryKnowledge     33104
#define ID_stopPcRegistryMon            33105
#define ID_startPcRegistryMon           33106
#define ID_qyMakeClients                33107
#define ID_qyCfgStandardName            33108
#define ID_qyCfgStandardNames           33109
#define ID_pcNetFlowPropList            33110
#define ID_pcNetFlowPropList_ethernet   33111
#define ID_qyMgrSystems                 33113
#define ID_qyCfgSystems                 33114
#define ID_loadProcedObj                33115
#define ID_unloadProcedObj              33116
#define ID_pcNetSharePropList           33117
#define ID_qyTalk                       33127
#define ID_qyMessengerAuthList_needAudited 33134
#define ID_Menu                         33135
#define ID_qyMessengerAuthList          33137
#define ID_qyMessengerView              33138
#define ID_16MSGMGR_TASK                33144
#define ID_Menu33145                    33145
#define ID_qyTalkToTaskPeer             33149
#define ID_qyNewImGrp                   33156
#define ID_qyImGrpAuthList              33159
#define ID_qyAddTo                      33163
#define ID_qyDiscuss                    33165
#define ID_cfgImAuthCond                33168
#define ID_Menu33169                    33169
#define ID_qyModifyMessengerId          33171
#define ID_MENUNULL                     33174
#define ID_startAppCall                 33182
#define ID_startWhiteboard              33183
#define ID_avSetup                      33185
#define ID_wwwQm                        33189
#define ID_wwwQmCfgList                 33192
#define ID_wwwQmCfg                     33193
#define ID_ipKnowledgeList              33197
#define ID_17ISCLIENT_MODULES           33198
#define ID_17ISCLIENT_PHONEGUEST        33204
#define ID_qyPhoneGuestList             33206
#define ID_qyAdd                        33207
#define ID_qySendSm                     33209
#define ID_qyGsmModemList               33214
#define ID_qySmContactList              33215
#define ID_qyCfgDefaultSmContact        33217
#define ID_qyCfgSmContact               33218
#define ID_qyImObjAuthList              33223
#define ID_qyAddPhone                   33226
#define ID_qyDelPhone                   33228
#define ID_qyPhoneMessengerList         33229
#define ID_qyCfgDefaultSmServer         33231
#define ID_Menu33232                    33232
#define ID_PHONEMESSENGERS_PHONEMESSENGER 33233
#define ID_qyVerifiedPhoneList          33236
#define ID_qyViewSmContacts             33238
#define ID_qyCfgSkippedMacs             33240
#define ID_Menu33245                    33245
#define ID_MENU_APPLYFORTALKING         33284
#define ID_applyForTalking              33285
#define ID_Menu33289                    33289
#define ID_qyCopy                       33346
#define ID_qyPaste                      33347
#define ID_MENU_AVDEVICES               33359
#define ID_MENU                         33396
#define ID_viewDynBmp                   33398
#define ID_sharedDynBmpRuleList         33405
#define ID_cfgVisitor                   33407
#define ID_viewToolbox                  33416
#define ID_select                       33417
#define ID_stopEditing                  33422
#define ID_startEditing                 33424
#define ID_stopShowingRules             33426
#define ID_startToEdit                  33428
#define ID_startToShowRules             33429
#define ID_qyCusName                    33435
#define ID_qySetBackground              33436
#define ID_MENU_SAVE                    33438
#define ID_save                         33439
#define ID_MENU_OPEN                    33440
#define ID_open                         33441
#define ID_POPUP_RESETBACKGROUND        33442
#define ID_qyResetBackground            33443
#define ID_TASKINFO_TALKERLIST          33460
#define ID_TASKINFO_QLIST               33462
#define ID_CONTACT_NEWMESSENGER         33464
#define ID_qyNewMessenger               33465
#define ID_CONTACT_QYIMAMLIST           33466
#define ID_qyImAmList                   33467
#define ID_POPUP_SETPASSWD              33468
#define ID_MENU_isCmd_min               33470
#define ID_qyRefresh                    33989
#define ID_qySearch                     33990
#define ID_MENU_isCmd_max               36470
#define ID_CONTACT_KK                   36471
#define ID_POPUP                        36472
#define ID_POPUP_CFGCUSTOMERSERVICE     36473
#define ID_cfgCustomerService           36474
#define ID_16ISMGR_GROUP                36475
#define ID_16ISMGR_CUSTOMERSERVICE      36476
#define ID_customerServiceList          36478
#define ID_MY_BTN1                      61446

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        392
#define _APS_NEXT_COMMAND_VALUE         36510
#define _APS_NEXT_CONTROL_VALUE         2304
#define _APS_NEXT_SYMED_VALUE           140
#endif
#endif
