

#include	"stdafx.h"
#include	<tchar.h>

#include	"myresource_main.h"
#include	"afxres.h"

#include	"qyCusResCommon.h"

#include	"isCmdConst.h"

#include	"qnmCustomStr_common.h"
#include	"qnmCustomStr_netMc.h"


 QY_DMITEM  CONST_strTable_netMc[]  =
{
	{	CONST_resId_null,					_T(  ""  ),				},
	//
	{	CONST_resId_seqNo,					CONST_str_xuHao,		},
	//
	{	CONST_resId_idStr,					CONST_str_idStr,		},
	{	CONST_resId_idStr_grp,				CONST_str_idStr_grp,	},
	//
	{	CONST_resId_logon_wndTitle,			CONST_str_nm_logon,		},
	{	CONST_resId_logon_staticUsrName,	CONST_str_yongHuMing,	},
	{	CONST_resId_logon_staticPasswd,		CONST_str_password,		},
	//
	{	CONST_resId_y,						CONST_str_yes,			},		
	{	CONST_resId_n,						CONST_str_no,			},		
	{	IDOK,								CONST_str_OK,			},		
	{	IDCANCEL,							CONST_str_CANCEL,		},		
	{	IDC_BUTTON_DEL,						CONST_str_deleteRule,	},		

	//
	{	CONST_resId_lianJieMAC,				CONST_str_lianJieMAC,		},
	{	CONST_resId_caoZuoXiTong,			CONST_str_caoZuoXiTong,		},
	{	CONST_resId_buDing,					CONST_str_buDing,			},
	{	CONST_resId_leiXing,				CONST_str_leiXing,			},
	{	CONST_resId_wangLuoSheBei,			CONST_str_wangLuoSheBei,	},
	{	CONST_resId_likeSearch,				CONST_str_likeSearch,		},
	{	CONST_resId_switchPort,				CONST_str_duanKou,			},
	{	CONST_resId_mingChen,				CONST_str_mingChen,			},
	{	CONST_resId_jinChengMingChen,		CONST_str_jinChengMingChen,	},
	{	CONST_resId_moKuaiMingChen,			CONST_str_moKuaiMingChen,	},
	{	CONST_resId_cmdLine,				CONST_str_cmdLine,			},

	//

	//  ÒÔÏÂÊÇ¹¤¾ßÀ¸
	{	ID_qyRefresh,						CONST_ID_Refresh,			CONST_str_Refresh,	},
	{	ID_qySearch,						CONST_ID_Search,			CONST_str_Search,	},
	{	ID_APP_ABOUT,						CONST_str_ID_APP_ABOUT,		CONST_str_ID_APP_ABOUT_status,	},

	{	ID_qyShowWnd,					CONST_ID_qyShowMainWnd,		CONST_str_qyShowMainWnd,	},
	{	ID_qyQuitMainWnd,					CONST_ID_qyQuitMainWnd,		CONST_str_qyQuitMainWnd,	},


	//  ÒÔÏÂÊÇµ¯³ö²Ëµ¥
	{	ID_qyProperties,					CONST_ID_Properties,		CONST_str_Properties,	},
	{	ID_qyEdit,							CONST_ID_Edit,				CONST_str_Edit,			},
	{	ID_qyDel,							CONST_ID_Del,				CONST_str_Del,			},
	{	ID_qyEdit_pcNetwork,				CONST_ID_Edit,				CONST_str_Edit,			},
	{	ID_qyDel_pcNetwork,					CONST_ID_Del,				CONST_str_Del,			},
	{	CONST_resId_qyEdit1,				CONST_str_qyEdit,			CONST_str_bianjiyonghuxinxi,},
	{	ID_qySendMsg,						CONST_str_qySendMsg,		CONST_str_fasongxiaoxi,		},
	{	CONST_resId_qyProperties1,			CONST_ID_qyProperties,		CONST_str_yonghushuxing,	},
	{	ID_qyProp_pcNetwork,				CONST_ID_Properties,        CONST_str_Properties,	},
	{	ID_qyCfgPcRule,						CONST_ID_qyPersonalRule,	CONST_str_qyPersonalRule,				},
	{	ID_qyCfgStandardName,				CONST_ID_guifanyonghuxinxi,					},
	{	ID_qyDelPcRule,						CONST_ID_Del,				CONST_str_Del,			},
	{	ID_qySearchPcSp,					CONST_ID_SearchPcSp,       CONST_str_buDingChaXun,				},
	{	ID_qyCusPcSp,						CONST_ID_qyCusPcSp,        CONST_str_qyCusPcSp,				},
	{	ID_addSp,							CONST_ID_New,				CONST_str_New,				},
	{	ID_qyDelPcSp,						CONST_ID_Del,				CONST_str_Del,			},
	{	ID_delServicePack,					CONST_ID_Del,				CONST_str_Del,			},
   
	{	ID_qyProhibit,						CONST_ID_qyProhibit,		CONST_str_qyProhibit,	},
	{	ID_qyProhibitAll,					CONST_ID_qyProhibitAll,		CONST_str_qyProhibitAll,},
	{	ID_addPcProcessPermitRule,			CONST_ID_addPcProcessPermitRule,	CONST_str_addPcProcessPermitRule,	},
	{	ID_viewPcProcessRule,				CONST_ID_viewPcProcessRule,			CONST_str_viewPcProcessRule,		},
	{	ID_editPcModuleKnowlege,			CONST_ID_editPcModuleKnowlege,		CONST_str_editPcModuleKnowlege,		},
	{	ID_qyProp_pcModuleKnowlege,			CONST_ID_qyProp_pcModuleKnowlege,	CONST_str_qyProp_pcModuleKnowlege,	},
	{	ID_addModuleKnowlege,				CONST_ID_Add,		},
	{	ID_importModuleKnowlege,			CONST_ID_Import,		},
	{	ID_exportModuleKnowlege,			CONST_ID_Export,		},
	{	ID_clearupModuleKnowlege,			CONST_ID_Clear,		},

	//
	{	CONST_resId_anQuanGuanLi,						CONST_ID_anquanguanli,			},	//  2006/03/04
		{	ID_qyCfgPcRule,								CONST_ID_qyPersonalRule,		},
	{	CONST_resId_yuanChengZhuoMianGuanLi,			CONST_ID_yuanChengZhuoMianGuanLi,		},
		{	ID_viewRemoteDesktop,						CONST_ID_viewRemoteDesktop,		},
		{	ID_cancelRemoteDesktop,						CONST_ID_cancelRemoteDesktop,		},
		{	ID_queryNetworkProp,						CONST_ID_queryNetworkProp,            },
		{	ID_queryProxyCfg,							CONST_ID_queryProxyCfg,      },
		//  {	ID_queryComputerInfo,						CONST_ID_queryComputerInfo,      },
		{	ID_queryPcWindowsUpdatePolicyProp,			CONST_ID_queryPcWindowsUpdatePolicyProp,		},
		{	ID_pcProcessPropList,						CONST_ID_pcProcessPropList,                },
		{	ID_pcProcessModulePropList,					CONST_ID_pcProcessModulePropList,		},	
		{	ID_pcNetFlowPropList,						CONST_ID_pcNetFlowPropList,				},
		{	ID_pcNetFlowPropList_ethernet,				CONST_ID_pcNetFlowPropList_ethernet,				},
		{	ID_pcNetSharePropList,						CONST_ID_pcNetSharePropList,			},
	{	CONST_resId_jianKongYuShenJi,				CONST_ID_jianKongYuShenJi,			},
		{	ID_monDesktop,								CONST_ID_monDesktop,						CONST_str_monDesktop,	},
		{	ID_cancelMonDesktop,						CONST_ID_cancelMonDesktop,					CONST_str_cancelMonDesktop,	},
		//
		{	ID_pcSecChkEventList,						CONST_ID_pcSecChkEventList,					CONST_str_pcSecChkEventList,	},
		{	CONST_resId_pcSecChkEventList_netMc2,		CONST_ID_pcSecChkEventList_netMc2,			CONST_str_pcSecChkEventList_netMc2,	},
		{	ID_pcRegistryList,							CONST_ID_pcRegistryList,				},
		{	ID_pcRegistryRuleStatusList,				CONST_ID_pcRegistryRuleStatusList,	},
		{	ID_pcEventLogList,							CONST_ID_pcEventLogList,				},
		{	ID_pcOsUsrList,								CONST_ID_pcOsUsrList,         },
		{	ID_qyPcNetStatList,							CONST_ID_qyPcNetStatList,              },
		{	ID_pcPrinterPropList,						CONST_ID_pcPrinterPropList,               },
		{	ID_qyPcSpList,								CONST_ID_qyPcSpList,                 },
	{	CONST_resId_yongHuXinXiBianJiShenHe,		CONST_str_qyEdit,        },
	{	ID_qyEdit,									CONST_str_qyEdit,		},
	{	ID_qyDelPcUsr,								CONST_ID_Del,				CONST_str_Del,			},
	{	ID_qyProperties,							CONST_ID_Properties,		},
	//  2005/12/11
	//  "popup_viewUnchkedPcList - 5"
		{	ID_qyStopUnchk,							CONST_ID_qyStopUnchk,			CONST_str_qyStopUnchk,				},
	//  "popup_viewWillAttackPcList - 6"
		{	ID_qyStopWillAttack,					CONST_ID_qyStopWillAttack,		CONST_str_qyStopWillAttack,				},
	//  "popup_viewPcUsrInTab1List  - 7"
		{	ID_qyEditPcUsrInTab1,					CONST_str_qyEdit,				CONST_str_bianjiyonghuxinxi,		},
		{	ID_qyDelPcUsrInTab1,					CONST_ID_Del,				CONST_str_Del,			},
	//  "popup_tree_network 9"
		{	ID_qyProperties_network,				CONST_ID_Properties,		CONST_str_Properties,		},
	//  "popup_tree_switch 10"
        //  MENUITEM "ÊµÊ±Ë¢ÐÂ(&H)",                ID_qyRefresh
		{	ID_qyEdit_switchInfo,					CONST_ID_qyEdit_switchInfo,			CONST_str_qyEdit_switchInfo,		},
		{	ID_qyEdit_switchAndAllConns,			CONST_ID_qyEdit_switchAndAllConns,	CONST_str_qyEdit_switchAndAllConns,		},
		{	ID_qyCancel_switchAndAllConns,			CONST_ID_qyCancel_switchAndAllConns,CONST_str_qyCancel_switchAndAllConns,		},
		{	ID_qyCancel_allConns,					CONST_ID_qyCancel_allConns,			CONST_str_qyCancel_allConns,		},
		{	ID_qyCfgSnmpObjRule,					CONST_ID_qyCfgSnmpObjRule,			CONST_str_qyCfgSnmpObjRule,		},
		{	ID_qyDel_switch,						CONST_ID_Del,				CONST_str_Del,			},
		{	ID_qyProperties_switch,					CONST_ID_Properties,		CONST_str_Properties,		},						
	//  "popup_tree_switchPort 11"
		{	ID_qyWillAttack,							CONST_ID_qyWillAttack,								CONST_str_qyWillAttack,		},
		{	ID_qyStopWillAttack,						CONST_ID_qyStopWillAttack,							CONST_str_qyStopWillAttack,		},
		{	ID_beStaticAccessModeAndEnablePortSecurity,	CONST_ID_beStaticAccessModeAndEnablePortSecurity,	CONST_str_beStaticAccessModeAndEnablePortSecurity,		},
		{	ID_disablePortSecurity,						CONST_ID_disablePortSecurity,						CONST_str_disablePortSecurity,		},
		{	ID_setCpsIfMaxSecureMacAddr,				CONST_ID_setCpsIfMaxSecureMacAddr,					CONST_str_setCpsIfMaxSecureMacAddr,		},
		{	ID_qyCfgSnmpObjPortRule,					CONST_ID_qyCfgSnmpObjPortRule,						CONST_str_qyCfgSnmpObjPortRule,		},
		{	ID_qyProperties_switchPort,					CONST_ID_Properties,								CONST_str_Properties,		},
	//  "popup_rootList 12"
	    //  MENUITEM "MAC²éÑ¯(&M)",                 ID_qySearch_mac
		{	ID_qySearchConnection,						CONST_ID_qySearchConnection,						CONST_str_qySearchConnection,		},
		{	ID_qyEdit_portUsrInfo,						CONST_ID_qyEdit_portUsrInfo,						CONST_str_qyEdit_portUsrInfo,		},
		{	ID_qyCancel_portUsrInfo,					CONST_ID_qyCancel_portUsrInfo,						CONST_str_qyCancel_portUsrInfo,		},
		{	ID_qyDel_connection,						CONST_ID_Del,										CONST_str_Del,			},
		{	ID_secureMac,								CONST_ID_secureMac,									CONST_str_secureMac,		},
		{	ID_cancelSecureMac,							CONST_ID_cancelSecureMac,							CONST_str_cancelSecureMac,		},
	//  "popup_viewPcList_secChk  - 13"
		{	ID_doSecChk,								CONST_ID_doSecChk,									CONST_str_doSecChk,		},
		{	ID_undoSecChk,								CONST_ID_undoSecChk,								CONST_str_undoSecChk,		},
		{	CONST_resId_monIe,							CONST_ID_monIe,										CONST_str_monIe,	},
    //  "popup_viewNetDevConn 14"
		{	ID_qySearchSwitchPort,						CONST_ID_qySearchSwitchPort,						CONST_str_qySearchSwitchPort,		},
		{	ID_qyProperties_viewNetDevConn,				CONST_ID_qyProperties_viewNetDevConn,				CONST_str_qyProperties_viewNetDevConn,		},
	//	"popup_viewSnmpObjRuleList - 26"
		//  ID_qyCfgSnmpObjRule
		{	ID_qyDelSnmpObjRule,						CONST_ID_Del,										CONST_str_Del,			},
    //	"popup_viewConflictConnList - 27"
		{	ID_qyCancelConnLock,						CONST_ID_qyCancelConnLock,							CONST_str_qyCancelConnLock,		},
		{	ID_qyDelConnLock,							CONST_ID_Del,										CONST_str_Del,			},
		{	ID_qyDelSwitchConnLock,						CONST_ID_qyDelSwitchConnLock,						CONST_str_qyDelSwitchConnLock,		},
	//  "popup_viewPcNetworkProp - 28"


	//  "popup_messenger  -  100
		{	ID_qyTalk,									CONST_ID_qyTalk,						},
		{	ID_qyDiscuss,								CONST_ID_qyDiscuss,					},
		{	ID_qyRule,									CONST_ID_qyRule,					},
		{	ID_qyAddPhone,								CONST_ID_qyAddPhone,				},
		{	ID_qyDelPhone,								CONST_ID_qyDelPhone,				},
		{	ID_qyModifyMessengerId,						CONST_ID_qyModifyMessengerId,				},
		{	ID_qyAddTo,									CONST_ID_qyAddTo,				},
		{	CONST_resId_removeFrom,						CONST_ID_removeFrom,		},
		{	ID_wwwQmCfg,								CONST_ID_wwwQmCfg,	},
		{	ID_ipKnowledgeList,							CONST_ID_ipKnowledgeList,			},
		{	ID_setPasswd,								CONST_ID_setPasswd,					},
		//
		{	ID_qyViewSmContacts,						CONST_ID_qyViewSmContacts,			},
		{	ID_qyCfgSmContact,							CONST_ID_qyCfgSmContact,		},
		{	ID_qyCfgDefaultSmContact,					CONST_ID_qyCfgDefaultSmContact,		},
		{	ID_qyCfgDefaultSmServer,					CONST_ID_qyCfgDefaultSmServer,		},
		//
		{	ID_cfgImAuthCond,							CONST_ID_cfgImAuthCond,			},

	//  popup_viewProcedObj - 234
		{	ID_loadProcedObj,							CONST_ID_loadProcedObj,				CONST_str_loadProcedObj,					},
		{	ID_unloadProcedObj,							CONST_ID_unloadProcedObj,			CONST_str_unloadProcedObj,					},

	//  ²¹¶¡¿âÅäÖÃ
	{	ID_addServicePack,							CONST_str_New,		},
	

	//  ÒÔÏÂÊÇÏÂÀ­ÆÕÍ¨²Ëµ¥
	{	CONST_resId_menu_wenJian,					CONST_ID_FILE,			},
		{	ID_qyMgrSystems,						CONST_ID_qyMgrSystems,	},
		{	ID_qyCfgSystems,						CONST_ID_qyCfgSystems,	},
	//
	{	ID_qyMakeClients,							CONST_ID_qyMakeClients,		CONST_str_qyMakeClients,		},
	//
	{	CONST_resId_menu_guanLi,					CONST_ID_menu_guanLi,		},
		{	ID_qyScannedIpList,							CONST_ID_qyScannedIpList,		CONST_str_qyScannedIpList,          },
		{	CONST_resId_menu_jiSuanJiGuanLi,			CONST_ID_menu_jiSuanJiGuanLi,				},
			{	ID_qyPcView,								CONST_ID_qyPcView,			},
			{	ID_qyPcList,								CONST_ID_qyPcList,	CONST_str_qyPcList,             },
			{	ID_qyPcSpList,								CONST_ID_qyPcSpList,                },	
		{	CONST_resId_menu_lianXiRenGuanLi,			CONST_ID_menu_lianXiRenGuanLi,			},
			{	ID_qyMessengerView,							CONST_ID_qyMessengerView,	},
			{	ID_qyNewMessenger,							CONST_ID_qyNewMessenger,	},
			{	ID_qyMessengerAuthList,						CONST_ID_qyMessengerAuthList,	},
			{	ID_qyMessengerAuthList_needAudited,			CONST_ID_qyMessengerAuthList_needAudited,	},
			{	ID_qyImAmList,								CONST_ID_qyImAmList,				},
			{	ID_qyPhoneMessengerList,					CONST_ID_qyPhoneMessengerList,	},
			//


			//
			{	ID_qyProp_imTask,							CONST_ID_Properties,					},
		{	CONST_resId_menu_xiaoXiChaKan,			CONST_ID_menu_xiaoXiChaKan,	},
		{	CONST_resId_menu_yongHuGuanLi,			CONST_ID_menu_yongHuGuanLi,			         },
			{	ID_qyPcUsrList,							CONST_ID_qyPcUsrList,			CONST_str_qyPcUsrList,         },		
			{	ID_qyPcUsrInTab1List,					CONST_ID_qyPcUsrInTab1List,                },		
		{	CONST_resId_menu_keHuDuanGuanLi,		CONST_ID_menu_keHuDuanGuanLi,			         },
			{	ID_qwmSvrList,							CONST_ID_qwmSvrList,			CONST_str_qwmSvrList,         },	
			{	ID_imObjRuleList,						CONST_ID_imObjRuleList,		},
		{	CONST_resId_menu_wangLuoGuanLi,			CONST_ID_menu_wangLuoGuanLi,			         },
			{	ID_qyNetworkView,						CONST_ID_qyNetworkView,		},			//  (  "ÍøÂçÁª½ÓÊÓÍ¼(&S)"  )
			{	ID_qyConnectionView,					CONST_ID_qyConnectionView,            },		//  (  "ÓÃ»§½ÓÈëÊÓÍ¼(&J)
			{	ID_qyNetworkSpeedView,					CONST_ID_qyNetworkSpeedView,            },		//  (  "ÍøÂçÁ÷Á¿ÊÓÍ¼(&L)"  )
			{	ID_snmpObjRuleList,						CONST_ID_snmpObjRuleList,		},    //  (  "ÍøÂçÉè±¸¹ÜÀí²ßÂÔÁÐ±í(&C)"  )
			{	ID_conflictConnList,					CONST_ID_conflictConnList,		},        //  (  "Áª½Ó°ó¶¨ÁÐ±í(&D)"  )
			{	ID_directConnList,						CONST_ID_directConnList,					},			//  (  "½ÓÈëÁÐ±í(J)"  )
		{	CONST_resId_menu_jiSuanJiAnQuanGuanLi,		CONST_ID_menu_jiSuanJiAnQuanGuanLi,			         },
			{	ID_pcRuleList0,						CONST_ID_pcRuleList0,							CONST_str_pcRuleList,         },					
			{	ID_pcRuleList1,						CONST_ID_pcRuleList1,							CONST_str_pcRuleList,         },					

		{	CONST_resId_menu_yuanChengZhuoMianGuanLi,CONST_ID_menu_yuanChengZhuoMianGuanLi,			         },
			{	ID_pcNetworkPropList,				CONST_ID_pcNetworkPropList,						CONST_str_pcNetworkPropList,         },					
			{	ID_pcNetworkRuleList,				CONST_ID_pcNetworkRuleList,						CONST_str_pcNetworkRuleList,         },					
			{	ID_pcProxyCfgPropList,				CONST_ID_pcProxyCfgPropList,					CONST_str_pcProxyCfgPropList,         },					
			{	ID_pcProxyCfgRuleList,				CONST_ID_pcProxyCfgRuleList,					CONST_str_pcProxyCfgRuleList,         },					
			{	ID_pcComputerPropList,				CONST_ID_pcComputerPropList,					CONST_str_pcComputerPropList,         },					
			{	ID_pcComputerRuleList,				CONST_ID_pcComputerRuleList,					CONST_str_pcComputerRuleList,         },					
			{	ID_pcWindowsUpdatePolicyPropList,	CONST_ID_pcWindowsUpdatePolicyPropList,						},
			{	ID_pcWindowsUpdatePolicyRuleList,	CONST_ID_pcWindowsUpdatePolicyRuleList,						},
			{	ID_pcProcessPropList,				CONST_ID_pcProcessPropList,						CONST_str_pcProcessPropList,         },					
			{	ID_pcProcessRuleList,				CONST_ID_pcProcessRuleList,						CONST_str_pcProcessRuleList,         },					
		{	CONST_resId_menu_jianKongYuShenJi,		CONST_ID_menu_jianKongYuShenJi,												         },
			{	ID_pcEventLogList,					CONST_ID_pcEventLogList,						CONST_str_pcEventLogList,         },					
			{	ID_pcOsUsrList,						CONST_ID_pcOsUsrList,							CONST_str_pcOsUsrList,         },					
			{	ID_qyPcNetStatList,					CONST_ID_qyPcNetStatList,						CONST_str_qyPcNetStatList,         },					
			{	ID_pcPrinterPropList,				CONST_ID_pcPrinterPropList,						CONST_str_pcPrinterPropList,         },					
			{	ID_qyPcSpList,						CONST_ID_qyPcSpList,							CONST_str_qyPcSpList,         },							
		{	CONST_resId_menu_shiJianChaKan,			CONST_ID_menu_shiJianChaKan,															     },
			{	ID_qyEventAll,						CONST_ID_qyEventAll,							CONST_str_qyEventAll,         },					
			{	ID_qyRas,							CONST_ID_qyRas,									CONST_str_qyRas,					},					
			{	ID_qyProxyServer,					CONST_ID_qyProxyServer,																},
			{	ID_qyOnInternet,					CONST_ID_qyOnInternet,							CONST_str_qyOnInternet,				},					
			{	ID_qyIntraConn,						CONST_ID_qyIntraConn,							CONST_str_qyIntraConn,         },						
			{	ID_qyDevChanged,					CONST_ID_qyDevChanged,							CONST_str_qyDevChanged,         },					
			{	ID_qyQwmDel,						CONST_ID_qyQwmDel,								CONST_str_qyQwmDel,         },					
			{	ID_qyEventAll1,						CONST_ID_qyEventAll1,							CONST_str_qyEventAll1,        },
			{	ID_qyNetDevEventAll,				CONST_ID_qyNetDevEventAll,													},
			{	ID_qyOpEventAll,					CONST_ID_qyOpEventAll,							CONST_str_qyOpEventAll,         },							
		{	CONST_resId_menu_chaXun,				CONST_ID_Search,			         },
			{	ID_qySearch_netDevEvent,			CONST_ID_qySearch_netDevEvent,        },
			{	ID_qySearch_pcEvent,				CONST_ID_qySearch_pcEvent,          },
			{	ID_qySearch_pcList,					CONST_ID_qySearch_pcList,              },
			{	ID_qySearch_pcSpList,				CONST_ID_SearchPcSp,                 },
			{	ID_qySearch_mac,					CONST_ID_qySearch_mac,                 },
			{	ID_qySearch_ip,						CONST_ID_qySearch_ip,						},
			{	ID_qySearch_unusedConn,				CONST_ID_qySearch_unusedConn,            },
		{	CONST_resId_menu_ziChanGuanLi,		CONST_ID_menu_ziChanGuanLi,				},	
			{	ID_qyAssetsView,					CONST_ID_qyAssetsView,							CONST_str_qyAssetsView,         },								
	{	 ID_qySearch,								CONST_ID_Search,								CONST_str_Search,          },
	{	 ID_qyStat,									CONST_ID_Stat,									CONST_str_Stat,          },
	{	CONST_resId_menu_baoBiao,					CONST_ID_menu_baoBiao,		},
	{	CONST_resId_menu_yiJianZiChanZhongWenBaoBiao,CONST_ID_menu_yiJianZiChanZhongWenBaoBiao,},
			{	ID_qyReportAssetsInfo_byMac,			CONST_ID_qyReportAssetsInfo_byMac,			CONST_str_qyReportAssetsInfo_byMac,          			},	
			{	ID_qyReportAssetsInfo_byOs,				CONST_ID_qyReportAssetsInfo_byOs,			CONST_str_qyReportAssetsInfo_byOs,		},	
	{	CONST_resId_menu_yiJianZiChanYingWenBaoBiao,	CONST_ID_menu_yiJianZiChanYingWenBaoBiao,},
			{	ID_qyReportAssetsInfo_en_byMac,			CONST_ID_qyReportAssetsInfo_byMac,			CONST_str_qyReportAssetsInfo_byMac,  			},	
			{	ID_qyReportAssetsInfo_en_byOs,			CONST_ID_qyReportAssetsInfo_byOs,			CONST_str_qyReportAssetsInfo_byOs,			},	
	{	ID_qyAdd,									CONST_ID_Add,								CONST_str_Add,			},
	{	ID_qyImport,								CONST_ID_Import,		CONST_str_Import,       },
	{	ID_qyExport,								CONST_ID_Export,		CONST_str_Export		},
	{	ID_qyClearUp,								CONST_ID_Clear,			CONST_str_Clear,        },

	{	ID_FILE_PRINT_SETUP,						CONST_ID_PRINT_SETUP,	CONST_str_PRINT_SETUP,     },
	{	ID_FILE_PRINT,								CONST_ID_PRINT,			CONST_str_PRINT,   },
	{	ID_APP_EXIT,								CONST_ID_APP_EXIT,		CONST_str_APP_EXIT,     },
	//	{	CONST_resId_menu_yonghuGuanLi,			CONST_ID_menu_yongHuGuanLi,				},

	{	CONST_resId_menu_xiTong,			CONST_ID_menu_xiTong,					},
		//		{	ID_qyStopMon,					CONST_ID_qyStopMon,		CONST_str_qyStopMon,      },
		//		{	ID_qyStartMon,					CONST_ID_qyStartMon,		CONST_str_qyStartMon,      },
		{	ID_qyStopIpScan,				CONST_ID_qyStopIpScan,		CONST_str_qyStopIpScan,      },
		{	ID_qyStartIpScan,				CONST_ID_qyStartIpScan,		CONST_str_qyStartIpScan,      },

		{	ID_qyStopSnmpScan,				CONST_ID_qyStopSnmpScan,        CONST_str_qyStopSnmpScan,			},
		{	ID_qyStartSnmpScan,				CONST_ID_qyStartSnmpScan,       CONST_str_qyStartSnmpScan,			},
		{	ID_qyStopRegScan1,				CONST_ID_qyStopRegScan1,		CONST_str_qyStopRegScan1,		},
		{	ID_qyStartRegScan1,				CONST_ID_qyStartRegScan1,		CONST_str_qyStartRegScan1,		},
		{	ID_qyStopDownPortIfMacChanged,	CONST_ID_qyStopDownPortIfMacChanged,	CONST_str_qyStopDownPortIfMacChanged,		},
		{	ID_qyStartDownPortIfMacChanged,	CONST_ID_qyStartDownPortIfMacChanged,	CONST_str_qyStartDownPortIfMacChanged,		},
		{	ID_qyStopDownPortIfWarnSpeed,	CONST_ID_qyStopDownPortIfWarnSpeed,	},
		{	ID_qyStartDownPortIfWarnSpeed,	CONST_ID_qyStartDownPortIfWarnSpeed,	},
		//
		{	ID_qyStopSecChk,				CONST_ID_qyStopSecChk,			CONST_str_qyStopSecChk,		},
		{	ID_qyStartSecChk,				CONST_ID_qyStartSecChk,			CONST_str_qyStartSecChk,		},

		/*  nms:ÏÂÃæµÄ²Ëµ¥ÓÐÃ»ÓÐÓÃ°¡
        MENUITEM SEPARATOR
        MENUITEM "Í£ÓÃÖØÐÂ×¢²á¹¦ÄÜ£¬ÆôÓÃ½ö¼ì²é¹¦ÄÜ(&J)", ID_qyStartUpdate
        MENUITEM "ÆôÓÃÖØÐÂ×¢²á¹¦ÄÜ£¬Í£ÓÃ½ö¼ì²é¹¦ÄÜ(&C)", ID_qyStopUpdate
		*/
		{	ID_qyStopRegScan,				CONST_ID_qyStopRegScan,		CONST_str_qyStopRegScan,      },
		{	ID_qyStartRegScan,				CONST_ID_qyStartRegScan,	CONST_str_qyStartRegScan,      },
		{	ID_qyStopMacScan,				CONST_ID_qyStopMacScan,		CONST_str_qyStopMacScan,    },
        {	ID_qyStartMacScan,				CONST_ID_qyStartMacScan,	CONST_str_qyStartMacScan,		},
		{	ID_qyStopWatchIp,				CONST_ID_qyStopWatchIp,          },
		{	ID_qyStartWatchIp,				CONST_ID_qyStartWatchIp,    },
		{	ID_stopFileMon,					CONST_ID_stopFileMon,		},
		{	ID_startFileMon,				CONST_ID_startFileMon,		},
		{	ID_stopPcRegistryMon,			CONST_ID_stopPcRegistryMon,	},
		{	ID_startPcRegistryMon,			CONST_ID_startPcRegistryMon,	},
		{	ID_stopModuleMon,				CONST_ID_stopModuleMon,		},
		{	ID_startModuleMon,				CONST_ID_startModuleMon,		},
		{	ID_qyStartUpdate,				CONST_ID_qyStartUpdate,		CONST_str_qyStartUpdate,      },
		{	ID_qyStopUpdate,				CONST_ID_qyStopUpdate,		CONST_str_qyStopUpdate,      },
	{	CONST_resId_menu_peiZhi,			CONST_ID_menu_peiZhi,					},
		{	ID_qyCfgIpScan,						CONST_ID_qyCfgIpScan,				CONST_str_qyCfgIpScan,      },
		{	ID_qyMgrPcGrp,						CONST_ID_qyMgrPcGrp,				CONST_str_qyMgrPcGrp,      },
		{	ID_qyMgrPcGrp1,						CONST_ID_qyMgrPcGrp1,				CONST_str_qyMgrPcGrp1,	},
		{	ID_qyCfgUnchk,						CONST_ID_qyCfgUnchk,			CONST_str_qyCfgUnchk,      },
		{	ID_qyCfgSkippedMacs,				CONST_ID_qyCfgSkippedMacs,		}, 
		{	ID_cfgSystemParams,					CONST_ID_cfgSystemParams,				CONST_str_cfgSystemParams,      },
		{	ID_cfgPcMonOptions,					CONST_ID_cfgPcMonOptions,			CONST_str_cfgPcMonOptions,			},
		{	ID_cfgRasOptions,					CONST_ID_cfgRasOptions,			CONST_str_cfgRasOptions,      },
		{	ID_cfgPcNetworkOptions,				CONST_ID_cfgPcNetworkOptions,		CONST_str_cfgPcNetworkOptions,      },
		{	ID_qyCfgSwitchPolicyGrps,			CONST_ID_qyCfgSwitchPolicyGrps,		CONST_str_qyCfgSwitchPolicyGrps,  },
		{	ID_qyMgrSwitchPolicyGrps,			CONST_ID_qyMgrSwitchPolicyGrps,		CONST_str_qyMgrSwitchPolicyGrps,  },
		{	ID_qyCfgModuleInfo,					CONST_ID_qyCfgModuleInfo,			CONST_str_qyCfgModuleInfo,		},
		{	ID_qyCfgPcRegistryKnowledge,		CONST_ID_qyCfgPcRegistryKnowledge,								},
		{	ID_qyCfgCustom,						CONST_ID_qyCfgCustom,					CONST_str_qyCfgCustom,      },
		{	ID_qyCfgStandardNames,				CONST_ID_qyCfgStandardNames,				},
		{	ID_cfgOptions,						CONST_ID_cfgOptions,      },
		{	ID_cfgAdvancedOptions,				CONST_ID_cfgAdvancedOptions,			   },
		{	ID_CFGWARN,							CONST_ID_CFGWARN,				CONST_str_CFGWARN,      },
		{	ID_CFGUSR,							CONST_ID_CFGUSR,				CONST_str_CFGUSR,      },
	{	CONST_resId_menu_chaKan,			CONST_ID_menu_chaKan,					},
		{	ID_VIEW_TOOLBAR,					CONST_ID_VIEW_TOOLBAR,					},
		{	ID_VIEW_STATUS_BAR,					CONST_ID_VIEW_STATUS_BAR,					},

		{	ID_viewQnmStatus,					CONST_ID_viewQnmStaus,				},
		{	ID_viewDaemonStatus0,				CONST_ID_viewDaemonStatus0,			},
		{	ID_viewDaemonStatus1,				CONST_ID_viewDaemonStatus1,			},
		{	ID_viewDaemonStatus2,				CONST_ID_viewDaemonStatus2,			},

		{	ID_viewWarningTool,					CONST_ID_viewWarningTool,			},

		{	ID_qyRefresh,						CONST_ID_Refresh,				},
	{	CONST_resId_menu_chuangKou,			CONST_ID_menu_chuangKou,		},
		{	ID_WINDOW_NEW,						CONST_ID_WINDOW_NEW,                },
		{	ID_WINDOW_CASCADE,					CONST_ID_WINDOW_CASCADE,			},
		{	ID_WINDOW_TILE_HORZ,				CONST_ID_WINDOW_TILE_HORZ,                    },
		{	ID_WINDOW_ARRANGE,					CONST_ID_WINDOW_ARRANGE,                },
	{	CONST_resId_menu_bangZhu,			CONST_ID_menu_bangZhu,		},
		{	ID_HELP,							CONST_ID_HELP,                },
		{	ID_APP_ABOUT,						CONST_str_ID_APP_ABOUT,		CONST_str_ID_APP_ABOUT_status,	},

		//
		//
		{	CONST_resId_channelType,				CONST_str_channelType,				},
		{	CONST_resId_inOctets,					CONST_str_inOctets,					},
		{	CONST_resId_outOctets,					CONST_str_outOctets,				},
		{	CONST_resId_inSpeed,					CONST_str_inSpeed,					},
		{	CONST_resId_outSpeed,					CONST_str_outSpeed,					},

	//  ListViewµÄÒ»Ð©×ÊÔ´
	{	CONST_resId_zuiJinJianCeShiJian,				CONST_str_zuiJinJianCeShiJian,		},
	//
	//  ¶Ô»°¿ò×ÊÔ´¶¼·ÅÏÂÃæ
	{	CONST_resId_dlgStatic,				},	
	//
	{	IDD_qyCfgSystems,								CONST_IDD_qyCfgSystems,		},
	{	IDD_qyCfgSystem,								CONST_IDD_qyCfgSystem,		},
		{	IDC_STATIC_systemName,						CONST_IDC_STATIC_systemName,			},
		{	IDC_STATIC_systemId,						CONST_IDC_STATIC_systemId,			},
		{	IDC_STATIC_ucbDsnless,						CONST_IDC_STATIC_ucbDsnless,		},
		{	CONST_resId_dbNameOrDsnName,				CONST_ID_dbNameOrDsnName,	},
	//
	//	
	{	CONST_resId_STATIC_nDwLevels,					CONST_ID_STATIC_nDwLevels,			},
	{   CONST_resId_STATIC_nZcbhs,						CONST_ID_STATIC_nZcbhs,		},
	{	CONST_resId_STATIC_qrtTitle,					CONST_ID_STATIC_qrtTitle,				},
	{	CONST_resId_STATIC_hint,						CONST_ID_STATIC_hint,				},
	//
	{	IDC_STATIC_getCfgInterval,						CONST_IDC_STATIC_getCfgInterval,				},
	{	IDC_STATIC_queryCfgsInterval,					CONST_IDC_STATIC_queryCfgsInterval,			},
	{	IDC_STATIC_getOpCmdInterval,					CONST_IDC_STATIC_getOpCmdInterval,		},
	{	IDC_STATIC_showPcNetworkPropInterval,  			CONST_IDC_STATIC_showPcNetworkPropInterval,			},
	{   IDC_STATIC_sndEventLogInterval,					CONST_IDC_STATIC_sndEventLogInterval,			},
	{	IDC_STATIC_sndUsrInfoInterval,					CONST_IDC_STATIC_sndUsrInfoInterval,	},
	{	IDC_STATIC_sndNetStatInterval,					CONST_IDC_STATIC_sndNetStatInterval,			},		
	{	IDC_STATIC_showProcessInterval,					CONST_IDC_STATIC_showProcessInterval,			},
	{	IDC_STATIC_showModulesInterval,					CONST_IDC_STATIC_showModulesInterval,		},
	{	IDC_STATIC_showNetFlowInterval,					CONST_IDC_STATIC_showNetFlowInterval,			},
	{	IDC_STATIC_showWindowsUpdatePolicyInterval,		CONST_IDC_STATIC_showWindowsUpdatePolicyInterval,		},
	{	IDC_STATIC_sndPrintersInterval,					CONST_IDC_STATIC_sndPrintersInterval,		},
	{	IDC_STATIC_showPcNetShareInterval,				CONST_IDC_STATIC_showPcNetShareInterval,		},
	{	IDC_STATIC_showPcArpInterval,					CONST_IDC_STATIC_showPcArpInterval,			},
	{	IDC_STATIC_nProcessQmObjQInterval,				CONST_IDC_STATIC_nProcessQmObjQInterval,	},
	{	IDC_STATIC_nRefreshQmObjQLastCommTime,			CONST_IDC_STATIC_nRefreshQmObjQLastCommTime,		},
	{	IDC_STATIC_maxLogs,								CONST_IDC_STATIC_maxLogs,	},
	{	IDC_STATIC_nMaxConns,							CONST_IDC_STATIC_nMaxConns,			},
	//
	{	CONST_resId_STATIC_type,						CONST_str_leiXing,							},
	{	CONST_resId_STATIC_name,						CONST_str_mingChen,								},
	{	CONST_resId_STATIC_cusName,						CONST_str_bieMing,								},
	{	CONST_resId_STATIC_des0,						CONST_ID_STATIC_des0,								},
	{	CONST_resId_STATIC_langId,						CONST_str_yuYan,								},
	{	CONST_resId_STATIC_supportedOs,					CONST_ID_STATIC_supportedOs,						},
	{	CONST_resId_STATIC_url,							CONST_ID_STATIC_url,							},
	//
	{	CONST_resId_IDD_passwdForStopMon,				CONST_IDD_passwdForStopMon,							},
		{	CONST_resId_STATIC_passwdForStopMon,		CONST_ID_STATIC_passwdForStopMon,			},
	//
	{	CONST_resId_STATIC_phoneNum,					CONST_ID_STATIC_phoneNum,			},
	//
	{	IDD_cfgSystemParams,							CONST_str_cfgSystemParams,	},
	{	IDD_cfgSystemParams_is,							CONST_str_cfgSystemParams,	},
		{	IDC_STATIC_usIntervalInS_refreshRecentFriends,		CONST_IDC_STATIC_usIntervalInS_refreshRecentFriends,	},
		{	IDC_STATIC_usIntervalInS_refreshContactList,		CONST_IDC_STATIC_usIntervalInS_refreshContactList,	},

	{	IDD_exportClients,								CONST_str_pleaseSelect,				},
		{	IDC_RADIO_default,								CONST_IDC_RADIO_default,		},
		{	IDC_RADIO_ts_logon,								CONST_IDC_RADIO_ts_logon,		},
		{	IDC_RADIO_ts_dev,								CONST_IDC_RADIO_ts_dev,			},

	//  IDD_qnmCfgOptions_isClient
#if  0
	{	IDC_STATIC_cntName,								CONST_IDC_STATIC_cntName,		},
#endif
	{	CONST_resId_STATIC_centerIp,					CONST_IDC_STATIC_centerIp,		},
	{	IDC_CHECK_cntIp,								CONST_IDC_CHECK_cntIp,			},
#if  0
	{	IDC_STATIC_cntAddr0,							CONST_IDC_STATIC_cntAddr0,		},
#endif
	{	IDC_STATIC_cntAddr1,							CONST_IDC_STATIC_cntAddr1,		},
	{	IDC_STATIC_cntAddr2,							CONST_IDC_STATIC_cntAddr2,		},
	{	IDC_STATIC_cntPort,								CONST_IDC_STATIC_staticPort,	},

	{	CONST_resId_STATIC_qyRegToolDir,				CONST_IDC_STATIC_qyRegToolDir,	},
	//
	{	CONST_resId_IDD_qnmCfgRasOptions,			CONST_IDD_qnmCfgRasOptions,					},
		{	CONST_resId_STATIC_floppyCmd,					CONST_IDC_STATIC_floppyCmd,						},
		{	CONST_resId_STATIC_cdromCmd,					CONST_IDC_STATIC_cdromCmd,						},
		{	CONST_resId_STATIC_usbCmd,						CONST_IDC_STATIC_usbCmd,						},
		{	IDC_STATIC_wLanAdapterCmd,						CONST_IDC_STATIC_wLanAdapterCmd,				},
		{	CONST_resId_STATIC_rasCmd,						CONST_IDC_STATIC_rasCmd,						},
		{	IDC_STATIC_ucBlueToothCmd,						CONST_IDC_STATIC_ucBlueToothCmd,				},
		{	IDC_STATIC_ucInfraredCmd,						CONST_IDC_STATIC_ucInfraredCmd,					},
		{	IDC_STATIC_uc1394Cmd,							CONST_IDC_STATIC_uc1394Cmd,						},
		{	IDC_STATIC_ucWpdCmd,							CONST_IDC_STATIC_ucWpdCmd,						},
		{	IDC_STATIC_ucSdHostAdapterCmd,					CONST_IDC_STATIC_ucSdHostAdapterCmd,						},
		{	IDC_STATIC_ucMobileDeviceCmd,					CONST_IDC_STATIC_ucMobileDeviceCmd,						},
		{	IDC_STATIC_ucUsbNetworkCardCmd,					CONST_IDC_STATIC_ucUsbNetworkCardCmd,	},

		//  {	CONST_resId_STATIC_warnToInternetCmd,			CONST_IDC_STATIC_warnToInternetCmd,					},

		{	IDC_STATIC_autorunCmd,							CONST_IDC_STATIC_autorunCmd,				},
		{	IDC_STATIC_netShareCmd,							CONST_IDC_STATIC_netShareCmd,							},
		{	IDC_STATIC_safeModeCmd,							CONST_IDC_STATIC_safeModeCmd,						},
		{	IDC_STATIC_adminCmd,							CONST_IDC_STATIC_adminCmd,							},
		{	IDC_STATIC_ucHideQwmCmd,						CONST_IDC_STATIC_ucHideQwmCmd,						},
		
		{	CONST_resId_STATIC_sndEventLogCmd,				CONST_IDC_STATIC_sndEventLogCmd,						},
		{	CONST_resId_STATIC_sndUsrInfoCmd,				CONST_IDC_STATIC_sndUsrInfoCmd,				},
		{	CONST_resId_STATIC_sndPrinterCmd,				CONST_IDC_STATIC_sndPrinterCmd,							},
		{	CONST_resId_STATIC_sndNetStatCmd,				CONST_IDC_STATIC_sndNetStatCmd,						},
		{	IDC_STATIC_sndModuleInfoCmd,					CONST_IDC_STATIC_sndModuleInfoCmd,	},
		{	IDC_CHECK_bMonAllDisks,							CONST_IDC_CHECK_bMonAllDisks,				},
		{	CONST_resId_STATIC_auditDir,					CONST_IDC_STATIC_auditDir,				},
		{	IDC_STATIC_sndPcRegistryValCmd,					CONST_IDC_STATIC_sndPcRegistryValCmd,			},
		{	CONST_resId_STATIC_stopMon,						CONST_IDC_STATIC_stopMon,						},
		{	CONST_resId_CHECK_unchk,						CONST_IDC_CHECK_unchk,								},
		{	CONST_resId_STATIC_specialPhoneNum,				CONST_IDC_STATIC_specialPhoneNum,		},
		{	CONST_resId_add,								CONST_str_Add,	},
		{	CONST_resId_del,								CONST_str_Del,	},
		{	CONST_resId_CHECK_bNotChkOnInternet,			CONST_IDC_CHECK_bNotChkOnInternet,		},
		{	CONST_resId_STATIC_monIp,						CONST_IDC_STATIC_monIp,	},
		{	CONST_resId_STATIC_monPort,						CONST_str_duanKou,	},
	{	CONST_resId_IDD_qnmCfgPcNetworkOptions,		CONST_IDD_qnmCfgPcNetworkOptions,	},
		{	CONST_resId_STATIC_bindPcNetworkOptions,			CONST_IDC_STATIC_bindPcNetworkOptions,	},
		{	CONST_resId_BUTTON_bindPcNetworkOptions,			CONST_IDC_STATIC_Lock,	},
		{	CONST_resId_STATIC_cancelPcNetworkOptionsBindings,	CONST_IDC_STATIC_cancelPcNetworkOptionsBindings,	},
		{	CONST_resId_BUTTON_cancelPcNetworkOptionsBindings,	CONST_IDC_STATIC_CancelLock,	},
		{	IDC_STATIC_cfgWindowsUpdatePolicy,					CONST_IDC_STATIC_cfgWindowsUpdatePolicy,	},
		{	IDC_BUTTON_cfgWindowsUpdatePolicy,					CONST_IDC_BUTTON_cfgWindowsUpdatePolicy,		},
		{	IDC_STATIC_netFlow,									CONST_IDC_STATIC_netFlow,				},
		{	IDC_STATIC_uiWarnPercent,							CONST_IDC_STATIC_uiWarnPercent,			},
		{	IDC_STATIC_percentSym,								CONST_IDC_STATIC_percentSym,						},
		{	IDC_STATIC_ucDetectTimesBeforeWarn,					CONST_IDC_STATIC_ucDetectTimesBeforeWarn,		},
		{	IDC_STATIC_ucWarnedNetworkCardCmd,					CONST_IDC_STATIC_ucWarnedNetworkCardCmd,			},
		{	IDC_CHECK_ucbPopupToWarn,							CONST_IDC_CHECK_ucbPopupToWarn,			},
		{	IDC_STATIC_stopNetworkCardTime,						CONST_IDC_STATIC_stopNetworkCardTime,			},
	{	IDD_pcNetworkOptions_sel,					CONST_IDD_pcNetworkOptions_sel,	},
		{	IDC_CHECK_pcAdapter,								CONST_IDC_CHECK_pcAdapter,		},
		{	IDC_CHECK_proxy,									CONST_IDC_CHECK_proxy,	},
		{	IDC_CHECK_computer,									CONST_IDC_CHECK_computer,		},
		{	IDC_CHECK_windowsUpdatePolicy,						CONST_IDC_CHECK_windowsUpdatePolicy,		},
	{	IDD_qnmCfgPcMonOptions,						CONST_IDD_qnmCfgPcMonOptions,		},
		{	IDC_STATIC_GROUP_capScreen,						CONST_IDC_STATIC_capScreen,			},
		{	IDC_STATIC_capScreenCmd,						CONST_IDC_STATIC_capScreen,		},
		{	IDC_STATIC_staticCapScreenDir,					CONST_IDC_STATIC_staticCapScreenDir,	},
		{	IDC_BUTTON_browseDir,							_T(  "..."  ),				},
		{	IDC_STATIC_capScreenInterval,					CONST_IDC_STATIC_capScreenInterval,	},
		{	IDC_CHECK_ucbSaveAsGif,							CONST_IDC_CHECK_ucbSaveAsGif,		},
		{	IDC_STATIC_monPics_row,							CONST_IDC_STATIC_monPics_row,		},
		{	IDC_STATIC_monPics_col,							CONST_IDC_STATIC_monPics_col,		},
		//
		//  {	IDC_STATIC_fileMon,								_T(  "ÎÄ¼þ¼àÊÓ:"  ),			},
		{	IDC_BUTTON_cfgFileMonFilter,					CONST_IDC_BUTTON_cfgFileMonFilter,  },
		{	IDC_BUTTON_cfgPcRegistry,						CONST_IDC_BUTTON_cfgPcRegistry,  },

	{	IDD_cfgFileMonFilter,						CONST_IDC_BUTTON_cfgFileMonFilter,					},
		{	IDC_STATIC_filterRules,							CONST_IDC_STATIC_filterRules,							},
		{	IDC_CHECK_filterSysDir,							CONST_IDC_CHECK_filterSysDir,				},
		{	IDC_CHECK_filterWinDir,							CONST_IDC_CHECK_filterWinDir,		},
		{	IDC_CHECK_filterWinTmpDir,						CONST_IDC_CHECK_filterWinTmpDir,			},
		{	IDC_CHECK_filterUsrTmpDir,						CONST_IDC_CHECK_filterUsrTmpDir,			},
		//  {	IDC_clearAll,									CONST_IDC_clearAll,			},
		{	IDC_CHECK_filterRename,							CONST_IDC_CHECK_filterRename,			},
		{	IDC_CHECK_filterModify,							CONST_IDC_CHECK_filterModify,			},
		{	CONST_resId_fileMon_bMonAll,					CONST_IDC_fileMon_bMonAll,			},
		{	CONST_resId_fileMon_monOnly,					CONST_IDC_fileMon_monOnly,				},
		{	CONST_resId_fileMon_suffix,						CONST_IDC_fileMon_suffix,		},
		{	CONST_resId_fileMon_str,						CONST_IDC_fileMon_str,		},

	{	IDD_addFileMonRule,							CONST_IDD_addFileMonRule,		},
		{	CONST_resId_hint_addFileMonRule,				CONST_IDC_hint_addFileMonRule,	},
	{	IDD_cfgPcRegistrys,							CONST_IDC_BUTTON_cfgPcRegistry,		},
	{	IDD_cfgPcRegistry,							CONST_IDD_cfgPcRegistry,		},
		{	IDC_STATIC_iRootKey,							CONST_IDC_STATIC_iRootKey,		},
		{	IDC_STATIC_subKey,								CONST_IDC_STATIC_subKey,		},
		{	IDC_STATIC_cfgName,								CONST_IDC_STATIC_cfgName,		},
		{	IDC_STATIC_nIntervals,							CONST_IDC_STATIC_nIntervals,				},
		{	IDC_CHECK_unsupport98,							CONST_IDC_CHECK_unsupport98,					},
		{	IDC_CHECK_unsupportMe,							CONST_IDC_CHECK_unsupportMe,					},
		{	IDC_CHECK_unsupport2000,						CONST_IDC_CHECK_unsupport2000,				},
		{	IDC_CHECK_unsupportXp,							CONST_IDC_CHECK_unsupportXp,					},
		{	IDC_CHECK_unsupport2003,						CONST_IDC_CHECK_unsupport2003,				},
		{	IDC_CHECK_ucbNotLogAdd,							CONST_IDC_CHECK_ucbNotLogAdd,			},
		{	IDC_CHECK_ucbNotLogDel,							CONST_IDC_CHECK_ucbNotLogDel,			},
		{	IDC_CHECK_ucbNotLogModify,						CONST_IDC_CHECK_ucbNotLogModify,			},
		{	IDC_STATIC_cfgPcRegistryHint,					CONST_IDC_STATIC_cfgPcRegistryHint,	},

	//
	//
	{	IDD_cfgCustom,								CONST_IDD_cfgCustom,				},
		{	IDC_STATIC_hint_cfgStandardName,			CONST_IDC_STATIC_hint_cfgStandardName,		},
	{	IDD_cfgStandardNames,						CONST_IDD_cfgStandardNames,			},
		{	IDC_BUTTON_cfgStandardNames,				CONST_IDC_BUTTON_cfgStandardNames,		},
	{	IDD_cfgStandardName,						CONST_IDD_cfgStandardName,			},
		{	IDC_STATIC_preStandardName,					CONST_str_mingChen,				},
		{	IDC_STATIC_standardName,					CONST_IDC_STATIC_standardName,				},
		{	IDC_CHECK_zb,								CONST_IDC_CHECK_zb,			},
		{	IDC_CHECK_bb,								CONST_IDC_CHECK_bb,			},
		{	IDC_CHECK_dw,								CONST_IDC_CHECK_dw,			},
		{	IDC_CHECK_bm,								CONST_IDC_CHECK_bm,			},
		{	IDC_CHECK_syr,								CONST_IDC_CHECK_syr,			},
	{	IDD_qnmCfgOptions,							CONST_IDD_qnmCfgOptions,	},
#if  0
	{	IDD_qnmCfgOptions_isClient,					CONST_IDD_qnmCfgOptions,	},
#endif
	{	CONST_resId_IDD_qnmCfgPcRule,				CONST_IDD_qnmCfgPcRule,						},
	{	CONST_resId_IDD_qnmEditPcUsrInfo,			CONST_IDD_qnmCfgPcRule,			},
		{	CONST_resId_hint0,						CONST_ID_hint0,	},
		{	CONST_resId_hint1,						CONST_ID_hint1,	},
		{	CONST_resId_pc0_zongBu,					CONST_str_zongBu,	},		//  2009/01/04
		{	CONST_resId_pc2_benBu,					CONST_str_benBu,},
		{	CONST_resId_pc4_danWei,					CONST_str_danWei,},
		{	CONST_resId_pc8_buMen,					CONST_str_buMen,},
		{	CONST_resId_pc10_shiYongRen,			CONST_str_shiYongRen,},
		{	CONST_resId_pc12_jiQiLeiXing,			CONST_str_jiQiLeiXing,},
		{	CONST_resId_pc16_zhuYaoYongTu,			CONST_str_zhuYaoYongTu,},
		{	CONST_resId_pc18_lianXiDianHua,			CONST_str_lianXiDianHua,},
		{	CONST_resId_pc20_shiYongDiDian,			CONST_str_shiYongDiDian,},
		{	CONST_resId_pc14_ziChanBianHao,			CONST_str_ziChanBianHao,},
		{	CONST_resId_pc24_ziChanBianHao1,		CONST_str_ziChanBianHao1,},
		{	CONST_resId_pc26_ziChanShuoMing1,		CONST_str_ziChanShuoMing1,},
		{	CONST_resId_pc28_ziChanBianHao2,		CONST_str_ziChanBianHao2,},
		{	CONST_resId_pc30_ziChanShuoMing2,		CONST_str_ziChanShuoMing2,},





	//  2005/11/09
	{	CONST_resId_IDD_ABOUTBOX,					CONST_IDD_ABOUTBOX,	},
		{	CONST_resId_ver,							CONST_ID_ver,	},
		{	CONST_resId_qycxCopyRight,					CONST_ID_qycxCopyRight,	},
	{	CONST_resId_IDD_CFGUSR,						CONST_IDD_CFGUSR,		},
		{	CONST_resId_name,						CONST_ID_name,		},
		{	IDC_STATIC_passwd0,						CONST_IDC_STATIC_passwd0,		},
		{	IDC_STATIC_passwd1,						CONST_IDC_STATIC_passwd1,		},
		{	IDC_STATIC_scope,						CONST_IDC_STATIC_scope,		},
		//
		{	IDC_STATIC_zb,							CONST_str_zongBu,			},
		{	IDC_STATIC_bb,							CONST_str_benBu,			},
		{	IDC_STATIC_dw,							CONST_str_danWei,			},
		{	IDC_STATIC_bm,							CONST_str_buMen,			},

	{	CONST_resId_IDD_CFGUSRS,					CONST_IDD_CFGUSRS,		},
		{	IDC_STATIC_minPasswdLen,					CONST_IDC_STATIC_minPasswdLen,	},
		{	IDC_STATIC_maxInvalidLogonAttempts,			CONST_IDC_STATIC_maxInvalidLogonAttempts,	},
		{	CONST_resId_HINT,							CONST_ID_HINT,		},
		{	CONST_resId_ADD,							CONST_str_Add,		},
		{	CONST_resId_MODIFY,							CONST_str_qyModify,		},
		{	CONST_resId_DEL,							CONST_str_Del,		},
	{	CONST_resId_IDD_CFGWARN,					CONST_ID_IDD_CFGWARN,							},
		{	CONST_resId_WARNON,							CONST_ID_WARNON,					},
		{	CONST_resId_STATIC_cfgWarn,					CONST_ID_STATIC_cfgWarn,						},
		{	CONST_resId_WARNUNTILUSRSTOPIT,				CONST_ID_WARNUNTILUSRSTOPIT,		},
		{	CONST_resId_STATIC_maxWarnElapse,			CONST_ID_STATIC_maxWarnElapse,			},
		{	IDC_CHECK_popupToWarn,						CONST_IDC_CHECK_popupToWarn,				},
		{	IDC_STATIC_popupToWarnStartTime,			CONST_IDC_STATIC_popupToWarnStartTime,		},
	{	CONST_resId_IDD_clearupEventCond,			CONST_IDD_clearupEventCond,		},
		{	IDC_STATIC_condition,						CONST_IDC_STATIC_condition,		},
		{	IDC_STATIC_startTime,						CONST_str_startTime,		},
		{	IDC_STATIC_endTime,							CONST_str_endTime,		},
	{	CONST_resId_IDD_qnmSearch,					CONST_str_Search,				},
	//  2005/11/11
	{	CONST_resId_IDD_cusPcSp,					CONST_IDD_cusPcSp,		},
		{	CONST_resId_STATIC_buDing,					CONST_ID_STATIC_buDing,		},
		{	CONST_resId_STATIC_bieMing,					CONST_ID_STATIC_bieMing,		},
	{	CONST_resId_IDD_qnmCfgIpScan,				CONST_IDD_qnmCfgIpScan,		},
		{	IDC_ADD,									CONST_str_Add,		},
		{	IDC_MODIFY,									CONST_str_MODIFY		},
		{	IDC_DEL,									CONST_str_Del,		},
		{	IDC_reset,									CONST_str_reset,		},

	/*
	PUSHBUTTON      "ÐÂ½¨",,78,150,50,14
    PUSHBUTTON      "É¾³ý",IDC_DEL,186,150,50,14
    PUSHBUTTON      "ÐÞ¸Ä",IDC_MODIFY
	//	{	CONST_resId_add,								_T(  "Ìí¼Ó"  ),	},
	//	{	CONST_resId_del,								CONST_str_Del,	},
	//	{	CONST_resId_ADD,							_T(  "Ôö¼Ó"  ),		},
	//	{	CONST_resId_MODIFY,							_T(  "ÐÞ¸Ä¿ÚÁî"  ),		},
		{	CONST_resId_ADD,							_T(  "Ôö¼Ó"  ),		},
		{	CONST_resId_MODIFY,							_T(  "ÐÞ¸Ä¿ÚÁî"  ),		},
		{	CONST_resId_DEL,							CONST_str_Del,		},
		*/



	{	CONST_resId_IDD_qnmCfgPcGrp,				CONST_IDD_qnmCfgPcGrp,		},
		{	CONST_resId_STATIC_qiShiIP,					CONST_IDC_STATIC_qiShiIP,		},
		{	CONST_resId_STATIC_jieShuIP,				CONST_IDC_STATIC_jieShuIP,		},
		{	CONST_resId_STATIC_danWei,					CONST_IDC_STATIC_danWei,		},
		{	CONST_resId_STATIC_buMen,					CONST_IDC_STATIC_buMen,		},
		{	CONST_resId_STATIC_scanedObj,				CONST_IDC_STATIC_scanedObj,		},
		//
	{	CONST_resId_STATIC_shiYongRen,					CONST_STATIC_shiYongRen,		},
			//
	{	CONST_resId_IDD_shhgPcProperties,			CONST_IDD_shhgPcProperties,	},
		{	CONST_resId_pc0_zongBu,						CONST_IDC_CHECK_zb,	},
 		{	CONST_resId_pc2_benBu,						CONST_IDC_CHECK_bb,	},
 		{	CONST_resId_pc4_danWei,						CONST_IDC_CHECK_dw,	},
		{	CONST_resId_pc6_qiTaDanWei,					CONST_str_otherDepart,	},
		{	CONST_resId_pc8_buMen,						CONST_IDC_CHECK_bm,	},
		{	CONST_resId_pc10_shiYongRen,				CONST_IDC_CHECK_syr,	},
		{	CONST_resId_pc12_jiQiLeiXing,				COSNT_IDC_jiQiLeiXing,	},
		{	CONST_resId_pc14_ziChanBianHao,				CONST_IDC_ziChanBianHao,	},
		{	CONST_resId_pc16_zhuYaoYongTu,				CONST_IDC_zhuYaoYongTu,	},
		{	CONST_resId_pc18_lianXiDianHua,				CONST_IDC_lianXiDianHua,	},
		{	CONST_resId_pc20_shiYongDiDian,				CONST_IDC_shiYongDiDian,	},
		{	CONST_resId_pc22_shiYongDiDian,				CONST_IDC_shiYongDiDian,	},
		{	CONST_resId_pc24_ziChanBianHao1,			CONST_IDC_ziChanBianHao1,	},
		{	CONST_resId_pc26_ziChanShuoMing1,			CONST_IDC_ziChanShuoMing1,	},
		{	CONST_resId_pc28_ziChanBianHao2,			CONST_IDC_ziChanBianHao2,	},
		{	CONST_resId_pc30_ziChanShuoMing2,			CONST_IDC_ziChanShuoMing2,	},
		//
		{	CONST_resId_STATIC_usrInfoZone,				CONST_IDC_STATIC_usrInfoZone,	},	
		{	CONST_resId_STATIC_pcName,					CONST_IDC_STATIC_pcName,	},
		{	CONST_resId_STATIC_ip,						CONST_IDC_STATIC_ip,	},
		{	CONST_resId_STATIC_osName,					CONST_IDC_STATIC_osName,	},
		{	CONST_resId_STATIC_servicePack,				_T(  "ServicePack:"  ),	},
		{	CONST_resId_STATIC_mac0,					_T(  "MAC0:"  ),	},
		{	CONST_resId_STATIC_mac1,					_T(  "MAC1:"  ),	},
		{	CONST_resId_STATIC_mac2,					_T(  "MAC2:"  ),	},
		{	CONST_resId_STATIC_ip0,						_T(  "IP0:"  ),	},
		{	CONST_resId_STATIC_ip1,						_T(  "IP1:"  ),	},
		{	CONST_resId_STATIC_ip2,						_T(  "IP2:"  ),	},
		//
		{	CONST_resId_STATIC_qwmVer,					CONST_IDC_STATIC_qwmVer,		},
		{	CONST_resId_STATIC_regTime,					CONST_IDC_STATIC_regTime,		},
		{	CONST_resId_STATIC_auditTime,				CONST_IDC_STATIC_auditTime,		},
		{	CONST_resId_STATIC_clientStartTime,			CONST_IDC_STATIC_clientStartTime,		},
		{	CONST_resId_STATIC_lastCommTime,			CONST_IDC_STATIC_lastCommTime,		},
		//
	{	IDD_prop_messenger,							CONST_IDD_prop_messenger,		},
		{	IDC_STATIC_staticMessengerId,				_T(  "Messenger ID:"  ),	},
	{	IDD_prop_imGrp,								CONST_IDD_prop_imGrp,			},
	{	IDD_imGrp,									CONST_IDD_imGrp,				},
	{	IDD_policy_imAuthCond,						CONST_IDD_policy_imAuthCond,			},
		{	CONST_resId_imAuthCond_hint,				CONST_IDC_imAuthCond_hint,				},
		{	IDC_CHECK_ucbUseMac,						_T(  "MAC"  ),				},
		{	IDC_CHECK_ucbUsePcName,						_T(  "PC Name"  ),			},	
		{	IDC_CHECK_ucbUseDomainName,					_T(  "Domain Name"  ),		},
		{	IDC_CHECK_ucbUseOsUsrName,					CONST_IDC_CHECK_ucbUseOsUsrName,		},
		{	IDC_CHECK_ucbUseMessengerName,				CONST_IDC_CHECK_ucbUseMessengerName,		},
		{	IDC_CHECK_ucbAutoVerification,				CONST_IDC_CHECK_ucbAutoVerification,		},
		{	IDC_CHECK_ucbNeedValidIpForDevice,			CONST_IDC_CHECK_ucbNeedValidIpForDevice,	},
		{	IDC_STATIC_qiShiIP,							CONST_IDC_STATIC_qiShiIP,	},
		{	IDC_STATIC_jieShuIP,						CONST_IDC_STATIC_jieShuIP,	},


	{	IDD_cfgCustomerService,						CONST_IDD_cfgCustomerService,	},
		{	IDC_STATIC_lang,							CONST_IDC_STATIC_lang,	},
		{	IDC_STATIC_category,						CONST_IDC_STATIC_category,	},


	{	IDD_prop_imTask,							CONST_IDD_prop_imTask,		},
		{	IDC_STATIC_staticType,						(  TCHAR  *  )CONST_str_leiXing  _T(  ":"  ),		},
		{	IDC_STATIC_staticImTaskStatus,				(  TCHAR  *  )CONST_str_zhuangTai  _T(  ":"  ),		},
		{	IDC_STATIC_staticSender,					CONST_str_senderDesc  _T(  ":"  ),			},
		{	IDC_STATIC_staticReceiver,					CONST_str_receiverDesc  _T(  ":"  ),		},
		{	IDC_STATIC_staticSendTime,					CONST_str_sendTime  _T(  ":"  ),			},
		{	IDC_STATIC_staticRecvTime,					CONST_str_recvTime  _T(  ":"  ),			},
		{	IDC_STATIC_staticSubject,					CONST_str_subject  _T(  ":"  ),				},
		{	IDC_STATIC_staticContent,					CONST_str_content  _T(  ":"  ),				},
	{	IDD_prop_imMsg,								CONST_IDD_prop_imMsg,		},

	//  {	CONST_resId_IDD_spProperties,				CONST_str_Properties,		},
	/*	{	CONST_resId_STATIC_type,					_T(  "ÀàÐÍ:"  ),		},
		{	CONST_resId_STATIC_name,					_T(  "Ãû³Æ:"  ),		},
		{	CONST_resId_STATIC_cusName,					_T(  "±ðÃû:"  ),		},
		{	CONST_resId_STATIC_des0,					_T(  "ËµÃ÷:"  ),		},
		{	CONST_resId_STATIC_langId,					_T(  "ÓïÑÔ:"  ),		},
		{	CONST_resId_STATIC_supportedOs,				_T(  "ÊÊÓÃµÄ²Ù×÷ÏµÍ³:"  ),		},
		{	CONST_resId_STATIC_url,						_T(  "¹©ÏÂÔØµÄURL:"  ),		},
	*/
	{	CONST_resId_IDD_qyExport,					CONST_IDD_qyExport,		},
		{	CONST_resId_RADIO_exportCurQuery,			CONST_IDC_RADIO_exportCurQuery,		},
		{	CONST_resId_RADIO_exportBakData,			CONST_IDC_RADIO_exportBakData,					},
		{	CONST_resId_RADIO_exportCfg,				CONST_IDC_RADIO_exportCfg,				},
		{	CONST_resId_STATIC_exportHint,				CONST_IDC_STATIC_exportHint,			},
		{	CONST_resId_RADIO_exportBhbCfg,				CONST_IDC_RADIO_exportBhbCfg,		},
		{	CONST_resId_RADIO_exportRegInfo,			CONST_IDC_RADIO_exportRegInfo,				},
		{	CONST_resId_RADIO_procDj,					CONST_IDC_RADIO_procDj,					},
		{	IDC_RADIO_procModuleKnowlege,				CONST_IDC_RADIO_procModuleKnowlege,					},
		{	IDC_RADIO_procRegistryKnowlege,				CONST_IDC_RADIO_procRegistryKnowlege,						},
		{	IDC_RADIO_procIpKnowledge,					CONST_IDC_RADIO_procIpKnowledge,						},
		{	IDC_RADIO_procPhoneGuest,					CONST_IDC_RADIO_procPhoneGuest,						},
		{	IDC_RADIO_procImMsg,						CONST_IDC_RADIO_procImMsg,								},
		{	IDC_RADIO_procImHisTask,					CONST_IDC_RADIO_procImHisTask,							},
	{	CONST_resId_IDD_qnmClearup,					CONST_IDD_qnmClearup,		},
		{	CONST_resId_STATIC_clearHint,				CONST_IDC_STATIC_clearHint,		},
		{	CONST_resId_RADIO_clearupScannedIp,			CONST_IDC_RADIO_clearupScannedIp,		},
		{	CONST_resId_RADIO_clearupEvent,				CONST_IDC_RADIO_clearupEvent,		},
	{	CONST_resId_IDD_pcAssetProperties,			CONST_str_Properties,		},			
		{	CONST_resId_STATIC_staticMac0,				_T(  "MAC:"  ),		},
		{	CONST_resId_STATIC_staticAssetType,			CONST_IDC_STATIC_staticAssetType,	},
		{	IDC_STATIC_staticName,						CONST_IDC_STATIC_cfgName,		},
		{	CONST_resId_STATIC_staticDes0,				CONST_IDC_STATIC_staticDes0,		},
		{	CONST_resId_STATIC_staticStartTime,			CONST_IDC_STATIC_staticStartTime,		},
		{	CONST_resId_STATIC_staticEndTime,			CONST_IDC_STATIC_staticEndTime,		},
	//  {	CONST_resId_IDD_editSp,						CONST_str_Edit,		},
		//  {	CONST_resId_STATIC_servicePack0,				_T(  "   Service Pack"  ),		},
		//  {	CONST_resId_STATIC_servicePack_win2003,				_T(  "Service Pack 1a"  ),		},
		//  {	CONST_resId_STATIC_servicePack_winXp,				_T(  "Service Pack 1a"  ),		},
		//  {	CONST_resId_STATIC_servicePack_win2000,				_T(  "Service Pack 1a"  ),		},
		//  {	CONST_resId_STATIC_servicePack_winNt,				_T(  "Service Pack 1a"  ),		},
	{	CONST_resId_IDD_qnmSearch,					CONST_str_Search,		},
		{	CONST_resId_STATIC_queryType,				CONST_IDC_STATIC_queryType,		},
	{	IDD_qnmEventSearch,							CONST_IDD_qnmEventSearch,		},
		{	IDC_STATIC_hint,						CONST_IDC_STATIC_hint,	},
		//  IDC_STATIC,		"ÆðÊ¼Ê±¼ä:"
		//  IDC_STATIC,		"½ØÖ¹Ê±¼ä:"
		{	IDC_STATIC_eventType,					CONST_IDC_STATIC_eventType,		},
	{	IDD_qnmPcAssetListSearch,					CONST_IDD_qnmPcAssetListSearch,		},
		{	IDC_CHECK_onlyLast,						CONST_IDC_CHECK_onlyLast,		},
		{	IDC_STATIC_deviceType,					CONST_IDC_STATIC_deviceType,		},
		{	IDC_STATIC_keySearch,					CONST_IDC_STATIC_keySearch,		},
	{	IDD_qnmPcListSearch,					CONST_IDD_qnmPcListSearch,		},
	{	IDD_qnmPcSpListSearch,						CONST_IDD_qnmPcSpListSearch,		},
	{	IDD_qnmCfgPcGrps,						CONST_IDD_qnmCfgPcGrps,		},
		{	CONST_resId_qnmCfgPcGrps_ADD,			CONST_str_Add,		},
		{	CONST_resId_qnmCfgPcGrps_MODIFY,		CONST_str_qyModify,		},
		{	CONST_resId_qnmCfgPcGrps_DEL,			CONST_str_Del,		},
		{	IDC_CHECK_bNotAllAllowed,				CONST_IDC_CHECK_bNotAllAllowed,		},
	{	IDD_qnmCfgAdvancedOptions,				CONST_IDD_qnmCfgAdvancedOptions,		},
		{	IDC_STATIC_dbTypeName,				CONST_IDC_STATIC_dbTypeName,					},			
		{	IDC_STATIC_dbServIp,				CONST_IDC_STATIC_dbServIp,						},		
		{	IDC_STATIC_dbName,					CONST_IDC_STATIC_dbName,				},		
		{	IDC_STATIC_uid,						CONST_IDC_STATIC_uid,				},
		{	IDC_STATIC_pwd,						CONST_IDC_STATIC_pwd,				},
		{	IDC_CHECK_default,					CONST_IDC_CHECK_default,				},
	{	IDD_prop_pcNetwork,					CONST_IDD_prop_pcNetwork,				},
		{	IDC_RADIO_ucbDhcpEnabled,			CONST_IDC_RADIO_ucbDhcpEnabled,				},		
		{	IDC_RADIO_staticIp,					CONST_IDC_RADIO_staticIp,				},		
		{	IDC_STATIC_staticDevIp,				CONST_IDC_STATIC_staticDevIp,				},		
		{	IDC_STATIC_staticIpMask,			CONST_IDC_STATIC_staticIpMask,				},		
		{	IDC_STATIC_staticGateway,			CONST_IDC_STATIC_staticGateway,				},		
		{	IDC_RADIO_autoDns,					CONST_IDC_RADIO_autoDns,				},		
		{	IDC_RADIO_staticDns,				CONST_IDC_RADIO_staticDns,				},		
		{	IDC_STATIC_staticFirstDns,			CONST_IDC_STATIC_staticFirstDns,				},		
		{	IDC_STATIC_pcNetworkPropType,		CONST_IDC_STATIC_pcNetworkPropType,				},		
		{	IDC_STATIC_staticSecondaryDns,		CONST_IDC_STATIC_staticSecondaryDns,				},		
	{	IDD_qnmCfgPcNetworkRule,			CONST_IDD_qnmCfgPcNetworkRule,				},		
	//
	{	IDD_prop_pcProxyCfg,					CONST_IDD_prop_pcProxyCfg,		},
		{	CONST_resId_STATIC_staticDw,					CONST_IDC_CHECK_dw,								},
		{	CONST_resId_STATIC_staticBm,					CONST_IDC_CHECK_bm,								},
		{	CONST_resId_STATIC_staticSyr,					CONST_IDC_CHECK_syr,								},
		{	CONST_resId_STATIC_staticIp,					_T(  "IP:"  ),									},
		{	CONST_resId_STATIC_staticType,					CONST_IDC_STATIC_staticType,					},
		{	CONST_resId_STATIC_dialSetting,					CONST_IDC_STATIC_dialSetting,					},
		{	CONST_resId_RADIO_ucbEnableAutodial,			CONST_IDC_RADIO_ucbEnableAutodial,			},
		{	CONST_resId_RADIO_ucbNoNetAutodial,				CONST_IDC_RADIO_ucbNoNetAutodial,				},
		{	CONST_resId_RADIO_defaultDial,					CONST_IDC_RADIO_defaultDial,					},
		{	CONST_resId_STATIC_lanSetting,					CONST_IDC_STATIC_lanSetting,					},
		{	CONST_resId_CHECK_autoDetect,					CONST_IDC_CHECK_autoDetect,					},
		{	IDC_CHECK_autoConfigUrl,						CONST_IDC_CHECK_autoConfigUrl,					},
		{	IDC_STATIC_autoConfigUrl,						CONST_IDC_STATIC_autoConfigUrl,					},
		{	CONST_resId_CHECK_enableProxy,					CONST_IDC_CHECK_enableProxy,					},
		{	CONST_resId_STATIC_staticIpAddress,				CONST_IDC_STATIC_staticIpAddress,				},
		{	CONST_resId_STATIC_staticPort,					CONST_IDC_STATIC_staticPort,					},
		{	CONST_resId_CHECK_proxyOverride,				CONST_IDC_CHECK_proxyOverride,				},
	{	IDD_qnmCfgPcProxyCfg,							CONST_IDD_qnmCfgPcProxyCfg,				},
	//
#if  0
	{	IDD_prop_pcComputer,							CONST_IDD_prop_pcComputer,				},
		{	IDC_STATIC_hint_activeComputerName,				CONST_IDC_STATIC_hint_activeComputerName,		},
		{	IDC_STATIC_newPcName,							CONST_IDC_STATIC_newPcName,				},
		{	IDC_CHECK_ucbAutoRestartIfChanged,				CONST_IDC_CHECK_ucbAutoRestartIfChanged,		},
#endif
	{	IDD_prop_windowsUpdatePolicy,					CONST_IDD_prop_windowsUpdatePolicy,			},
		{	IDC_STATIC_group_autoUpdate,					CONST_IDC_STATIC_group_autoUpdate,			},
//		
		{	IDC_STATIC_autoUpdate,								_T(  "[HLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\WindowsUpdate\\Auto Update]:"  ),	},
		{	IDC_STATIC_staticAUOptions_autoUpdate,				_T(  "AUOptions:"  ),	},
		{	IDC_STATIC_staticScheduledInstallDay_autoUpdate,	_T(  "ScheduledInstallDay:"  ),		},
		{	IDC_STATIC_staticScheduledInstallTime_autoUpdate,	_T(  "ScheduledInstallTime:"  ),	},
		//
		{	IDC_RADIO_ucbWSusPolicyExists,						CONST_str_shiYongWSus,		},
		{	CONST_resId_importWSusTmpl,							CONST_IDC_importWSusTmpl,		},
		{	IDC_STATIC_wsus,									_T(  "[HLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate]:"  ),  },
		{	IDC_STATIC_staticNoAutoUpdate,						_T(  "NoAutoUpdate:"  ),	},
		{	IDC_STATIC_staticAUOptions,							_T(  "AUOptions:"  ),		},
		{	IDC_STATIC_staticScheduledInstallDay,				_T(  "ScheduledInstallDay:"  ),				},
		{	IDC_STATIC_staticScheduledInstallTime,				_T(  "ScheduledInstallTime:"  ),				},
		{	IDC_STATIC_staticUseWUServer,						_T(  "UseWUServer:"  ),		},
		{	IDC_STATIC_staticWUServer,							_T(  "WUServer:"  ),		},
		{	IDC_STATIC_staticWUStatusServer,					_T(  "WUStatusServer:"  ),	},
		{	IDC_STATIC_staticRescheduleWaitTimeEnabled,			_T(  "RescheduleWaitTimeEnabled:"  ),		},
		{	IDC_STATIC_staticRescheduleWaitTime,				_T(  "RescheduleWaitTime:"  ),				},
		{	IDC_STATIC_staticDetectionFrequencyEnabled,			_T(  "DetectionFrequencyEnabled:"  ),		},
		{	IDC_STATIC_staticDetectionFrequency,				_T(  "DetectionFrequency:"  ),				},
		{	IDC_STATIC_staticNoAutoRebootWithLoggedOnUsers,		_T(  "NoAutoRebootWithLoggedOnUsers:"  ),	},
		{	IDC_STATIC_staticElevateNonAdmins,					_T(  "ElevateNonAdmins:"  ),					},
		{	IDC_STATIC_staticTargetGroupEnabled,				_T(  "TargetGroupEnabled:"  ),					},
		{	IDC_STATIC_staticTargetGroup,						_T(  "TargetGroup:"  ),							},
	{	IDD_qnmCfgWindowsUpdatePolicy,				CONST_IDD_qnmCfgWindowsUpdatePolicy,					},
		//
	{	CONST_resId_IDD_qnmCfgPcComputer,			CONST_IDD_qnmCfgPcComputer,		},
		{	CONST_resId_STATIC_leiXing,					CONST_str_leiXing,		},
		{	CONST_resId_STATIC_jiSuanJiMing,			CONST_str_jiSuanJiMing,		},
		{	CONST_resId_STATIC_zhuYi,			CONST_IDC_STATIC_zhuYi,					},
		{	CONST_resId_CHECK_ucbAutoRestartIfChanged,			CONST_IDC_CHECK_ucbAutoRestartIfChanged2,	},
	{	IDD_qnmCfgIpGrp,			CONST_IDD_qnmCfgIpGrp,							},
	{	IDD_qnmCfgUnchk,			CONST_IDD_qnmCfgUnchk,							},
		{	IDC_STATIC_unchkedHint,			CONST_IDC_STATIC_unchkedHint,						},
		{	IDC_STATIC_unchkedIp,			CONST_IDC_STATIC_unchkedIp,						},
		{	IDC_STATIC_tmpUnchkedIp,			CONST_IDC_STATIC_tmpUnchkedIp,					},
	{	IDD_qnmCfgUnchkedIpGrp,			CONST_IDD_qnmCfgUnchkedIpGrp,						},
	{	IDD_cfgSkippedMacs,			CONST_IDD_cfgSkippedMacs,							},
		{	CONST_resId_skippedMacsHint,			CONST_IDC_skippedMacsHint,				},


		//		
		{	IDC_STATIC_mac0,							_T(  "MAC0"  ),						},
		{	IDC_STATIC_mac1,							_T(  "MAC1"  ),						},
		{	IDC_STATIC_mac2,							_T(  "MAC2"  ),						},
		{	IDC_STATIC_mac3,							_T(  "MAC3"  ),						},
		{	IDC_STATIC_mac4,							_T(  "MAC4"  ),						},
	//
	{	IDD_cfgPcProcessRule,					CONST_IDD_cfgPcProcessRule,						},
		{	IDC_STATIC_processName,					CONST_IDC_STATIC_processName,						},
	{	IDD_qnmOtherMacInfo,					CONST_IDD_qnmOtherMacInfo,						},
	{	IDD_phoneNum,					CONST_IDD_phoneNum,							},
	{	IDD_cfgSwitchPolicyGrps,					CONST_IDD_cfgSwitchPolicyGrps,						},
		{	IDC_modifyDefSnmpPolicy,					CONST_IDC_modifyDefSnmpPolicy,						},
		{	IDC_STATIC_snmpPolicyHint,					CONST_IDC_STATIC_snmpPolicyHint,					},
	{	IDD_cfgSwitchPolicyGrp,					CONST_IDD_cfgSwitchPolicyGrp,						},
		{	IDC_STATIC_snmpVer,							CONST_IDC_STATIC_snmpVer,						},
		{	IDC_STATIC_getCommunity,					CONST_IDC_STATIC_getCommunity,						},
		{	IDC_STATIC_setCommunity,					CONST_IDC_STATIC_setCommunity,						},
		{	IDC_STATIC_usrName,							CONST_IDC_STATIC_usrName,						},
		{	IDC_STATIC_passwd,							CONST_IDC_STATIC_passwd,						},
#if  0
		{	IDC_BUTTON_option,							CONST_IDC_STATIC_option,						},
#endif
		{	IDC_STATIC_securityLevel,					CONST_IDC_STATIC_securityLevel,						},
		{	IDC_STATIC_grpName,							CONST_IDC_STATIC_grpName,						},
		{	IDC_STATIC_cfgSwitchPolicyGrpWarning,		CONST_IDC_STATIC_cfgSwitchPolicyGrpWarning,				},
	{	IDD_mgrSwitchPolicyGrps,				CONST_IDD_mgrSwitchPolicyGrps,						},
	{	IDD_addSwitchToGrp,						CONST_IDD_addSwitchToGrp,						},
		{	IDC_STATIC_ipAddress1,						CONST_IDC_STATIC_ipAddress1,						},
		{	IDC_STATIC_cusName,							CONST_ID_STATIC_bieMing,		},
		{	IDC_STATIC_addSwitchToGrpHint,				CONST_IDC_STATIC_addSwitchToGrpHint,				},
	{	IDD_qnmEditMacInfo,						CONST_IDD_qnmEditMacInfo,					},
		{	IDC_CHECK_ucbDirectConn,					CONST_IDC_CHECK_ucbDirectConn,					},
		{	IDC_STATIC_devDes0,							CONST_IDC_STATIC_devDes0,					},
		{	IDC_qnmEditMacInfo_switch,					CONST_IDC_qnmEditMacInfo_switch,				},
		{	IDC_qnmEditMacInfo_mac,						CONST_IDC_qnmEditMacInfo_mac,					},
		{	IDC_qnmEditMacInfo_switchPort,				CONST_IDC_qnmEditMacInfo_switchPort,				},
		{	IDC_qnmEditMacInfo_auditTime,				CONST_IDC_qnmEditMacInfo_auditTime,				},
	{	IDD_qnmSnmpObjProperties,				CONST_IDD_qnmSnmpObjProperties,					},
		{	IDC_qnmSnmpObjProperties_productName,		CONST_IDC_qnmSnmpObjProperties_productName,			},
		{	IDC_qnmSnmpObjProperties_cusName,			CONST_ID_STATIC_bieMing,		},
		{	IDC_qnmSnmpObjProperties_IP,				_T(  "IP:"  ),		},
		{	IDC_qnmSnmpObjProperties_place,				CONST_IDC_shiYongDiDian,		},
		{	IDC_qnmSnmpObjProperties_numPorts,			CONST_IDC_qnmSnmpObjProperties_numPorts,		},
		{	IDC_qnmSnmpObjProperties_sysDescr,			CONST_IDC_STATIC_staticDes0,		},
		{	IDC_STATIC_prePortIfDescr,				CONST_IDC_STATIC_prePortIfDescr,					},
		{	IDC_STATIC_prePortIfIndex,				CONST_IDC_STATIC_prePortIfIndex,					},
		{	IDC_STATIC_preICpsGlobalMaxSecureAddress,				CONST_IDC_STATIC_preICpsGlobalMaxSecureAddress,				},
		{	IDC_STATIC_preICpsGlobalTotalSecureAddress,				CONST_IDC_STATIC_preICpsGlobalTotalSecureAddress,			},
	{	IDD_num,				CONST_IDD_num,								},
		{	IDC_num_hint,				CONST_IDC_num_hint,							},
	{	IDC_mac_hint,				CONST_IDC_mac_hint,							},
	{	IDD_qnmSnmpObjPortProperties,				CONST_IDD_qnmSnmpObjPortProperties,					},
		{	IDC_STATIC_prePortIfDescr,				CONST_IDC_STATIC_prePortIfDescr,					},
		{	IDC_STATIC_prePortIfIndex,				CONST_IDC_STATIC_prePortIfIndex,					},
		{	IDC_STATIC_preVlanId,				CONST_IDC_STATIC_preVlanId,						},
		{	IDC_STATIC_preICpsIfMaxSecureMacAddr,				CONST_IDC_STATIC_preICpsIfMaxSecureMacAddr,				},
		{	IDC_STATIC_preICpsIfSecureMacAddrCount,				CONST_IDC_STATIC_preICpsIfSecureMacAddrCount,				},
		{	IDC_STATIC_preICpsIfPortSecurityStatus,				CONST_IDC_STATIC_preICpsIfPortSecurityStatus,				},
		{	IDC_STATIC_preICpsIfViolationAction,				CONST_IDC_STATIC_preICpsIfViolationAction,				},
		{	IDC_STATIC_iCpsIfViolationAction,				CONST_IDC_STATIC_iCpsIfViolationAction,					},
	{	IDD_cfgSwitchDefaultPolicyGrp,				CONST_IDD_cfgSwitchDefaultPolicyGrp,					},
		{	IDC_default_snmpVer,				CONST_IDC_default_snmpVer,						},
		{	IDC_default_getCommunity,				CONST_IDC_default_getCommunity,						},
		{	IDC_default_setCommunity,				CONST_IDC_default_setCommunity,						},
		{	IDC_default_cfgSwitchPolicyGrpWarning,				CONST_IDC_default_cfgSwitchPolicyGrpWarning,				},
		{	IDC_cfgSwitchDefaultPolicyGrp_hint,				CONST_IDC_cfgSwitchDefaultPolicyGrp_hint,				},

	{	CONST_resId_IDD_editSwitchInfo_only,				CONST_IDD_editSwitchInfo_only,						},
	{	CONST_resId_IDD_editSwitchInfo,				CONST_IDD_editSwitchInfo,						},
	{	IDD_qnmCfgSnmpObjRule,				CONST_IDD_qnmCfgSnmpObjRule,						},
		{	IDC_STATIC_staticRuleType,				CONST_IDC_STATIC_staticRuleType,					},
		{	IDC_STATIC_staticProductName,				CONST_IDC_STATIC_staticProductName,					},
		{	IDC_CHECK_ibDirectConn,				CONST_IDC_CHECK_ibDirectConn,						},
		{	IDC_STATIC_portIfDescrHint,					CONST_IDC_STATIC_staticPort,		},
		{	IDC_STATIC_ibDownPortIfMacChanged,					CONST_IDC_STATIC_ibDownPortIfMacChanged,		},
		{	IDC_STATIC_ibDownPortIfMacChangePort,					CONST_IDC_STATIC_ibDownPortIfMacChangePort,		},
		{	IDC_STATIC_ibNotLogIfMacChanged,					CONST_IDC_STATIC_ibNotLogIfMacChanged,			},
		{	IDC_STATIC_warnPercentOfBand,					CONST_IDC_STATIC_warnPercentOfBand,			},
		{	IDC_STATIC_warnPercentOfBandUnit,			_T(  "%"  ),							},
		{	IDC_STATIC_ibDownPortIfWarnSpeed,					CONST_IDC_STATIC_ibDownPortIfWarnSpeed,			},

	{	IDD_cfgModuleKnowlege,				CONST_IDD_cfgModuleKnowlege,					},
		{	IDC_STATIC_cfgModuleKnowlegeHint,					CONST_IDC_STATIC_cfgModuleKnowlegeHint,			},
		{	IDC_STATIC_staticFileName,					CONST_IDC_STATIC_staticFileName,			},
		{	IDC_STATIC_staticCmdLine,					CONST_IDC_STATIC_staticCmdLine,				},
		{	IDC_CHECK_bCmdLineGiven,					CONST_IDC_CHECK_bCmdLineGiven,				},
		{	IDC_STATIC_name,							CONST_IDC_STATIC_cfgName,					},
		{	IDC_STATIC_des0,							CONST_IDC_STATIC_staticDes0,					},
		{	IDC_STATIC_company,					CONST_IDC_STATIC_company,				},
		{	IDC_STATIC_product,					CONST_IDC_STATIC_product,				},
		{	IDC_STATIC_commonErr,					CONST_IDC_STATIC_commonErr,				},
		{	IDC_STATIC_memInfo,					CONST_IDC_STATIC_memInfo,				},
		{	IDC_STATIC_securityLevel,					CONST_IDC_STATIC_securityLevel,				},
		{	IDC_CHECK_ucbSys,					CONST_IDC_CHECK_ucbSys,					},
		{	IDC_CHECK_ucbDaemon,					CONST_IDC_CHECK_ucbDaemon,				},
		{	IDC_CHECK_ucbUseNet,					CONST_IDC_CHECK_ucbUseNet,				},
		{	IDC_CHECK_ucbHardware,					CONST_IDC_CHECK_ucbHardware,				},
		{	IDC_CHECK_ucbSpy,					CONST_IDC_CHECK_ucbSpy,					},
		{	IDC_CHECK_ucbAdvertisement,					CONST_IDC_CHECK_ucbAdvertisement,			},
		{	IDC_CHECK_ucbVirus,					CONST_IDC_CHECK_ucbVirus,				},
		{	IDC_CHECK_ucbBackDoor,					CONST_IDC_CHECK_ucbBackDoor,				},
		{	IDC_STATIC_providerName,					CONST_IDC_STATIC_providerName,				},
		{	IDC_STATIC_providerAddr,					CONST_IDC_STATIC_providerAddr,				},
		{	IDC_STATIC_providerTime,					CONST_IDC_STATIC_providerTime,				},
		{	IDC_STATIC_staticAuditTime,					CONST_IDC_STATIC_staticAuditTime,			},
		{	IDOK,										CONST_str_OK,						},
		{	IDCANCEL,									CONST_str_CANCEL,						},
//
	{	IDD_prop_moduleKnowlege,						CONST_IDD_prop_moduleKnowlege,			},
	{	IDD_qnmPcProcessModuleListSearch,						CONST_IDD_qnmPcProcessModuleListSearch,		},
		{	IDC_STATIC_qnmPcProcessModuleListSearch,						CONST_IDC_STATIC_qnmPcProcessModuleListSearch,	},
	{	IDD_moduleKnowlegeOptions,						CONST_IDD_moduleKnowlegeOptions,		},
		{	IDC_RADIO_unAudited,						CONST_IDC_RADIO_unAudited,			},
		{	IDC_RADIO_audited,						CONST_IDC_RADIO_audited,			},
		{	CONST_resId_unAudited_pcRegistry,						CONST_IDC_unAudited_pcRegistry,			},
		{	CONST_resId_audited_pcRegistry,						CONST_IDC_audited_pcRegistry,			},
//
	{	IDD_cfgPcRegistryKnowledge,						CONST_IDD_cfgPcRegistryKnowledge,		},
		{	IDC_STATIC_cfgPcRegistryKnowlegeHint,				_T(  ""  ),								},
		{	IDC_STATIC_iRootKey,						CONST_IDC_STATIC_iRootKey2,			},
		{	IDC_STATIC_subKey,						CONST_IDC_STATIC_subKey2,			},
		{	IDC_STATIC_cfgName,						CONST_IDC_STATIC_cfgName,						},
		{	IDC_STATIC_suggestedVal,						CONST_IDC_STATIC_suggestedVal,			},
//
	{	IDD_prop_pcRegistryKnowledge,						CONST_IDD_prop_pcRegistryKnowledge,		},
		{	CONST_resId_absolutePcRegistry,						CONST_IDC_absolutePcRegistry,			},
		{	CONST_resId_editPcRegistryKnowledge,						CONST_IDC_editPcRegistryKnowledge,		},
		{	CONST_resId_prop_pcRegistryKnowledge,						CONST_IDC_prop_pcRegistryKnowledge,		},
	{	IDD_selectDsn,						CONST_IDD_selectDsn,				},
	{	IDD_imMsgSearch,						CONST_IDD_imMsgSearch,				},
		{	IDC_STATIC_staticTalker,						CONST_IDC_STATIC_staticTalker,			},
		{	IDC_STATIC_staticId,						_T(  "ID:"  ),						},
		{	IDC_STATIC_content,						CONST_IDC_STATIC_content,			},
//
	{	IDD_wwwQmCfg,						CONST_IDD_wwwQmCfg,				},
		{	IDC_STATIC_staticMessengerId,				_T(  "Messenger ID:"  ),  },
		{	IDC_CHECK_ucbPublic,						CONST_IDC_CHECK_ucbPublic,			},
		{	IDC_CHECK_ucbDefault,						CONST_IDC_CHECK_ucbDefault,			},
		{	CONST_resId_ucbDefaultSmContact,						CONST_IDC_ucbDefaultSmContact,			},
		//
		{	IDC_STATIC_grpDisplayName,					CONST_str_grpDisplayName,				},
		{	IDC_STATIC_displayName,						CONST_str_displayName,			},
		{	IDC_CHECK_ucbImSwitchable,						CONST_IDC_CHECK_ucbImSwitchable,		},
		{	IDC_STATIC_wAdvertisement,						CONST_IDC_STATIC_wAdvertisement,		},
	{	IDD_cfgIpKnowledge,						CONST_IDD_cfgIpKnowledge,			},
		{	IDC_STATIC_startIp,							CONST_str_startIp  _T(  ":"  ),			},
		{	IDC_STATIC_endIp,							CONST_str_endIp  _T(  ":"  ),			},
		{	IDC_STATIC_wLocation,						CONST_str_wLocation  _T(  ":"  ),		},
		{	IDC_STATIC_iWeight,							CONST_str_iWeight  _T(  ":"  ),			},
//
	{	IDD_prop_ipKnowledge,						CONST_IDD_prop_ipKnowledge,			},
	{	IDD_cfgPhoneMessenger,						CONST_str_peiZhi,								},
		{	IDC_STATIC_dw,								CONST_str_danWei,							},
		{	IDC_STATIC_bm,								CONST_str_buMen,			},
		{	IDC_STATIC_syr,								CONST_str_shiYongRen,		},
		{	IDC_STATIC_countryCode,						CONST_str_countryCode,		},
		{	IDC_STATIC_phoneNo,							CONST_str_phoneNo,		},

	{	IDD_cfgGsmModem,							CONST_str_peiZhi,			},
		{	IDC_STATIC_idStr_vDev,						CONST_IDC_STATIC_idStr_vDev,			},
		{	IDC_STATIC_wDevIdStr,						CONST_IDC_STATIC_wDevIdStr,			},
		{	IDC_CHECK_ucbDefaultSmServer,				CONST_IDC_CHECK_ucbDefaultSmServer,		},
		{	CONST_resId_smContactMsgrId,			CONST_IDC_smContactMsgrId,			},
		{	CONST_resId_verifyPhoneListHint,			CONST_IDC_verifyPhoneListHint,			},
#if  0
	{	IDD_talk,									_T(  "Talk"  ),					},
		{	IDC_STATIC_instantStatus,					CONST_IDC_STATIC_instantStatus,			},
		{	IDC_BUTTON_font,							_T(  "A"  ),				},
		{	IDC_STATIC_peerName,						CONST_IDC_STATIC_peerName,			},		
		{	IDC_STATIC_peerDesc,						_T(  ""  ),					},
		{	CONST_resId_staticToPaths,					CONST_IDC_staticToPaths,			},
		{	CONST_resId_localToPaths,					CONST_IDC_localToPaths,				},
#endif
		// 
	{	IDD_desktopsMon,							CONST_IDD_desktopsMon,							},

	{	IDD_messenger,									CONST_IDD_messenger,		},
		{	IDC_STATIC_hint1,						CONST_IDC_STATIC_hint1,	},	
		{	IDC_STATIC_messengerName,					CONST_IDC_STATIC_messengerName,		},
		{	IDC_STATIC_passwd0,							CONST_IDC_STATIC_passwd0,	},	
		{	IDC_STATIC_passwd1,							CONST_IDC_STATIC_passwd1,	},	
	{	IDD_status_daemon,							CONST_IDD_status_daemon,		},
#if 0
		{	IDD_status_cli,								CONST_IDD_status_cli,		},
#endif



	//
	{	ID_qyCopy,									CONST_ID_qyCopy,								},
	{	ID_qyPaste,									CONST_ID_qyPaste,								},
	//
	{	CONST_resId_iRootKey,						CONST_str_genJian,		},
	{	CONST_resId_subKey,							CONST_str_ziJian,		},
	{	CONST_resId_cfgName,						CONST_str_mingChen,		},
	//
	{	CONST_resId_startIp,						CONST_str_startIp,	},
	{	CONST_resId_endIp,							CONST_str_endIp,	},
	//
	{	CONST_resId_misServName,					CONST_str_servName,	},
	{	CONST_resId_uiDevType,						CONST_str_leiXing,	},
	{	CONST_resId_wDevIdStr,						CONST_str_phoneNo,	},

	//
	{	CONST_resId_status,							CONST_str_zhuangTai,		},

	//
	{	CONST_resId_pcMgrClass,						CONST_str_leiBie,			},
	{	CONST_resId_pcUsrInfo,						CONST_IDC_pcUsrInfo,		},
	{	CONST_resId_pcOpNode,						CONST_str_caozuo,			},
	{	CONST_resId_pcOsClass,						CONST_str_caoZuoXiTong,		},
	//
	{	CONST_resId_pcOpNode_desc,					CONST_IDC_pcOpNode_desc,					},

	//  2008/12/14
	{	CONST_resId_objIdStr_unRegGrp,				CONST_objIdStr_unRegGrp,	},	//			_T(  "(Î´×¢²áÓÃ»§)"  )
	{	CONST_resId_objIdStr_othersGrp,				CONST_objIdStr_othersGrp,	},	//			_T(  "(ÆäËûÓÃ»§)"  )
	{	CONST_resId_objIdStr_me,					CONST_objIdStr_me,			},	//			_T(  "ÎÒ"  )
	{	CONST_resId_objIdStr_imGrps,				CONST_objIdStr_imGrps,		},	//			_T(  "×é¼¯ºÏ"  )


	//
	{	CONST_resId_statIpScan,						CONST_IDC_statIpScan,			},
	{	CONST_resId_statPcInfo,						CONST_IDC_statPcInfo,			},
	{	CONST_resId_statUsrInfo,					CONST_IDC_statUsrInfo,	},
	{	CONST_resId_statGeneral,					CONST_IDC_statGeneral,		},
	{	CONST_resId_statOthers,						CONST_IDC_statOthers,			},
	//
	{	CONST_resId_statMessengerInfo,				CONST_IDC_statMessengerInfo,	},


	//	³ÌÐòÌâÍ·£¬2005/11/16
	{	CONST_resId_sys_bha,						CONST_sys_bha,			},
	{	CONST_resId_sys_bhb_intraMon,						CONST_sys_bhb_intraMon,	},
	{	CONST_resId_sys_bhb_interMon,						CONST_sys_bhb_interMon,	},
	{	CONST_resId_sys_netMc2,						CONST_sys_netMc2,			},
	{	CONST_resId_sys_nms,						CONST_sys_nms,			},
	{	CONST_resId_sys_secChk,						CONST_sys_secChk,			},
	{	CONST_resId_sys_assetMgr,					CONST_sys_assetMgr,			},
	{	CONST_resId_sys_isCli_default,				_T(  "Qycx Messenger"  ),									},
	{	CONST_resId_sys_isCli_ts,					_T(  "Qycx Messenger"  ),									},
	{	CONST_resId_sys_isMgr,						CONST_sys_misMgr,			},

	//  ÔÓÏî
	//  2008/12/15
	{	CONST_resId_network,						CONST_str_network,							},
	{	CONST_resId_baseSystem,						CONST_str_baseSystem,						},
	{	CONST_resId_qyMessengerView,				CONST_str_qyMessengerView,					},		//_T(  "ÁªÏµÈËÊ÷×´Í¼"  )
	{	CONST_resId_qyMessengerList,				CONST_str_qyMessengerList,					},
	{	CONST_resId_qyMessengerAuthList,			CONST_str_qyMessengerAuthList,				},
	{	CONST_resId_qyImAmList,						CONST_str_qyImAmList,						},
	{	CONST_resId_qyPhoneMessengerList,			CONST_str_qyPhoneMessengerList,				},
	{	CONST_resId_qyPcUsrList2,					CONST_str_qyPcUsrList2,						},
	{	CONST_resId_qyMessengerAuthList_needAudited,CONST_str_qyMessengerAuthList_needAudited,	},	
	{	CONST_resId_qyImGrpAuthList,				CONST_str_qyImGrpAuthList,					},
	{	CONST_resId_qyImGrpList,					CONST_str_qyImGrpList,						},
	{	CONST_resId_qyImGrpMemList,					CONST_str_qyImGrpMemList,					},
	{	CONST_resId_customerServiceList,			CONST_str_customerServiceList,			},
	{	CONST_resId_wwwQmCfgList,					CONST_str_wwwQmCfgList,						},
	{	CONST_resId_sharedDynBmpList,				CONST_str_sharedDynBmpList,					},
	{	CONST_resId_sharedDynBmpRuleList,			CONST_str_sharedDynBmpRuleList,					},
	{	CONST_resId_procIpKnowledge,				CONST_str_procIpKnowledge,					},
	{	CONST_resId_qyGsmModemList,					CONST_str_qyGsmModemList,					},
	{	CONST_resId_qySmContactList,				CONST_str_qySmContactList,					},
	{	CONST_resId_qyPhoneGuestList,				CONST_str_qyPhoneGuestList,					},
	{	CONST_resId_qyClientList,					CONST_str_qyClientList,						},
	{	CONST_resId_loaded,							CONST_str_loaded,							},
	{	CONST_resId_dataSourceList,					CONST_str_dataSourceList,					},
	{	CONST_resId_loadDataSourceFailed,			CONST_str_loadDataSourceFailed,				},
	{	CONST_resId_unloadDataSourceFailed,			CONST_str_unloadDataSourceFailed,			},
	//
	{	CONST_resId_selectDbFile,					CONST_str_selectDbFile,						},	
	{	CONST_resId_cannotEmpty,					CONST_str_cannotEmpty,						},
	{	CONST_resId_systemTypeErr,					CONST_str_systemTypeErr,					},
	{	CONST_resId_systemNameExisted,				CONST_str_systemNameExisted,				},
	{	CONST_resId_addSystemErr,					CONST_str_addSystemErr,						},
	{	CONST_resId_maximumNumberOfObject,			CONST_str_maximumNumberOfObject,			},
	{	CONST_resId_systemCfgErr,					CONST_str_systemCfgErr,						},
	{	CONST_resId_databaseformat,					CONST_str_databaseformat,					},
	{	CONST_resId_cannotModifyIfLoaded,			CONST_str_cannotModifyIfLoaded,				},
	{	CONST_resId_cannotDeleteIfLoaded,			CONST_str_cannotDeleteIfLoaded,				},
	{	CONST_resId_askIfDelete,					CONST_str_askIfDelete,						},
	//
	{	CONST_resId_qyPcList,						CONST_str_qyPcList,							},
	{	CONST_resId_qyPcView,						CONST_str_qyPcView,							},
	//
	{	CONST_resId_qyAssetsView,					CONST_str_qyAssetsView,						},
	//
	{	CONST_resId_qyRealTimeTaskList,				CONST_str_qyRealTimeTaskList,				},
	{	CONST_resId_sharingObjectList,				CONST_str_sharingObjectList,				},
	{	CONST_resId_playerList,						CONST_str_playerList,					},
	{	CONST_resId_qyTaskList,						CONST_str_qyTaskList,						},
	{	CONST_resId_qyTaskHisList,					CONST_str_qyTaskHisList,					},
	{	CONST_resId_msgList,						CONST_str_msgList,							},
	{	CONST_resId_qyMsgToday,						CONST_str_qyMsgToday,						},
	{	CONST_resId_today,							CONST_str_today,							},
	{	CONST_resId_logList,						CONST_str_logList,							},
	{	CONST_resId_unfinished,						CONST_str_unfinished,						},
	{	CONST_resId_dialUpLogList,					CONST_str_dialUpLogList,					},
	//
	{	CONST_resId_statIpScanList,					CONST_str_statIpScanList,					},
	{	CONST_resId_statPcInfoList,					CONST_str_statPcInfoList,					},
	{	CONST_resId_statUsrInfoList,				CONST_str_statUsrInfoList,					},
	{	CONST_resId_statGeneralList,				CONST_str_statGeneralList,					},
	{	CONST_resId_statOthersList,					CONST_str_statOthersList,					},
	{	CONST_resId_statMessengerInfoList,			CONST_str_statMessengerInfoList,			},
	//
	{	CONST_resId_statCondition,					CONST_str_statCondition,					},
	{	CONST_resId_askForContentOfStat,			CONST_str_askForContentOfStat,				},
	{	CONST_resId_ipCount,						CONST_str_ipCount,							},
	{	CONST_resId_pcCount,						CONST_str_pcCount,							},
	{	CONST_resId_computer,						CONST_str_computer,							},
	{	CONST_resId_otherOs,						CONST_str_otherOs,							},
	{	CONST_resId_networkCard,					CONST_str_networkCard,						},
	{	CONST_resId_multiNetworkCard,				CONST_str_multiNetworkCard,					},
	{	CONST_resId_userCount,						CONST_str_userCount,						},

	//  import
	{	CONST_resId_selectContentOfImport,			CONST_str_selectContentOfImport,			},
	{	CONST_resId_importBakData,					CONST_str_importBakData,					},
	{	CONST_resId_importRegInfo,					CONST_str_importRegInfo,					},
	{	CONST_resId_importBhbInfo,					CONST_str_importBhbInfo,					},
	{	CONST_resId_selectFilenameFormat,			CONST_str_selectFilenameFormat,				},
	{	CONST_resId_qyBakFileFormat,				CONST_str_qyBakFileFormat,					},
	{	CONST_resId_qyBhbBakFileFormat,				CONST_str_qyBhbBakFileFormat,				},
	{	CONST_resId_selectFolder,					CONST_str_selectFolder,						},
	{	CONST_resId_importOk,						CONST_str_importOk,							},
	{	CONST_resId_importWizard,					CONST_str_importWizard,						},
	{	CONST_resId_exportWizard,					CONST_str_exportWizard,						},
	{	CONST_resId_selectExportPcSecChkFolder,		CONST_str_selectExportPcSecChkFolder,		},
	{	CONST_resId_exportOk,						CONST_str_exportOk,							},
	{	CONST_resId_exportFailed,					CONST_str_exportFailed,						},
	{	CONST_resId_emptyWizard,					CONST_str_emptyWizard,						},
	{	CONST_resId_fileFormat,						CONST_str_fileFormat,						},
	{	CONST_resId_timeErr,						CONST_str_timeErr,							},
	{	CONST_resId_timeErr2,						CONST_str_timeErr2,							},
	{	CONST_resId_clearVerify,					CONST_str_clearVerify,						},
	{	CONST_resId_clearBhbVerify,					CONST_str_clearBhbVerify,					},
	//  mainfrm
	{	CONST_resId_pathErr,						CONST_str_pathErr,							},
	{	CONST_resId_current,						CONST_str_current,							},
	{	CONST_resId_history,						CONST_str_history,							},
	{	CONST_resId_paramErrMakeClientFailed,		CONST_str_paramErrMakeClientFailed,			},
	{	CONST_resId_folderErrMakeClientFailed,		CONST_str_folderErrMakeClientFailed,		},
	{	CONST_resId_makeClientOk,					CONST_str_makeClientOk,						},
	{	CONST_resId_makeClientFailed,				CONST_str_makeClientFailed,					},
	{	CONST_resId_stopDialupDetectVerify,			CONST_str_stopDialupDetectVerify,			},
	{	CONST_resId_cannotOpenRegistry,				CONST_str_cannotOpenRegistry,				},
	{	CONST_resId_err,							CONST_str_err,								},
	{	CONST_resId_writeRegistryFailed,			CONST_str_writeRegistryFailed,				},
	{	CONST_resId_stopServiceWarning,				CONST_str_stopServiceWarning,				},
	{	CONST_resId_qyStopIpScan,					CONST_str_qyStopIpScan,						},
	{	CONST_resId_qyStartIpScan,					CONST_str_qyStartIpScan,					},
	{	CONST_resId_qyStopRegScan,					CONST_str_qyStopRegScan,					},
	{	CONST_resId_qyStartRegScan,					CONST_str_qyStartRegScan,					},
	{	CONST_resId_stopUpdating,					CONST_str_stopUpdating,						},
	{	CONST_resId_startUpdating,					CONST_str_startUpdating,					},
	//	qyMcMainProc1.cpp
	{	CONST_resId_NoPrivilegesToOpenPcList,		CONST_str_NoPrivilegesToOpenPcList,			},
	{	CONST_resId_warning,						CONST_str_warning,							},
	{	CONST_resId_searchReg,						CONST_str_searchReg,						},
	{	CONST_resId_searchRegProm,					CONST_str_searchRegProm,					},
	{	CONST_resId_searchIp,						CONST_str_searchIp,							},
	{	CONST_resId_chaXun,							CONST_str_chaXun,							},
	{	CONST_resId_theOsIs,						CONST_str_theOsIs,							},
	{	CONST_resId_thePatchIs,						CONST_str_thePatchIs,						},
	{	CONST_resId_belongToPc,						CONST_str_belongToPc,						},	
	{	CONST_resId_searchResultBelongTo,			CONST_str_searchResultBelongTo,				},
	{	CONST_resId_port,							CONST_str_port,								},
	{	CONST_resId_belongToUnknownDevice,			CONST_str_belongToUnknownDevice,			},
	//	{	CONST_resId_resultBelongto,					CONST_str_resultBelongto,					},
	{	CONST_resId_searchOfResult,					CONST_str_searchOfResult,					},
	//	{	CONST_resId_searchMac,						CONST_str_searchMac,						},
	{	CONST_resId_connection,						CONST_str_connection,						},
	//	{	CONST_resId_resultOfPort,					CONST_str_resultOfPort,						},
	{	CONST_resId_searchResult,					CONST_str_searchResult,						},
	{	CONST_resId_daysCannotBeFound,				CONST_str_daysCannotBeFound,				},
	{	CONST_resId_communicationStatus,			CONST_str_communicationStatus,				},
	{	CONST_resId_communicationStatusWithFilters,	CONST_str_communicationStatusWithFilters,	},
	//
	{	CONST_resId_patchList,						CONST_str_patchList,						},
	{	CONST_resId_userInfoList,					CONST_str_userInfoList,						},
	{	CONST_resId_qyPcUsrInTab1List,				CONST_str_qyPcUsrInTab1List,				},
	//
	{	CONST_resId_qyNetworkView,					CONST_str_qyNetworkView,					},
	{	CONST_resId_qyConnectionView,				CONST_str_qyConnectionView,					},
	{	CONST_resId_qyNetworkSpeedView,				CONST_str_qyNetworkSpeedView,				},
	{	CONST_resId_snmpObjRuleList,				CONST_str_snmpObjRuleList,					},
	{	CONST_resId_conflictConnList,				CONST_str_conflictConnList,					},
	{	CONST_resId_directConnList,					CONST_str_directConnList,					},
	{	CONST_resId_connDevice,						CONST_str_connDevice,						},
	{	CONST_resId_searchList,						CONST_str_searchList,						},
	{	CONST_resId_qySearch,						CONST_str_qySearch,							},
	{	CONST_resId_askIfPortDown,					CONST_str_askIfPortDown,					},
	{	CONST_resId_cmdErr,							CONST_str_cmdErr,							},
	{	CONST_resId_cmdOk,							CONST_str_cmdOk,							},
	{	CONST_resId_tryAgainLater,					CONST_str_tryAgainLater,					},
	{	CONST_resId_ifDeleteMac,					CONST_str_ifDeleteMac,						},
	{	CONST_resId_ifDeleteDevice,					CONST_str_ifDeleteDevice,					},
	//
	{	CONST_resId_all,							CONST_str_all,								},
	{	CONST_resId_none,							CONST_str_none,								},
	{	CONST_resId_fieldCannotSame,				CONST_str_fieldCannotSame,					},
	{	CONST_resId_qnmHint_startIp0,				CONST_qnmHint_startIp0,						},
	{	CONST_resId_qnmHint_endIpLtStartIp,			CONST_qnmHint_endIpLtStartIp,				},
	{	CONST_resId_ifDeleteNetworkSegment,			CONST_str_ifDeleteNetworkSegment,			},
	{	CONST_resId_ifDeleteNetworkSegmentSuffix,	CONST_str_ifDeleteNetworkSegmentSuffix,		},
	{	CONST_resId_ifModifyDefaultSnmpPolicy,		CONST_str_ifModifyDefaultSnmpPolicy,		},
	{	CONST_resId_hintOfConfigSnmpFirst,			CONST_str_hintOfConfigSnmpFirst,			},
	{	CONST_resId_dbErrorResultCannotDelete,		CONST_str_dbErrorResultCannotDelete,		},
	{	CONST_resId_theMeaningOfCfgSnmpGrpPolicy,	CONST_str_theMeaningOfCfgSnmpGrpPolicy,		},
	{	CONST_resId_defaultPolicy,					CONST_str_defaultPolicy,					},
	{	CONST_resId_onlyReadCommunity,				CONST_str_onlyReadCommunity,				},
	{	CONST_resId_writeCommunity,					CONST_str_writeCommunity,					},
	//
	{	CONST_resId_grpNameCannotEmpty,				CONST_str_grpNameCannotEmpty,				},
	{	CONST_resId_messengerNameCannotEmpty,		CONST_str_messengerNameCannotEmpty,			},
	{	CONST_resId_passwdCannotEmpty,				CONST_str_passwdCannotEmpty,				},
	{	CONST_resId_passwdNotConfirmed,				CONST_str_passwdNotConfirmed,				},
	{	CONST_resId_nameExists,						CONST_str_nameExists,						},
	//
	{	CONST_resId_intervalBetween,				CONST_str_intervalBetween,					},
	{	CONST_resId_minuteAnd,						CONST_str_minuteAnd,						},
	{	CONST_resId_uptoMinute,						CONST_str_uptoMinute,						},
	{	CONST_resId_concurrentBetween,				CONST_str_concurrentBetween,				},
	{	CONST_resId_and,							CONST_str_and,								},
	{	CONST_resId_upto,							CONST_str_upto,								},
	{	CONST_resId_nMaxConns,						CONST_str_nMaxConns,						},
	{	CONST_resId_ipWrong,						CONST_str_ipWrong,							},
	{	CONST_resId_default_qrtTitle,				CONST_default_qrtTitle,						},
	{	CONST_resId_default_qrtHint,				CONST_default_qrtHint,						},
	//
	{	CONST_resId_afterStandard,					CONST_str_afterStandard,					},
	{	CONST_resId_cannotBeEmpty,					CONST_str_cannotBeEmpty,					},
	{	CONST_resId_ifStandard,						CONST_str_ifStandard,						},
	{	CONST_resId_standardFinished,				CONST_str_standardFinished,					},
	{	CONST_resId_standardFinished,				CONST_str_standardFinished,					},
	{	CONST_resId_ifSaveStandardPolicy,			CONST_str_ifSaveStandardPolicy,				},
	{	CONST_resId_standardPolicyCannotBeEmpty,	CONST_str_standardPolicyCannotBeEmpty,		},
	{	CONST_resId_cannotFindSendChannel,			CONST_str_cannotFindSendChannel,			},
	//
	//
	{	CONST_resId_qingqiu,						CONST_str_qingqiu,							},
	{	CONST_resId_tasks,							CONST_str_tasks,							},
	{	CONST_resId_tempGroup,						CONST_str_tempGroup,						},
	{	CONST_resId_ifStopScreenSharingRemoteAssist,CONST_str_ifStopScreenSharingRemoteAssist,	},
	{	CONST_resId_howToEnlarge,					CONST_str_howToEnlarge,						},
	{	CONST_resId_quXiao,							CONST_str_quXiao,							},
	{	CONST_resId_canceled,						CONST_str_canceled,							},
	{	CONST_resId_xiangYing,						CONST_str_xiangYing,						},
	//
	{	CONST_resId_pleaseSelect,					CONST_str_pleaseSelect,						},
	{	CONST_resId_canSelect,						CONST_str_canSelect,						},
	{	CONST_resId_select,							CONST_str_select,							},
	{	CONST_resId_toInterupt,						CONST_str_toInterupt,						},
	{	CONST_resId_toRequestAgain,					CONST_str_toRequestAgain,					},
	{	CONST_resId_sendAgain,						CONST_str_sendAgain,						},
	{	CONST_resId_faSong,							CONST_str_faSong,							},
	{	CONST_resId_jieShou,						CONST_str_jieShou,							},

	{	CONST_resId_reqToSend,						CONST_str_reqToSend,						},	
	{	CONST_resId_accept,							CONST_str_accept,							},
	{	CONST_resId_deny,							CONST_str_deny,							},
	{	CONST_resId_interupted,						CONST_str_interupted,						},
	{	CONST_resId_accepted,						CONST_str_accepted,							},
	{	CONST_resId_denied,							CONST_str_denied,							},

	{	CONST_resId_ifExitSession,					CONST_str_ifExitSession,					},
	{	CONST_resId_ifAcceptVideo,					CONST_str_ifAcceptVideo,					},
	{	CONST_resId_willSendFile,					CONST_str_willSendFile,						},
	{	CONST_resId_pleaseRecvFile,					CONST_str_pleaseRecvFile,					},
	{	CONST_resId_recvFinished,					CONST_str_recvFinished,						},
	{	CONST_resId_sendFinished,					CONST_str_sendFinished,						},
	{	CONST_resId_saveAs,							CONST_str_saveAs,							},
	{	CONST_resId_saved,							CONST_str_saved,							},
	{	CONST_resId_zhongDe,						CONST_str_zhongDe,							},
	{	CONST_resId_pcRegistration,					CONST_str_pcRegistration,					},
	{	CONST_resId_askIfDeleteInfo,				CONST_str_askIfDeleteInfo,					},
	{	CONST_resId_message,						CONST_str_message,							},
	{	CONST_resId_allSystemEvent,					CONST_str_allSystemEvent,					},
	{	CONST_resId_ifChangeDb,						CONST_str_ifChangeDb,						},
	{	CONST_resId_cannotConnectToDb,				CONST_str_cannotConnectToDb,				},
	{	CONST_resId_buildDbErr,						CONST_str_buildDbErr,						},
	{	CONST_resId_restart,						CONST_str_restart,							},
	{	CONST_resId_restoreAccess,					CONST_str_restoreAccess,					},
	{	CONST_resId_scope,							CONST_str_scope,							},
	//
	{	CONST_resId_desOfAdminGrp,					CONST_str_desOfAdminGrp,					},
	{	CONST_resId_desOfLogGrp,					CONST_str_desOfLogGrp,						},
	{	CONST_resId_desOfCfgGrp,					CONST_str_desOfCfgGrp,						},
	//	{	CONST_resId_beyondTheScopeOfManagement,		CONST_str_beyondTheScopeOfManagement,		},
	{	CONST_resId_clearupAuditedKnowledge,		CONST_str_clearupAuditedKnowledge,			},
	{	CONST_resId_clearupUnAuditedKnowledge,		CONST_str_clearupUnAuditedKnowledge,		},
	{	CONST_resId_clearupKnowledge,				CONST_str_clearupKnowledge,					},
	{	CONST_resId_clearupPhoneBook,				CONST_str_clearupPhoneBook,					},
	{	CONST_resId_importRecords,					CONST_str_importRecords,					},
	{	CONST_resId_countOfRecords,					CONST_str_countOfRecords,					},
	{	CONST_resId_importFinished,					CONST_str_importFinished,					},
	{	CONST_resId_deleteLogBetween,				CONST_str_deleteLogBetween,					},
	{	CONST_resId_cannotFindVideoDevice,			CONST_str_cannotFindVideoDevice,			},
	{	CONST_resId_rangeOfCorporateStructureLevel,	CONST_str_rangeOfCorporateStructureLevel,	},
	{	CONST_resId_rangeOfAssetNoNumber,			CONST_str_rangeOfAssetNoNumber,				},
	{	CONST_resId_reallyToDelete,					CONST_str_reallyToDelete,					},
	{	CONST_resId_rangeOfNumber,					CONST_str_rangeOfNumber,					},
	{	CONST_resId_whetherToModify,				CONST_str_whetherToModify,					},
	{	CONST_resId_hintToRestartProgram,			CONST_str_hintToRestartProgram,				},
	{	CONST_resId_needAuthCondition,				CONST_str_needAuthCondition,				},
	{	CONST_resId_createGroupFailed,				CONST_str_createGroupFailed,				},
	{	CONST_resId_hintToAddMember,				CONST_str_hintToAddMember,					},
	{	CONST_resId_modifyGroupNameFailed,			CONST_str_modifyGroupNameFailed,			},
	{	CONST_resId_hintToCreateGroup,				CONST_str_hintToCreateGroup,				},
	{	CONST_resId_hintToModifyGroup,				CONST_str_hintToModifyGroup,				},
	{	CONST_resId_askIfRemoveFromGroup,			CONST_str_askIfRemoveFromGroup,				},
	{	CONST_resId_numberIsWrong,					CONST_str_numberIsWrong,					},
	{	CONST_resId_selectGroup,					CONST_str_selectGroup,						},
	{	CONST_resId_selectMessenger,				CONST_str_selectMessenger,					},
	{	CONST_resId_askIfDeletePhoneNumber,			CONST_str_askIfDeletePhoneNumber,			},
	{	CONST_resId_needToSelect,					CONST_str_needToSelect,						},
	{	CONST_resId_online,							CONST_str_online,							},
	{	CONST_resId_offline,						CONST_str_offline,							},
	{	CONST_resId_hintOfModifyId,					CONST_str_hintOfModifyId,					},
	{	CONST_resId_newId,							CONST_str_newId,							},
	{	CONST_resId_hintOfReinput,					CONST_str_hintOfReinput,					},
	{	CONST_resId_hintOfPhoneReinput,				CONST_str_hintOfPhoneReinput,				},
	{	CONST_resId_hintOfRetype,					CONST_str_hintOfRetype,						},
	{	CONST_resId_modifyFailed,					CONST_str_modifyFailed,						},
	{	CONST_resId_askIfDeleteContact,				CONST_str_askIfDeleteContact,				},
	{	CONST_resId_askIfDeleteRegInfo,				CONST_str_askIfDeleteRegInfo,				},
	{	CONST_resId_askIfDeleteTmpRegInfo,			CONST_str_askIfDeleteTmpRegInfo,			},
	{	CONST_resId_whetherOnline,					CONST_str_whetherOnline,					},
	{	CONST_resId_standardUsrInfoFailed,			CONST_str_standardUsrInfoFailed,			},
	{	CONST_resId_whetherToSaveStandardRule,		CONST_str_whetherToSaveStandardRule,		},
	{	CONST_resId_saveStandardRuleFailed,			CONST_str_saveStandardRuleFailed,			},
	{	CONST_resId_invaildIp,						CONST_str_invaildIp,						},
	{	CONST_resId_invaildEndIp,					CONST_str_invaildEndIp,						},
	{	CONST_resId_ipKnowledge,					CONST_str_ipKnowledge,						},
	{	CONST_resId_registryKnowledge,				CONST_str_registryKnowledge,				},
	{	CONST_resId_qyCfgModuleInfo,				CONST_str_qyCfgModuleInfo,					},
	{	CONST_resId_phoneGuest,						CONST_str_phoneGuest,						},
	{	CONST_resId_errOfImportFmt,					CONST_str_errOfImportFmt,					},
	{	CONST_resId_unicodeImportFmt,				CONST_str_unicodeImportFmt,					},
	{	CONST_resId_tooMoreColumn,					CONST_str_tooMoreColumn,					},
	{	CONST_resId_needColumn,						CONST_str_needColumn,						},
	{	CONST_resId_passwordLength,					CONST_str_passwordLength,					},
	{	CONST_resId_passwordWrong,					CONST_str_passwordWrong,					},
	{	CONST_resId_passwordComposed,				CONST_str_passwordComposed,					},
	{	CONST_resId_passwordEmpty,					CONST_str_passwordEmpty,					},
	{	CONST_resId_passwordCannotMatch,			CONST_str_passwordCannotMatch,				},
	{	CONST_resId_passwordSaved,					CONST_str_passwordSaved,					},
	{	CONST_resId_userExisted,					CONST_str_userExisted,						},
	{	CONST_resId_userBelongToOtherGroup,			CONST_str_userBelongToOtherGroup,			},
	{	CONST_resId_dbErr,							CONST_str_dbErr,							},
	{	CONST_resId_dbErrHint,						CONST_str_dbErrHint,						},
	{	CONST_resId_addNewUser,						CONST_str_addNewUser,						},
	{	CONST_resId_userEmpty,						CONST_str_userEmpty,						},
	{	CONST_resId_invalidNumberAndMinIs,			CONST_str_invalidNumberAndMinIs,				},
	{	CONST_resId_invalidNumberAndMaxIs,			CONST_str_invalidNumberAndMaxIs,				},
	//  2009/01/27
	{	CONST_resId_runAsAdmin,						CONST_str_runAsAdmin,						},
	{	CONST_resId_installedProgramDb,				CONST_str_installedProgramDb,				},
	{	CONST_resId_verIs,							CONST_str_verIs,							},
	{	CONST_resId_updateProgramDbVer,				CONST_str_updateProgramDbVer,				},
	{	CONST_resId_renameDbIs,						CONST_str_renameDbIs,						},
	{	CONST_resId_whetherToUpdate,				CONST_str_whetherToUpdate,					},
	{	CONST_resId_isWrong,						CONST_str_isWrong,							},
	{	CONST_resId_mightBe,						CONST_str_mightBe,							},
	{	CONST_resId_updateTo,						CONST_str_updateTo,							},
	{	CONST_resId_Import,							CONST_str_Import,							},
	{	CONST_resId_Export,							CONST_str_Export,							},
	{	CONST_resId_completed,						CONST_str_completed,						},
	{	CONST_resId_folderDoesNotExist,				CONST_str_folderDoesNotExist,				},
	{	CONST_resId_pathIsNotAFolder,				CONST_str_pathIsNotAFolder,					},
	{	CONST_resId_beingProcessed,					CONST_str_beingProcessed,					},
	{	CONST_resId_interrupted,					CONST_str_interrupted,						},
	{	CONST_resId_incorrectUserOrPwd,				CONST_str_incorrectUserOrPwd,				},
	{	CONST_resId_limitedUserAccountCannotLogon,	CONST_str_limitedUserAccountCannotLogon,	},

	//  {	ID_MENU_notUseVfwWebcam,					CONST_str_ID_MENU_notUseVfwWebcam,			},
	//  {	ID_MENU_useVfwWebcam,						CONST_str_ID_MENU_useVfwWebcam,				},
	//
	{	ID_MENU_useWebcam_vfw,						CONST_str_ID_MENU_useWebcam_vfw,			},
	{	ID_MENU_useWebcam_directX,					CONST_str_ID_MENU_useWebcam_directX,		},
	{	ID_MENU_useWebcam_custom,					CONST_str_ID_MENU_useWebcam_custom,			},
	//
	{	CONST_resId_videoConference,				CONST_str_videoConference,					},
	{	CONST_resId_conferenceResources,			CONST_str_conferenceResources,				},
	//
	{	CONST_resId_licenseTimeout,					CONST_str_licenseTimeout,					},
	{	CONST_resId_trialPeriod,					CONST_str_trialPeriod,						},
	{	CONST_resId_days,							CONST_str_days,								},

	//  netMc2 
	{	CONST_resId_qyScannedIpList,				CONST_str_qyScannedIpList,					},
	{	CONST_resId_assetList,						CONST_str_assetList,						},
	{	CONST_resId_pcSecChkEventList,				CONST_str_pcSecChkEventList,				},
	{	CONST_resId_pcRuleList2,					CONST_str_pcRuleList2,						},
	{	CONST_resId_pcNetworkPropList,				CONST_str_pcNetworkPropList,				},
	{	CONST_resId_pcNetworkRuleList2,				CONST_str_pcNetworkRuleList2,				},
	{	CONST_resId_pcProxyCfgPropList2,			CONST_str_pcProxyCfgPropList2,				},
	{	CONST_resId_pcProxyCfgRuleList2,			CONST_str_pcProxyCfgRuleList2,				},
	{	CONST_resId_pcComputerPropList2,			CONST_str_pcComputerPropList2,				},
	{	CONST_resId_pcComputerRuleList2,			CONST_str_pcComputerRuleList2,				},
	{	CONST_resId_pcWindowsUpdatePolicyPropList,	CONST_str_pcWindowsUpdatePolicyPropList,	},
	{	CONST_resId_pcWindowsUpdatePolicyRuleList,	CONST_str_pcWindowsUpdatePolicyRuleList,	},
	{	CONST_resId_pcProcessPropList2,				CONST_str_pcProcessPropList2,				},
	{	CONST_resId_pcProcessModulePropList,		CONST_str_pcProcessModulePropList,			},
	{	CONST_resId_pcProcessRuleList2,				CONST_str_pcProcessRuleList2,				},
	{	CONST_resId_pcNetFlowPropList,				CONST_str_pcNetFlowPropList,				},
	{	CONST_resId_pcNetFlowPropList_ethernet,		CONST_str_pcNetFlowPropList_ethernet,		},
	{	CONST_resId_pcNetSharePropList,				CONST_str_pcNetSharePropList,				},
	{	CONST_resId_pcPrinterPropList2,				CONST_str_pcPrinterPropList,				},
	{	CONST_resId_pcRegistryList,					CONST_str_pcRegistryList,					},
	{	CONST_resId_pcRegistryRuleStatusList,		CONST_str_pcRegistryRuleStatusList,			},
	{	CONST_resId_pcEventLogList,					CONST_str_pcEventLogList,					},
	{	CONST_resId_pcOsUsrList,					CONST_str_pcOsUsrList,						},
	{	CONST_resId_qyPcNetStatList,				CONST_str_qyPcNetStatList,					},
	//
	{	CONST_resId_wuserverAddr,					CONST_str_wuserverAddr,						},
	{	CONST_resId_overall,						CONST_str_overall,							},
	{	CONST_resId_disable,						CONST_str_disable,							},
	{	CONST_resId_baoJingLiuLiang,				CONST_str_baoJingLiuLiang,					},
	{	CONST_resId_detectionFrequency,				CONST_str_detectionFrequency,				},
	{	CONST_resId_liuLiangBaoJingShiShiFouZuDuan,	CONST_str_liuLiangBaoJingShiShiFouZuDuan,	},
	{	CONST_resId_monPics,						CONST_str_monPics,							},
	{	CONST_resId_cancelMonDesktop,				CONST_str_cancelMonDesktop,					},
	//
	{	CONST_resId_qyHint_netMcDelPcs,				CONST_qyHint_netMcDelPcs,					},
	{	CONST_resId_qyHint_netMcDelPcUsr,			CONST_qyHint_netMcDelPcUsr,					},
	{	CONST_resId_qyHint_netMcDelPcRule,			CONST_qyHint_netMcDelPcRule,				},
	{	CONST_resId_qyHint_netMcDelProxy,			CONST_qyHint_netMcDelProxy,					},
	{	CONST_resId_qyHint_netMcDelPcSp,			CONST_qyHint_netMcDelPcSp,					},
	{	CONST_resId_qyHint_netMcDelPcUsrInTab1,		CONST_qyHint_netMcDelPcUsr,					},
	{	CONST_resId_qyHint_netMcDelPcRegistryInfo,	CONST_qyHint_netMcDelPcRegistryInfo,		},
	{	CONST_resId_cancelFailed,					CONST_str_cancelFailed,						},
	{	CONST_resId_deleteConnectionManually,		CONST_str_deleteConnectionManually,			},
	{	CONST_resId_thePortandMacIs,				CONST_str_thePortandMacIs,					},
	{	CONST_resId_askIfDeleteId,					CONST_str_askIfDeleteId,					},
	{	CONST_resId_askIfDeleteTmpId,				CONST_str_askIfDeleteTmpId,					},
	{	CONST_resId_askIfDeleteMsgr,				CONST_str_askIfDeleteMsgr,					},
	//
	{	CONST_resId_askIfDeleteBrowsingHistory,		CONST_str_askIfDeleteBrowsingHistory,		},
	{	CONST_resId_askIfDeleteRegistry,				CONST_str_askIfDeleteRegistry,			},
	{	CONST_resId_askIfDeleteWindowsLog,			CONST_str_askIfDeleteWindowsLog,			},
	{	CONST_resId_askIfDeleteUserAccount,			CONST_str_askIfDeleteUserAccount,			},
	{	CONST_resId_askIfDeleteNetstat,				CONST_str_askIfDeleteNetstat,				},
	{	CONST_resId_askIfDeletePrinter,				CONST_str_askIfDeletePrinter,				},
	{	CONST_resId_askIfDeleteProcess,				CONST_str_askIfDeleteProcess,				},
	{	CONST_resId_askIfDeleteRule,					CONST_str_askIfDeleteRule,				},
	{	CONST_resId_askIfDeleteFlow,					CONST_str_askIfDeleteFlow,				},
	{	CONST_resId_askIfDeleteNetSharing,				CONST_str_askIfDeleteNetSharing,			},
	//
	{	CONST_resId_askIfDeleteConnection,				CONST_str_askIfDeleteConnection,			},
	{	COSNT_resId_warningToKillProcess,				COSNT_str_warningToKillProcess,				},
	{	CONST_resId_existRule,							CONST_str_existRule,						},
	{	CONST_resId_askIfChangeDesignetedToProhibit,	CONST_str_askIfChangeDesignetedToProhibit,	},
	{	CONST_resId_askIfChangeUniformToProhibit,		CONST_str_askIfChangeUniformToProhibit,		},
	{	CONST_resId_askIfKillDesignetedPcProcess,		CONST_str_askIfKillDesignetedPcProcess,		},
	{	CONST_resId_askIfKillProcess,					CONST_str_askIfKillProcess,					},
	{	CONST_resId_macChanged,							CONST_str_macChanged,},
	{	CONST_resId_invalidQwm,							CONST_str_invalidQwm,			},
	{	CONST_resId_checkForProxyServer,				CONST_str_checkForProxyServer,				},
	{	CONST_resId_qyIntraConn,						CONST_str_qyIntraConn,						},
	{	CONST_resId_qyOnInternet,						CONST_str_qyOnInternet,						},
	{	CONST_resId_changeCapScreenPolicy,				CONST_str_changeCapScreenPolicy,					},
	{	CONST_resId_changeCapScreenDir,					CONST_str_changeCapScreenDir,						},
	{	CONST_resId_changeCapScreenInterval,			CONST_str_ChangeCapScreenInterval,				},


	{	CONST_resId_anotherLogonExists,					CONST_str_anotherLogonExists,				},
	{	CONST_resId_areYouSure,							CONST_str_areYouSure,						},
	{	CONST_resId_willYouClose,						CONST_str_willYouClose,						},
	//{	CONST_resId_cancelAV,							CONST_str_cancelAV,							},
	{	CONST_resId_seconds,							CONST_str_seconds,							},
	{	CONST_resId_automaticallyCanceled,				CONST_str_automaticallyCanceled,			},
	{	CONST_resId_after,								CONST_str_after,							},
	{	CONST_resId_doYouWantToExit,					CONST_str_doYouWantToExit,					},
	{	CONST_resId_searchingServer,					CONST_str_searchingServer,					},
	{	CONST_resId_tryToConnect,						CONST_str_tryToConnect,						},
	{	CONST_resId_cannotFindServer,					CONST_str_cannotFindServer,					},
	{	CONST_resId_failedToLogon,						CONST_str_failedToLogon,					},
		

	//
	{	CONST_resId_yingJianReport,					CONST_ID_yingJianReport,								},

	//
	{	CONST_resId_total,							_T(  "总计"  ),	},
	{	-1,											NULL,					},
};



